### ISSUE TITLE
Add kedro-viz as optional dependency in setup.py

### ISSUE THREAD

**Issue by lucasjamar** [quantumblacklabs/kedro#1004]
## Description
There are some projects that I built in a hurry in kedro~=0.16 many months ago. I did not add kedro-viz to the requirements.in.
Going back to the project now with a new virtual env, I cannot run kedro-viz with the latest version of kedro-viz. So i simply downloaded a version of kedro-viz that I found on pypi was released at more or less the same time I did this project.

## Possible Implementation
It would be cool to add kedro-viz to the list of extras_require in setup.py. That way, in the requirements.in, we can simply specify kedro[viz]==0.17.5.

If no one objects, I can try to implement this in my free time :)

**Comment by lucasjamar** [comment]
Im unable to reproduce the error. I guess I was having some other dependency issue which i confused for kedro-viz. sorry :(

**Comment by datajoely** [comment]
No worries - thanks for following up @lucasjamar
