### ISSUE TITLE
Allow custom SQL query for GBQTableDataSet

### ISSUE THREAD

**Issue by simonpicard** [quantumblacklabs/kedro#1032]
## Description
Similar to SQLTableDataSet and SQLQueryDataSet, I would like to have a GBQQueryDataSet where I can specify to query to run on GBQ.

## Context
I am building a data pipeline where I increment data every day in GBQ tables, therefore I need to be able to select a portion of the data which has not been processed yet.

## Possible Implementation
Create a new class inheriting from GBQTableDataSet with an extra arg `sql`.
`sql`is then passed to `pd.read_gbq` as is in the `_load`function.
I actually implemented it that way as a custom dataset for my project.

## Possible Alternatives
n/a

Thanks for reading!

**Comment by datajoely** [comment]
Hi @simonpicard  thanks for raising the issue - makes sense and I'll add it to the backlog.

If you need it quickly the best thing to do is to implement it yourself by inheriting the existing class and customising it for your own purposes. There are some instructions [on how to do this here](https://kedro.readthedocs.io/en/stable/07_extend_kedro/03_custom_datasets.html).

If you do manage to implement this we would really appreciate a PR if you have the time? In theory it should match the [pandas.SQLQueryDataSet](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.pandas.SQLQueryDataSet.html) implementation + [the nifty recent contribution](https://github.com/quantumblacklabs/kedro/pull/887) to point to a *.sql file.

**Comment by lorenabalan** [comment]
Closing this as resolved in #1039

**Comment by lorenabalan** [comment]
Thank you @simonpicard!!
