### ISSUE TITLE
Should we change our datetime format to ISO 8601?

### ISSUE THREAD

**Issue by AntonyMilneQB** [quantumblacklabs/kedro#1050]
Thanks to @tynandebold for bringing this up!

## Should we change our datetime format to ISO 8601? Vote 👍 for yes; 👎 for no.

Currently our version format (used for versioned datasets and session run IDs) is this:
```
YYYY-MM-DDTHH.mm.ss.sssZ
```
It's been this way [since the beginning](https://github.com/quantumblacklabs/kedro/blob/0.14.0/kedro/io/core.py#L337). This format is very close, but not quite identical, to the [ISO 8601 standard](https://en.wikipedia.org/wiki/ISO_8601), which is:
```
YYYY-MM-DDTHH:mm:ss.sssZ
```
The only difference is `:` rather than `.` separating `HHmmss`.

While working on experiment tracking in kedro-viz, @tynandebold is facing difficulties because our date format isn't quite correct. The [JavaScript Date object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date) expects dates formatted in ISO 8601 and can't handle our date format. He needs to do this to convert the date string:
```
const standardizedTime = '2021-11-08T18.31.01.171Z'.replaceAll('.', ':');
```
This works ok but is obviously hacky and annoying when the string we're supplying is so close to ISO 8601 but not quite right.

**Pros of changing**
* We'll be following the standard correctly
* Slightly smoother integration with kedro-viz (and presumably other tools that expect ISO 8601 dates)

**Cons of changing**
* It'll be a breaking change and a hassle. Anyone upgrading kedro who is using versioned datasets would need to convert all their existing datasets to the new version format - we could provide some script to help with this migration
* The current kedro-viz hack works ok and AFAIK this never caused any problems before

If we _do_ want to change this then I think we should do so sooner rather than later, since experiment tracking is going to be increasingly relying on the session ID. It'll be more annoying to change this in the future than now (0.18).

**Comment by lorenabalan** [comment]
I believe this was intentional as some systems won't let you write a file with `:` in the name. So I vote leave it as is.

**Comment by AntonyMilneQB** [comment]
> I believe this was intentional as some systems won't let you write a file with `:` in the name. So I vote leave it as is.

This is a pretty compelling argument. Indeed it seems that `:` isn't allowed in a filename in Windows, so I don't think we can change this unless we don't use the version timestamp as a filename, which would need a whole new system and be a big and annoying change.
