### ISSUE TITLE
'build-docs' when following spaceflights tutorial results in error; ResolutionImpossible

### ISSUE THREAD

**Issue by fantasticle** [quantumblacklabs/kedro#1052]
## Description
I was following along the tutorial on your website and installed the already preconfigured spaceflights tutorial. When I want to build the documentation an error occurs.

## Context
How has this bug affected you? What were you trying to accomplish?

## Steps to Reproduce
1. Follow the spaceflights tutorial.
2. https://kedro.readthedocs.io/en/stable/03_tutorial/05_package_a_project.html => `kedro build-docs`

## Expected Result
I expect the dependencies to not result in an error when following the official documentation.

## Actual Result

```python
ERROR: Cannot install kedro-tutorial[docs]==0.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    kedro-tutorial[docs] 0.1 depends on ipykernel==6.5.0
    kedro-tutorial[docs] 0.1 depends on ipykernel~=5.3

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
WARNING: You are using pip version 21.2; however, version 21.3.1 is available.
You should consider upgrading via the '/home/fantasticle/myproject/.myvenv/bin/python -m pip install --upgrade pip' command.
```

## Your Environment
* Ubuntu 20.04 server edition, 16GB RAM and 4 cores, hosted VM
* Python 3.8 running in venv
* kedro 0.17.5

**Comment by AntonyMilneQB** [comment]
Hello @fantasticle, thanks very much for the report and sorry this isn't working. Please can you go into your setup.py file and find the lines that look like this?

```
extras_require={
        "docs": [
            ...
        ]
```
and tell me what's in there?

If you have `ipykernel~=5.3"` then trying changing that to `ipykernel>=5.3, <7.0` and re-running the `build-docs` command.
