### ISSUE TITLE
cannot create a new parameter file<Title>

### ISSUE THREAD

**Issue by mohannad21** [quantumblacklabs/kedro#1056]
## Description
I started to create a parameter file for my project. With time the parameter file became complicated so I want to split it into 3 parameter files: cleansing_paramaters, engineering_parameters and training parameters. 
The problem is that Kedro does not recognize the new file, e.g. conf/base/engineering_parameters.yml, as a configuration, so I cannot add it to the new node. 

    f"Pipeline input(s) {unsatisfied} not found in the DataCatalog"
ValueError: Pipeline input(s) {'train_parameters'} not found in the DataCatalog

## Your Environment
* Kedro version: 0.17.5:
* Python version: Python 3.7.11

**Comment by AntonyMilneQB** [comment]
Try `parameters_X.yml` instead of `X_parameters.yml` 🙂  https://kedro.readthedocs.io/en/latest/04_kedro_project_setup/02_configuration.html#load-parameters

**Comment by mohannad21** [comment]
Hi Antony, thanks for your quick response. 
unfortunately it still does not work

![image](https://user-images.githubusercontent.com/9336813/142856744-8a62b20c-8d64-475d-b38a-24cac21bbf3f.png)


error: 
    f"Pipeline input(s) {unsatisfied} not found in the DataCatalog"
ValueError: Pipeline input(s) {'parameters_dataScience'} not found in the DataCatalog

**Comment by AntonyMilneQB** [comment]
Ah, I see what you're doing here. When you create a parameters file it doesn't create a new catalog entry; there's only one `parameters` catalog entry that will contain _everything_ in all three of those parameters files.

If you want to pass in only a subset of your parameters into a node then you will need to define a top-level key inside your `parameters_dataScience.yml` file:
```
data_science:
    something: 1
    blah: 2
```

and then you can pass `params:data_science` as a node input.

**Comment by mohannad21** [comment]
Thanks a lot, it works! ;)

**Comment by AntonyMilneQB** [comment]
Perfect, thanks for confirming!
