### ISSUE TITLE
Git dependency is blocking production deployments

### ISSUE THREAD

**Issue by ppsimatikasmck** [quantumblacklabs/kedro#1062]
## Description

The latest version of kedro has a strong dependency of having git installed on the deployed machine. https://github.com/quantumblacklabs/kedro/blob/0.17.5/kedro/framework/cli/starters.py#L45

## Context

Our production servers do not have git installed, so that requirement must be removed.

## Solution

I see in master branch it is fixed: https://github.com/quantumblacklabs/kedro/blob/master/kedro/framework/cli/starters.py#L385

Can you please make a new patch release?

**Comment by lorenabalan** [comment]
Hi @ppsimatikasmck, a new version of kedro was released last week, closing this as resolved.
