### ISSUE TITLE
cannot import name 'SparkDataSet' from 'kedro.extras.datasets.spark'

### ISSUE THREAD

**Issue by jeannefukumaru** [quantumblacklabs/kedro#1073]
## Description
Cannot import or list `SparkDataSet` with `from kedro.extras.datasets.spark import SparkDataSet`

## Context
Was trying to create a `SparkDataSet` within Kedro for a Spark DataFrame and this error was thrown (was working fine the day before) 

## Steps to Reproduce
1. create conda environment `conda create --name=kedro python=3.8 -y` && `conda activate`
2. install kedro and verify version `kedro              0.17.5`
3. open python interpreter and import SparkDataSet class

## Expected Result
SparkDataSet should import successfully. 

## Actual Result
error: `cannot import name 'SparkDataSet' from 'kedro.extras.datasets.spark`

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.17.5
* Python version used (`python -V`): 3.8.12
* Operating system and version: MacOS BigSur version 11.6 and Databricks Notebook

**Comment by datajoely** [comment]
Hi @jeannefukumaru  - I suspect you solved this by doing `pip install "kedro[spark.SparkDataSet]"`. Did this fix it for you?
