### ISSUE TITLE
[KED-1154] Streamlt Use Cases

### ISSUE THREAD

**Issue by arita37** [quantumblacklabs/kedro#115]
## Description
some use examples with stramlit will be useful.

**Comment by benjaminjack** [comment]
Is there anything in particular that you're interested in seeing in an example streamlit app? I've built Plotly Dash apps that integrate with kedro. Streamlit should be pretty straight-forward.

**Comment by arita37** [comment]
Hello,

Thanks for replying.

Streamlit was developed by experienced people
(GoogleX,...) to remove the need of javascript, html when building a front end GUI.

Main strength :
   Minimal code and intuive flow.
   Python only for front end (!!!), more effort toward removing “javascript” is great.

can be integrated in a docker style, 
standalone app.


There is a NYC taxi minimal app, 
which can be a good case of integration
example with Kedro
https://github.com/streamlit/demo-uber-nyc-pickups/blob/master/app.py



Use case of streamlit :
https://news.ycombinator.com/item?id=21127528


Also, their API is really well designed (“user first” perspective), it should be an inspiration for many people.

**Comment by yetudada** [comment]
Hi @arita37, we give our teams the freedom to use whichever GUI interface for their pipeline results. Have you had any experience with Streamlit and would like to pick up this work?

**Comment by lucasjamar** [comment]
There is this new [example](https://www.youtube.com/watch?v=fYkVtzXUEBE&feature=emb_logo) from DE1
