### ISSUE TITLE
Jupyter notebooks within VS Code

### ISSUE THREAD

**Issue by benjaminjack** [quantumblacklabs/kedro#116]
## Description
The October release of the Python VS Code extension introduced support for [natively editing/running/interacting with Jupyter notebooks](https://devblogs.microsoft.com/python/python-in-visual-studio-code-october-2019-release/). Currently, this native editing functionality does not work with kedro, I assume because of the start-up scripts that run when you run `kedro jupyter notebook` instead of `jupyter notebook`. Is it possible to edit/run kedro jupyter notebooks within VS Code? Could we add a guide for this in the docs?

## Context
I switch back and forth between Jupyter notebooks (for exploration/interactive development) and VS Code (for editing nodes, data catalog, etc.). Now that VS Code has native support for jupyter notebooks, it would be great if I could use just one tool for all my kedro development needs!

**Comment by mzjp2** [comment]
One workaround is to use the `>Python: Specify Jupyter Server URI` and `>Type in the [...]`, copy in the `http://127.0.0.1:8888/?token=x` string that doing `kedro jupyter notebook` gives you on startup. It's not ideal, but it's better than nothing.

See below for how it works on my machine:
![image](https://user-images.githubusercontent.com/30357972/66511035-19e34c80-eace-11e9-8fd0-9adf41a99017.png)

**Comment by benjaminjack** [comment]
Thanks this seems like a reasonable workaround. Anyway we could turn this into a 'kedro run' VS Code task that automatically starts up the jupyter notebook and sets the proper URI?

**Comment by mzjp2** [comment]
> Thanks this seems like a reasonable workaround. Anyway we could turn this into a 'kedro run' VS Code task that automatically starts up the jupyter notebook and sets the proper URI?

It'd certainly be possible to write up an extension that does exactly this, but it seems like something overly small and niche to write an extension for. I'll have a look at what you can do with native `vscode` itself and report back. :)

**Comment by lorenabalan** [comment]
Closing this as answered, please feel free to open a new one if you have further concerns.

**Comment by AndrewLaganaro** [comment]
I support this request, I've just discovered Kedro a few weeks ago and I as quite disappointed that it doesn't have yet a seemingly integration with Vs code notebooks. As recent updates goes in Vs code, it's notebooks became quite handful to use, not to say all the database/cloud integration we have with vs code extensions alone. All this functionality could be used together with kedro to improve data science developing on it even more.

Please, consider making it easier to plug kedro into vs code notebooks. Vs code is my main development IDE, It'd be quite useful to have a button or a command palette option to connect Kedro with Vscode's notebooks :)

**Comment by mzjp2** [comment]
This should be significantly easier to do now with the Kedro IPython extension.

**Comment by ChronoJon** [comment]
It's now very easy to do. Just run `%load_ext kedro.extras.extensions.ipython`. Afterwards, the `%reload_kedro` cell magic works in VS Code.

![image](https://user-images.githubusercontent.com/12965550/158023647-d817658a-1a2c-4b27-8825-07bb1fe33584.png)

**Comment by mjspier** [comment]
in 2024 the command to load the extension is

`%load_ext kedro.ipython`

**Comment by trojblue** [comment]
in case anyone stunbled upon it there's a doc page for it: https://docs.kedro.org/en/stable/notebooks_and_ipython/kedro_and_notebooks.html
