### ISSUE TITLE
[KED-1110] "src/getting_started/nodes/example.py" file not getting generated in hello world tutorial

### ISSUE THREAD

**Issue by ajit555db** [quantumblacklabs/kedro#118]
## Description
src/getting_started/nodes/example.py file not getting generated as per example pipeline tutorial
https://kedro.readthedocs.io/en/latest/02_getting_started/04_hello_world.html

kedro new --config config.yml

## config.yml

output_dir: .
project_name: Getting Started
repo_name: getting-started
python_package: getting_started
include_example: true

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`):
Name: kedro
Version: 0.15.2
Summary: Kedro helps you build production-ready data and analytics pipelines
Home-page: https://github.com/quantumblacklabs/kedro
Author: QuantumBlack Labs
Author-email: None
License: Apache Software License (Apache 2.0)
Location: /home/ajit/miniconda3/envs/data/lib/python3.7/site-packages
Requires: requests, cookiecutter, click, memory-profiler, toposort, anyconfig, python-json-logger, xlsxwriter, PyYAML, s3fs, pip-tools, pyarrow, pandas, SQLAlchemy, tables, xlrd
Required-by: 

* Python version used (`python -V`):
Python 3.7.3

* Operating system and version:
Ubuntu 18.04

**Comment by lorenabalan** [comment]
Addressed in https://github.com/quantumblacklabs/kedro/commit/52632c5b4c28fc80464378c757e15abf82a23db9
