### ISSUE TITLE
Documentation enhancements (extend FAQs)

### ISSUE THREAD

**Issue by stichbury** [quantumblacklabs/kedro#12]
## Description
Since open sourcing, a few questions have been raised that an official FAQ can answer neatly for re-use and to provide information/education.

Also add some minor tweaks to section headings in the Data Catalog content for the Advanced User Guide

## Context
Adding this change improves the docs

## Checklist
Include labels so that we can categorise your issue:

- [ ] Add a "Component" label to the issue
- [ ] Add a "Priority" label to the issue

**Comment by stichbury** [comment]
Fixed by PR https://github.com/quantumblacklabs/kedro/pull/13

**Comment by yetudada** [comment]
Merged #13
