### ISSUE TITLE
[KED-1112] Allow customization of MAX_DESCRIPTION_LENGTH in core.py

### ISSUE THREAD

**Issue by sansagara2** [quantumblacklabs/kedro#120]
## Description
When troubleshooting load/save errors, i'm always frustrated by the fact that the string representation of the dataset truncates after 70 chars. 

## Context
The paths/locations of my catalogs are always really long, so it makes it diffucult to see which exact file has the problem, since that gets truncated.

## Possible Implementation
One possibility would be to have MAX_DESCRIPTION_LENGTH be customizable from the global parameters.

## Possible Alternatives
Onother option is to still cap at 70 chars, but starting from the end. That way, the paths would always show the exact filename.extension

**Comment by lorenabalan** [comment]
Thanks @sansagara2 for raising this! I've tagged this with our internal ticket number to make it easier to track.
