### ISSUE TITLE
[KED-1114] Code example in TemplatedConfig is not according to best practice

### ISSUE THREAD

**Issue by JoostDuisters** [quantumblacklabs/kedro#121]
## Description
In the example the config `config_loader` function (property) from the `KedroContext` class is overwritten. This works, but better practice would be to overload `_create_config_loader `.

Gist of how it should be done:  https://gist.github.com/JoostDuisters/727a20037ddf19c174deb901ba613259

## Context
This is just an update to the comments so won't have any effect on the code.

**Comment by lorenabalan** [comment]
Thank you for raising this, @JoostDuisters ! Closing the issue as it's been resolved in https://github.com/quantumblacklabs/kedro/commit/1a9e13d1838bb62440b71d3ee0e1b13d8e887239 .
