### ISSUE TITLE
[KED-1116] Python 3.8 support

### ISSUE THREAD

**Issue by Pet3ris** [quantumblacklabs/kedro#124]
## Description

What's the timeline for 3.8 support? Kedro is currently marked as `<3.8`, but I assume few problems exist to allow 3.8?

## Context
New version of Python.

## Possible Implementation
-

## Possible Alternatives
-

**Comment by 921kiyo** [comment]
@Pet3ris Thank you for opening the feature request! We will discuss this internally :)

**Comment by DmitriiDeriabinQB** [comment]
@Pet3ris We had a stab at it, and encountered some compatibility issues downstream. Specifically, `numpy` C-modules are not being installed properly on Python 3.8 on conda. We will keep track of it and get back you when we have any progress.

**Comment by lorenabalan** [comment]
Update: conda & numpy seem to be fine. Currently blocked by https://github.com/apache/arrow/pull/5685

**Comment by Pet3ris** [comment]
Have Arrow started building 3.8 wheels? See here: https://github.com/apache/arrow/commit/6c6754aa5fb840466dfd618ca5b6ae7ca72ebbfa. Does this mean 3.8 is good to go?

**Comment by Pet3ris** [comment]
FYI @921kiyo @DmitriiDeriabinQB @lorenabalan

**Comment by DmitriiDeriabinQB** [comment]
The latest `pyarrow` version 0.15.1, unfortunately, [does not come with Python 3.8 wheels](https://github.com/apache/arrow/pull/5685#issuecomment-564088923), so running `pip install pyarrow` fails on 3.8 at the moment: "[Best guess would be end of January but it may be sometime in February](https://github.com/apache/arrow/pull/5685#issuecomment-564116890)"

**Comment by lorenabalan** [comment]
Hey guys, latest commit on develop aims to enable 3.8 compatibility https://github.com/quantumblacklabs/kedro/commit/fe489536398408761274f6c1e3d820649b7c0b5e - feel free to have a play and let us know if you find any issues. Please note that `pyspark` is a known issue.

**Comment by lorenabalan** [comment]
Thank you for the feature request! I am now closing this as Python 3.8 compatibility was enabled starting with version 0.16.0 released today.
