### ISSUE TITLE
Support for ETL-like functionality with catalog items

### ISSUE THREAD

**Issue by bhilliard** [quantumblacklabs/kedro#126]
## Description
It's common for production databases to have the same table repeated across tenant databases/schemas. For example: [customer_id].[orders] for customers 123, 456 and 789. It would be nice to have an approach for more complicated ETL that also fits the kedro data loader model.

## Context
I can't figure out how I should construct a single table from these tables without some overly complicated SQL. I know I can write a python function to loop over customer ids and merge all the tables, but I'm not sure how to make that approach fit with the kedro mindset. 

Am I missing an option? Or is there another reasonable work around?

**Comment by DmitriiDeriabinQB** [comment]
@bhilliard Thank you for your feedback. 

One approach could be to encapsulate this logic into a custom SQL dataset (which, by the way, can leverage the standard `SQLTableDataSet` under the hood). So on load wrapper SQL dataset can iterate through your customer ids, call `SQLTableDataSet.load()` for each table individually and finally combine the results into a single dataframe. Please see [CachedDataSet](https://github.com/quantumblacklabs/kedro/blob/develop/kedro/contrib/io/cached/cached_dataset.py) implementation for some ideas about handling one dataset inside the other. 

Please let us know if it helps resolve your issue.

**Comment by lorenabalan** [comment]
Closing this as answered, but please feel free to open a new issue if you need additional help. :)
