### ISSUE TITLE
Typo in Tutorial

### ISSUE THREAD

**Issue by thgaertner** [quantumblacklabs/kedro#127]
## Typo
There is a typo in the kedro documentation. In [Creating-Custom-Dataset](https://kedro.readthedocs.io/en/latest/03_tutorial/03_set_up_data.html#creating-custom-datasets) for windows user you find the command
`mkdir src\kedro_turorial\io && type nul > src\kedro_turorial\io\__init__.py
`.  I think for further user it would be nice to fix this issue, because the next step does not work with it. 

Best regards!

**Comment by 921kiyo** [comment]
Thank you for reporting this! Could you point out where the typo is (or open a PR if you know how to fix it)?

**Comment by thgaertner** [comment]
In the example it is tu**r**orial instead of tu**t**orial. It is the first code for windows:

`mkdir src\kedro_turorial\io && type nul > src\kedro_turorial\io\__init__.py`
 has to be
`mkdir src\kedro_tutorial\io && type nul > src\kedro_turorial\io\__init__.py`
