### ISSUE TITLE
Process multiple XLS/XLSX files from a S3 bucket

### ISSUE THREAD

**Issue by NeerajMalhotra-QB** [quantumblacklabs/kedro#133]
## Description
I am looking for IO catalog to read multiple XLS/XLSX files at once and load save them as parquet file under another bucket.

## Context
Often we receive multiple excel files as datasets from clients and as of now, we are loading them individually through pandas which is inefficient. It will save lots of time to handle all files at once.

## Possible Implementation
I have some work done in this direction and will like to contribute for review and help others in the organisation.

## Possible Alternatives
(Optional) Describe any alternative solutions or features you've considered.

**Comment by iver56** [comment]
I have recently had the same kind of issue, and the kedro documentation didn't help me with it. Normally my dataset consists of _multiple_ files in a bucket, and not a single file in a bucket. My solution for now is to create a separate pipeline step that looks up all the files in the cloud service and compiles them down to one local pickle dataset. That pipeline step has no input.

**Comment by yetudada** [comment]
Thanks for raising this! @iver56 and @NeerajMalhotra-QB, we're releasing `kedro 0.15.5` soon and we've come up with a way to load a directory of files or folders with something called the `PartitionedDataSet`. It will solve this issue in a file type agnostic way. I'm going to close this issue and the PR for this in the meanwhile. 

But please check out the docs for this: https://kedro.readthedocs.io/en/latest/04_user_guide/08_advanced_io.html#partitioned-dataset
