### ISSUE TITLE
Inconsistent behaviour in TemplatedConfigLoader when parameters are missing.

### ISSUE THREAD

**Issue by JoostDuisters** [quantumblacklabs/kedro#136]
## Description
There is an inconsistency in the way missing parameters are handled in TemplatedConfigLoader. The intended behaviour is that whenever a parameter is missing in the `globals.yml` or in the `globals_dict`, then the `${...}` string gets returned.

This works fine when the entire string consists of the `${...}` bit. 

Example:
When you have 
```
path1: "${param1}"
```
in your yml file, but `param1` is missing from the `globals.yml` or the `feed_dict`, then you get
```
>>> catalog['path1']
'${param1}'
```

But when you have 
```
path2: "${param1}/${param2}/${param3}"
```
with none of `param1`, `param2` or `param3` in your config, you get:
```
>>> catalog['path2']
'None/None/None'
```

## Context
It is not a huge problem because when the parameters are missing the config entry is probably useless anyway. It is inconsistent and unintended behaviour though.

## Steps to Reproduce
![image](https://user-images.githubusercontent.com/41304973/67330505-c1c03780-f51c-11e9-91ee-d09bbc703584.png)

## Expected Result
In above example:
```
>>> catalog['path2']
'${param1}/${param2}/${param3}'
```

## Actual Result
Tell us what happens instead.

```
>>> catalog['path1']
'${param1}'
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`):
* Python version used (`python -V`):
* Operating system and version:

**Comment by JoostDuisters** [comment]
This PR highlights the problem with a unittest: https://github.com/quantumblacklabs/kedro/pull/137

**Comment by Flid** [comment]
Obsolete by the latest Kedro changes, adding default values to the formatting.
