### ISSUE TITLE
[KED-1009] Dask Integration

### ISSUE THREAD

**Issue by yetudada** [quantumblacklabs/kedro#144]
## Description

Dask is an open-source project that allows you to parallelise operations over NumPy Arrays, Pandas Dataframes and regular lists. QB users have been steadily adopting the tool because it speeds up their workflow.

**More information about Dask**
- GitHub URL: [https://github.com/dask/dask](https://github.com/dask/dask)
- Website: [https://dask.org/](https://dask.org/) 

## Context

Dask would allow data scientists to scale their Python workflow and offer an alternative dataset type for Data Engineers.

**Comment by et2010** [comment]
What about modin: https://github.com/modin-project/modin

**Comment by yetudada** [comment]
Thanks for the flag on Modin @et2010! I'm going to close this ticket for now, as actual adoption of Dask has been mixed. We'll park this ticket for now and are open to re-opening it, if it becomes the standard. Some user queries that we have heard include that there is a learning curve to configure it. 

There is elementary support in Kedro though, please have a look at the [`dask.ParquetDataSet`](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.dask.ParquetDataSet.html) for more information.
