### ISSUE TITLE
[KED-1147] Incremental Dataset Loading

### ISSUE THREAD

**Issue by yetudada** [quantumblacklabs/kedro#145]
## Description

An Incremental Dataset is a dataset, which only loads newly arrived data, and when saving, appends the results on top of already existing data. 

This is useful for applications where you get new data every day or week and this will help reduce processing time because you don't have to re-run the whole pipeline with all of the data. This affects data engineers and applies to use cases touching banking or manufacturing where data updates every day.  

## Context

This feature is marked as `Increase adoption` or `Maximise delight` for Kedro because we have discovered that some users have not used Kedro for this reason and because it causes pipeline performance issues. Some users have indicated that they have also built their own solutions to this problem.

**Comment by yetudada** [comment]
This will be available in the next release: https://kedro.readthedocs.io/en/latest/04_user_guide/08_advanced_io.html#incremental-loads-with-incrementaldataset

**Comment by DmitriiDeriabinQB** [comment]
Fixed in c7af0f3c61a79b309f0396b642c29c54408d518f and d370b8859700c644af7095b32fc685a20ddfafcc
