### ISSUE TITLE
[KED-1171] Kedro CLI command to help catalog cleaning

### ISSUE THREAD

**Issue by jiriklein** [quantumblacklabs/kedro#151]
## Description
New `kedro cli` command that allows the users to easily find deprecated datasets. Raised PR #150 

## Context
The point of this PR is to create a `kedro cli` function that would allow the users to list all redundant catalog entries. This is particularly useful towards the end of a project or during a handover, where project can have hundreds of catalog entries, but some may have been deprecated or replaced.
At the same time, the diff in the other direction is useful as well, as it allows the users to see which `DataSets` are considered to be `MemoryDataSets` and listing those to the user on a `kedro cli` command.

## Possible Implementation
Suggested in PR #150 

## Possible Alternatives
Could be implemented in `core` as opposed to `contrib`. Could include `DataSet` types to omit datasets that are intentionally `MemoryDataSets`.

**Comment by Flid** [comment]
Hello @jiriklein 
First of all, thank you for you contribution, and sorry it took so long to get back to you.
We were discussing the strategic vision for this feature, and indeed we need something like tools to get a better visibility for the catalog, and sone tools to highlight the issues.
What we have in mind:

`kedro catalog info` - shows the basic information about the catalog in a human-readable format. Considering the catalog might be composed of multiple files, with YAML templating etc, it might be very useful.
`kedro catalog analyze` - runs some checks on the catalog and prints the stats and issues found.

Essentially what you are doing is one of the `analyze` checks. The current implementation in the pull request you have kindly created only provides a function with the logic, but doesn't expose it over the CLI interface. Would you like to help us and add a CLI entry point to the template (https://github.com/quantumblacklabs/kedro/blob/develop/kedro/template/%7B%7B%20cookiecutter.repo_name%20%7D%7D/kedro_cli.py - this file), which calls the function you've created? The CLI command should be `kedro catalog analyze`, no parameters are required for now, just run the check and print, we'll extend it in future.

Thank you very much for the contribution!

**Comment by jiriklein** [comment]
Hi @Flid 

Happy to help.
I've added `kedro catalog info` and `kedro catalog analyze` `click` interface calls. 
I agree with the naming convention and will refactor accordingly. 
Is there any particular way you want me to pretty-print?
Cheers

**Comment by Flid** [comment]
Oh cool, thanks for help @jiriklein 
Just to clarify this - I didn't ask you to implement the `info`, and we didn't discuss it yet. If you really want to implement it - we can start with just YAML formatting. Or just remove this entry point for now, we'll add it later.
The `analyze` part - probably YAML also works the best, as it can also be used for other scripts in future, YAML is good for both human and machine readable output.

**Comment by jiriklein** [comment]
Sure @Flid 
I created skeleton functions for both `analyze` and `info` at the moment, before we decided on the output. To clarify when you mean YAML formatting -> does this mean YAML pretty-printing or YAML logging to a file?
Cheers

**Comment by Flid** [comment]
Just get the data you want to return, serialize it into YAML, print. If somebody needs to do additional validation on top or anything - the machine readable format is useful.

**Comment by lorenabalan** [comment]
Closing this as resolved in https://github.com/quantumblacklabs/kedro/commit/30eb0692fac696a971af31de6337412e38105ecd
