### ISSUE TITLE
[KED-1170] `tag` argument in `node` constructor is incorrect in User Guide > Nodes > Tagging Nodes

### ISSUE THREAD

**Issue by benjaminjack** [quantumblacklabs/kedro#152]
## Description
In the [Tagging Nodes](https://kedro.readthedocs.io/en/latest/04_user_guide/05_nodes.html#tagging-nodes) section of the User Guide in the kedro docs, the following example is given:

```
node(func=add, inputs=["a", "b"], outputs="sum", name="adding_a_and_b", tag="node_tag")
```

However, if you look at the documentation for the class `node`, there is no `tag` argument in the constructor. The correct argument is `tags` and it only accepts a list. The corrected example should read:

```
node(func=add, inputs=["a", "b"], outputs="sum", name="adding_a_and_b", tags=["node_tag"])
```

## Context
This error in the documentation makes it difficult to figure out how to use tags effectively with nodes. Overall, I think a consolidated explanation of tagging nodes and tagging pipelines would be helpful.

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.15.1 (also tested on 0.15.3)
* Python version used (`python -V`): 3.6.9
* Operating system and version: MacOS 10.14.6

**Comment by benjaminjack** [comment]
Perhaps related to #148.

**Comment by yetudada** [comment]
@benjaminjack Thanks for flagging this, we managed to resolve this error in our latest release for 0.15.4. However, you do raise a great point about re-doing our tagging documentation so I'll close this ticket but place on our backlog an item to look at that documentation.
