### ISSUE TITLE
Feature : Preprocessor with State in pipeline

### ISSUE THREAD

**Issue by arita37** [quantumblacklabs/kedro#155]
## Description
   If we want to create new features from cluster algorithms, we have the process :  
       train time :  Train the cluster algorithm on data, and cluster the data and output.
       predict time :  Load the cluster algorithm, and cluster the date and output.

There is a need to save the state of cluster algo (ie pre-trained ) and re-use it.

As the pipeline node is functional, 
how do you make differences between train and predict time ?

**Comment by tolomea** [comment]
you can use tags to tag the different parts of your pipeline and then only run the predict parts

**Comment by arita37** [comment]
Thanks.
Can you specify a bit “Tag” by small example ?

Isn’t cleaner to use :
   fit
   fit_transform and embed in class for the serialization ?

rather a “tag” ?

**Comment by yetudada** [comment]
Hi @arita37, you can see an example of how to use tags here: https://kedro.readthedocs.io/en/latest/03_tutorial/04_create_pipelines.html#using-tags 

Tags allow you to run partial pipelines so you would be able to separate train and predict within your pipeline.

**Comment by arita37** [comment]
Better to give concrete pipeline example
with train and test.

Because model  needs to  be seeialized !!!

**Comment by yetudada** [comment]
@arita37 We are open to modifications in our documentation to raise this example and hope you can pick this up. I'm going to close this ticket because we've indicated a way to do this. Thanks for the comment!
