### ISSUE TITLE
[KED-1129] Nodes with a list of arguments that includes a repeated argument throw a ValueError when running

### ISSUE THREAD

**Issue by simon-b** [quantumblacklabs/kedro#159]
## Description
If a node argument list contains the same argument more than once, then an error is thrown rather than the node's func being called with the repeated arg in the appropriate places.

## Steps to Reproduce

Simple example illustrating the problem:
```python
def add(a, b):
    return a + b

pipeline = Pipeline(
    [
        node(add, ["a", "b"], outputs="a_and_b", name="add_a_b"),
        node(add, ["a", "a"], outputs="twice_a", name="add_a_a"),
        node(add, ["b", "b"], outputs="twice_b", name="add_b_b"),
    ]
)
```

I would expect this to work fine, but instead produces the following error:
> ValueError: Node add_a_a: add([a,a]) -> [twice_a] expected 2 input(s) ['a', 'a'], but got the following 1 input(s) instead: ['a'].

## Possible fix

In `node.Node._run_with_list` there is the following check that seems to be too strict:
https://github.com/quantumblacklabs/kedro/blob/2bafa6f032d88f0ce7e2cb004da419a4762e2f49/kedro/pipeline/node.py#L432
If changed to just `if not all_available: ...` then the code above works successfully, but I have not tested whether this causes problems elsewhere. 

## Your Environment

* Kedro version used (`pip show kedro` or `kedro -V`): 0.15.1
* Python version used (`python -V`): Python 3.6.9 :: Anaconda, Inc.
* Operating system and version: macOS Mojave

**Comment by lorenabalan** [comment]
Hi @simon-b thanks for raising this issue - it's been on our backlog to investigate so I suspect we'll move it up on our priority list. Updated with the relevant internal ticket number to make it easier to track.

**Comment by lorenabalan** [comment]
Closing this as resolved in commit https://github.com/quantumblacklabs/kedro/commit/8f076cf9ba48edadde1227893b313d6bc6f0fa18
Thanks again for raising this!
