### ISSUE TITLE
How do I call columns from tables inside each function?

### ISSUE THREAD

**Issue by sofiacosta29** [quantumblacklabs/kedro#160]
Hello! I'm sorry, I had already opened another issue related to this theme, but I noticed that my problem wasn't in the data catalog but in the way I called the columns. I was putting the name of the columns as the second argument of the pipeline nodes, along with dataset names, in a list. What I meant to do was to call the column names in the nodes in order to use those columns as arguments of the functions (called in the pipeline as nodes). For example:

Def function_a(arg1: pd.DataFrame, arg2: list) -> pd.DataFrame:
...

This is the function that I have in the nodes.py file. Calling it as a node in pipeline.py, I have:

def create_pipeline(**kwargs) -> Dict[str, Pipeline]:
"""
...
"""
test_pipeline = Pipeline(
  [
     node(function_a, 'dataset1', "output1", name='output1'),
...
  ]
)

And I was inserting

['dataset1', 'column1']

In the 'dataset1' place. How should I insert the column names so that these are considered as arg2 in function_a, please?

I'm sorry for the mess.

Thank you very much for your attention.

**Comment by Flid** [comment]
Hi @sofiacosta29 
I guess what you are trying to do is to pass some parameters into the node. And there's a mechanism for that, you can specify the columns list in parameters.yaml, and then define the node as
```python
node(function_a, ["arg1", "params:columns_list"], "output1"),
```
The value of the `columns_list` parameter would be passed to the function as the second argument.
Hope that helps.

By the way, we are trying to grow our StackOverflow community (https://stackoverflow.com/questions/tagged/kedro), which is a better place for questions like that. It would be great if next time you can raise a question there.

**Comment by sofiacosta29** [comment]
Thank you very much, I will try that approach.

Noted, next time I will use StackOverflow.

**Comment by DmitriiDeriabinQB** [comment]
Closing as resolved
