### ISSUE TITLE
[KED-1224] Connect Parameters and the Data Catalog

### ISSUE THREAD

**Issue by dasturge** [quantumblacklabs/kedro#163]
## Description

I have a list of annotation names that I'd like to be able to pass in to a DataSet constructor, as well as to particular pipeline nodes.  There could easily be other cases where a node might need to know what parameter(s) a dataset was loaded with.  You can always just duplicate the list in both yaml files, but it's more ideal to have the parameter specified in only one place, especially it's some parameter you can play around with.

For a more motivating use case, consider an mp4_file dataset where I have a frame rate I'd like to load the dataset with.  So `frame_rate` is one of the dataset's arguments, and nodes might need to access the `frame_rate`.

## Possible Implementations

1. Is it possible to use parameters in the same manner as the credentials.yml file within the catalog.yml file?  
e.g.,
```
my_dataset.mp4:
  filepath: /some/path.mp4
  parameters: frame_rate
  ...
```
This would certainly get around the issue, and you can just inject the frame_rate parameter into the catalog entry by name.

2. Some extra pipeline node syntax like has been used for parameters, a la:  `"my_dataset.mp4:frame_rate"` to connect the frame_rate parameter of a catalog entry `my_dataset.mp4` to a node.

3.  The answer I don't want is that 'you could just return a dict of metadata with your loaded dataset object'.  It's not too pretty and I don't want to write every node to accept dictionary objects or tuples, making it awkward to treat them as functions later on.

edit: formatting

**Comment by DmitriiDeriabinQB** [comment]
@dasturge Thank you for your feedback.

Re 1: This use case is supported by [TemplatedConfigLoader](https://kedro.readthedocs.io/en/latest/kedro.contrib.config.templated_config.TemplatedConfigLoader.html) - it allows you to parameterise your configuration using some 'global' configuration. Can be applied to `catalog.yml` or any other config.

Re 2: I've created a ticket for the internal discussion. We will get back to you once we have an update.

**Comment by DmitriiDeriabinQB** [comment]
@dasturge regarding the second point, our suggestion would be to: 
1. specify the `frame_rate` in the parameters
2. feed the frame rate into the dataset definition by templating the catalog via `TemplatedConfigLoader`
3. pass the frame rate into the node as: `node(my_func, inputs=["my_dataset.mp4", "params:frame_rate"])`

**Comment by DmitriiDeriabinQB** [comment]
Please let us know whether this satisfies your use case

**Comment by markf94** [comment]
For all future readers, here's the updated link to the [TemplatedConfigLoader](https://kedro.readthedocs.io/en/stable/kedro.contrib.config.templated_config.TemplatedConfigLoader.html)

**Comment by WaylonWalker** [comment]
The updated link was broken again, here is one that worked for me today. 😃 [TemplatedConfigLoader](https://kedro.readthedocs.io/en/stable/kedro.config.TemplatedConfigLoader.html)

**Comment by DmitriiDeriabinQB** [comment]
I'm closing this issue. The suggested solution would be to utilise `TemplatedConfigLoader` as described [above](https://github.com/quantumblacklabs/kedro/issues/163#issuecomment-589775863).
