### ISSUE TITLE
Node dependencies

### ISSUE THREAD

**Issue by bayees** [quantumblacklabs/kedro#164]
## Description
I have issues with node dependencies when working with databases. One of my nodes extracts data into a database and another node is dependent on part of the data, so instead of loading the full table I have made a select statement with only the columns I need. Dependencies can currently only be linked by using the same output and input dataset. I am aware that I can create a dummy dataset to fake a dependencies, but that make messy code in both funcitons and nodes.

## Context
Why is this change important to you? How would you use it? How can it benefit other users?
The code will be cleaner and more explicit instead of the dummy dataset.

**Comment by tolomea** [comment]
You can use transcoding to save with one dataset and load with another. https://kedro.readthedocs.io/en/latest/04_user_guide/04_data_catalog.html#transcoding-datasets

**Comment by DmitriiDeriabinQB** [comment]
@bayees By the way, we are trying to grow our [StackOverflow community](https://stackoverflow.com/questions/tagged/kedro), which is a better place for questions like that. It would be great if next time you can raise a question there, thank you.

**Comment by DmitriiDeriabinQB** [comment]
Closing as resolved

**Comment by freebiesoft** [comment]
the transcoding page no longer exists
