### ISSUE TITLE
Failed to run joblib in kedro

### ISSUE THREAD

**Issue by Sirorezka** [quantumblacklabs/kedro#165]
## Description
Code fails if running joblib parallelization in Kedro jupyter notebooks. To reproduce the error:
1. run kedro jupyter notebook 
2. create function which uses joblib in 'src' folder
3. Run this function from jupyter

Script fails with error: "ModuleNotFoundError: No module named 'src'"

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

Kedro version 0.14.2
Python version 3.6.9
OS: macOS Mojave 10.14.5

**Comment by Sirorezka** [comment]
src/sample_proj/sample_joblib.py

```
from joblib import delayed, Parallel
import multiprocessing

def to_pow(x, pow = 2):
    return x**pow

def sample_joblib():

    cnt_cpus = multiprocessing.cpu_count()
    lst_vals = [1,2,3,4,5,6,7,8]
    res = Parallel(n_jobs=cnt_cpus)(delayed(to_pow)(i) for i in lst_vals)
```


kedro jupyter notebook:
```
import src.sample_proj.sample_joblib as smpl
from importlib import reload

reload(smpl)
smpl.sample_joblib()
```

**Comment by DmitriiDeriabinQB** [comment]
@Sirorezka thank you for the feedback. 

The `src` prefix in your example is causing an issue. Generally speaking, `src` is not a Python package and is not intended to be "importable", so it shouldn't be included in the import path. Instead, you should make sure that the path to `src` folder is included into `sys.path` for the imports to work.

Kedro does that automatically when loading the project, so if you ran `kedro jupyter notebook` then `import sample_proj.sample_joblib as smpl` and subsequent `smpl.sample_joblib()` work just fine. If you ran vanilla Jupyter (`jupyter-notebook`) then you'd have to `sys.path.append(<absolute-path-to-src>)` yourself.

**Comment by DmitriiDeriabinQB** [comment]
Closing as resolved
