### ISSUE TITLE
Log node run times

### ISSUE THREAD

**Issue by pwerth** [quantumblacklabs/kedro#167]
## Description
Log the run times for each node.

## Context
I am always curious to know if there are any bottlenecks in my pipelines, and where they occur. It is easy to log run times for functions within nodes, but it would be nice if the Kedro logger provided this information automatically. This holds not only for node logic, but for I/O as well (e.g. how long it takes to read or write certain CSVs).

## Possible Implementation
Could be optional with a config variable, or something that always occurs. Run time would be logged after a node is done running. Could have two levels of logging - one for I/O and one for node logic.

**Comment by tsanikgr** [comment]
Hello @pwerth 

How about using node decorators to do so?
Have a look here:

https://kedro.readthedocs.io/en/latest/04_user_guide/05_nodes.html#applying-decorators-to-nodes
https://kedro.readthedocs.io/en/latest/kedro.pipeline.decorators.log_time.html

**Comment by tsanikgr** [comment]
For logging the time it takes to load/save data, you can use dataset transformers:

https://kedro.readthedocs.io/en/latest/04_user_guide/04_data_catalog.html#transforming-datasets
https://kedro.readthedocs.io/en/latest/kedro.contrib.io.transformers.ProfileTimeTransformer.html

**Comment by pwerth** [comment]
@tsanikgr Thank you for your quick reply. Both of those solve my problem. Is this something you would consider automating, perhaps with a config variable? This would be a bit easier to use than having to add the decorator manually to every node.

**Comment by tsanikgr** [comment]
You can always apply the decorator to all nodes: `pipeline.decorate(...)` :)
https://kedro.readthedocs.io/en/latest/kedro.pipeline.Pipeline.html#kedro.pipeline.Pipeline.decorate

**Comment by pwerth** [comment]
Ah, great. Thanks!

**Comment by tsanikgr** [comment]
If this resolves your issue, please consider closing the issue. Thanks!
