### ISSUE TITLE
Kedro viz

### ISSUE THREAD

**Issue by talk21991** [quantumblacklabs/kedro#168]
When I was running `kedro viz` in my command prompt I got following error.

`NameError: name 'node' is not defined`

How to deal with this issue?

**Comment by tolomea** [comment]
could you please run 'kedro info' and paste the output here

**Comment by tolomea** [comment]
Also the full output of running `kedro viz`

**Comment by lorenabalan** [comment]
Hi @talk21991 , in order to debug this we need more information. Could you please follow the steps mentioned above by @tolomea ?

**Comment by talk21991** [comment]
Hi,

Sorry for the late reply. I able to understand my fault to define pipeline.

Actually I was skipping calling node( from kedro.node import nodename) in
my code when I am defining Pipeline. Now kedro viz is working. Thank.

**Comment by mzjp2** [comment]
> Hi, Sorry for the late reply. I able to understand my fault to define pipeline. Actually I was skipping calling node( from kedro.node import nodename) in my code when I am defining Pipeline. Now kedro viz is working. Thank.
> […](#)

If the issue is resolved, you might consider closing the issue 🙂

**Comment by lorenabalan** [comment]
Thanks @talk21991 , glad to hear it's working! I'll go ahead and close this issue.

**Comment by talk21991** [comment]
Hi,

Many thanks.

With regards
Arpan
