### ISSUE TITLE
Smart quotes in the legal disclaimers

### ISSUE THREAD

**Issue by wdearden** [quantumblacklabs/kedro#17]
## Description
There are smart quotes at several spots in the legal disclaimers. Here is one example but all examples can be found by searching the repo:
https://github.com/quantumblacklabs/kedro/blob/d3218bd89ce8d1148b1f79dfe589065f47037be6/kedro/template/%7B%7B%20cookiecutter.repo_name%20%7D%7D/src/%7B%7B%20cookiecutter.python_package%20%7D%7D/__init__.py#L17

## Context
I discovered this while building the Sphinx docs for the Hello World example and getting a "Non-ASCII character" error.

**Comment by yetudada** [comment]
Thanks for raising this @wdearden! We're going to look into this one for you. We'll work on reproducing the error.

**Comment by yetudada** [comment]
We've managed to resolve this issue in the latest release of Kedro. Check out Kedro 0.14.3, this [PR](https://github.com/quantumblacklabs/kedro/commit/c30f2da6f268fb445a075783cf647d4b45cf075b) and let us know your thoughts. Thank you once again for raising this bug @wdearden! 🚀
