### ISSUE TITLE
pipeline deselection

### ISSUE THREAD

**Issue by WaylonWalker** [quantumblacklabs/kedro#170]
## Description
Pipeline filtering methods `only_nodes`, `only_nodes_with_tags`, `only_nodes_with_inputs`, `only_nodes_with_outputs` are great for **selecting** nodes, and sections of pipelines.  Sometimes I want to avoid parts of the pipeline.  

## Context
This section/node may be slow, incur network cost, or may effect the work of a colleague.  It would be great to have some easy ways to deselecting part of the pipeline, without a bunch of for loops or list comprehensions.

## Possible Implementation

The most simple would be to implement a `__sub__` method to the pipeline.  Then users can utilize pipeline selectors to trim off sections of the pipeline.

## Possible Alternatives

* implement each of the `only_nodes_with_...` methods as an inverse `only_nodes_without...`
* allow negation in the `only_nodes_with_...` methods using '~'

**Comment by tolomea** [comment]
Given it already has add sub makes sense, feel free to make a pull request for that

**Comment by WaylonWalker** [comment]
Created PR #175 for adding `__sub__`.  I still feel that it would be really nice to have the opposite of each `only_nodes...` method.  `__sub__`  at least avoids writing a full list comprehension or for loop to slice pipelines in this way.

**Comment by lorenabalan** [comment]
Closing as resolved in https://github.com/quantumblacklabs/kedro/commit/2a08d8625be598364942e6cf2b7df518bc165f7e
