### ISSUE TITLE
[KED-1271] Tensorflow Model Dataset

### ISSUE THREAD

**Issue by williamashfordQB** [quantumblacklabs/kedro#176]
## Description
In order to prevent pickling errors with Tensorflow models, it would be great to include a tensorflow dataset which would invoke the APIs preferred save and load methods. 

## Context
Saving and loading tensorflow models via pickling can result in errors. It is possible to write a new dataset which invokes the APIs preferred save and load methods and prevents pickling errors. 

## Possible Implementation
I've been using this in my work. I haven't tried the `exists` functionality (I assume this won't work), however for regular pipeline operation, it works well. 

```
from kedro.io import AbstractDataSet
import tensorflow as tf
from typing import Dict, Any


class TensorflowModelDataset(AbstractDataSet):

    def __init__(self, filepath: str, load_args: Dict[str, Any] = None, save_args: Dict[str, Any] = None):
        """
        A dataset to save and load tensorflow models.

        Args:
            data: The tensorflow model to save.

        """

        self.filepath = filepath

        self._load_args = dict(custom_objects=None,
                               compile=True)

        self._save_args = dict(overwrite=True,
                               include_optimizer=True,
                               save_format='tf',
                               signatures=None,
                               options=None)

        if load_args is not None:
            self._load_args.update(load_args)

        if save_args is not None:
            self._save_args.update(save_args)

    def _load(self):
        return tf.keras.models.load_model(
            self.filepath,
            **self._load_args
        )

    def _save(self, data):
        tf.keras.models.save_model(
            data,
            self.filepath,
            **self._save_args
        )

    def _exists(self):
        return True if self.data is not None else False

    def _describe(self):
        return None
```

**Comment by lorenabalan** [comment]
Hi @williamashfordQB thanks for raising this. Would you be able to package this up as a PR? Out of interest, could you shed a bit more light around the root causes of the mentioned pickling problems?

**Comment by yetudada** [comment]
@williamashfordQB Is this #123 related to this issue? But otherwise please proceed with a PR on this 🚀

**Comment by williamashfordQB** [comment]
Yes this is the error! Yep I'll be sure to :)

**Comment by yetudada** [comment]
> Yes this is the error! Yep I'll be sure to :)

Awesome 😎 Let us know if you need any help and thank you so much for picking this up!

**Comment by w0rdsm1th** [comment]
FYI both, I am going to take a look at this as part of today's pysprint. basically transplanting @williamashfordQB's code and adding test cases

**Comment by williamashfordQB** [comment]
Cheers and enjoy!!

**Comment by andrii-ivaniuk** [comment]
The new dataset was added in 75e7fb6678b6fdc73ad088ade20666016ecd5a85 commit.

**Comment by joel-thomas-wilson** [comment]
This still breaks if you have a sklearn Pipeline wrapper around your tf model object.

`
`2022-01-29 15:04:47,941 - kedro.io.data_catalog - INFO - Saving data to `train_ann.ts_model` (TensorFlowModelDataset)...
Traceback (most recent call last):
  File "c:\users\python3\envs\gem_dl\lib\site-packages\kedro\io\core.py", line 240, in save
    self._save(data)
  File "C:\Users\Documents\PROJECTS\trainings\NeuralNetworks\git_repo\gem_dl\gem_dl\src\gem_dl\helper\tag_management\tf_io.py", line 157, in _save
    tf.keras.models.save_model(data, path, **self._save_args)
  File "c:\users\python3\envs\gem_dl\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "c:\users\python3\envs\gem_dl\lib\site-packages\keras\saving\saving_utils.py", line 308, in try_build_compiled_arguments
    model.outputs is not None):
AttributeError: 'Pipeline' object has no attribute 'outputs
`
tf.model object is : "<class 'sklearn.pipeline.Pipeline'>"

**Comment by willashford** [comment]
If you check the function signature of the save method, it expects a tf model class, not a sklearn pipeline.

If you want to save an object that isn’t covered by an existing dataset class, you’ll need to create a new dataset class. This is a good guide for this https://kedro.readthedocs.io/en/stable/07_extend_kedro/03_custom_datasets.html

**Comment by joel-thomas-wilson** [comment]
@willashford  - any ideas on how i can build one for a `<class 'sklearn.pipeline.Pipeline'>` 

It looks like this:
```
Pipeline(steps=[('select_columns',
                 SelectColumns(items=['f1', 'f2',
                                      'f3',])),
                ('standard_scaler',
                 SklearnTransform(transformer=StandardScaler())),
                ('estimator',
                 <keras.wrappers.scikit_learn.KerasRegressor object at 0x00000220353E0550>)])
```
