### ISSUE TITLE
[KED-1257] shellvars support

### ISSUE THREAD

**Issue by shirouto** [quantumblacklabs/kedro#179]
## Description
The documentation states that kedro supports ```shellvars``` config format through the ```.shellvars``` file extension, but that does not seem to work because ```anyconfig``` integration requires specifying the parser specifically: ```anyconfig``` will not pick up the parser automatically based on file extension. See 
[#47 on anyconfig](https://github.com/ssato/python-anyconfig/issues/47#issuecomment-269892372). The argument provided herein seems reasonable.

## Context
There are multiple workarounds available, so it does not have a significant impact.

A few options I see here:

* Strip the ```shellvars``` support all together. Even ```anyconfig``` does not seem to treat it as a priority. There are already a lot of configuration formats available and otherwise ```TemplatedConfigLoader``` can handle fancier cases.

* Standardize the file extension and pass in the ```ac_parser="shellvars"``` in the ```anyconfig.load``` call in ```kedro/config/config.py:231``` when the extension matches.

* Update the documentation to let users know they need to extend ```kedro.config.ConfigLoader``` if they need to use the ```shellvars``` format. 

If you need a PR, let me know: I have been pilfering some in your code lately.

**Comment by lorenabalan** [comment]
Hi @shirouto that's an excellent point, well-spotted!  My first instinct would be to go for fixing line 231 in `config.py`, I'll confirm with the team. We very much welcome PRs!
I've updated the issue with our internal ticket number to make it easier to track, if you do decide to open a PR please reference the same number in the title. :)

**Comment by lorenabalan** [comment]
Hey @shirouto I just realised we never got back to you on this, apologies! We decided to actually go with your first suggestion. This has been resolved [here](https://github.com/quantumblacklabs/kedro/commit/fbf4e751947b0500cbf1f7e892ba88b5ea3ef460).
I'm gonna go ahead and close this issue, but feel free to raise any others we come across, and any PRs you are keen on getting feedback on! :)
