### ISSUE TITLE
[KED-1274] Kedro Jupyter Notebook Issue- context not loading / %reload_kedro throws error 

### ISSUE THREAD

**Issue by selfishhari** [quantumblacklabs/kedro#184]
## Description
Upon starting kedro jupyter notebook, and running %reload_kedro. I get the below error.

 - root - ERROR - Kedro's ipython session startup script failed: Could not retrive 'context_path' from '.kedro.yml' in /path/to/project/notebooks. If you have created your project with Kedro version <0.15.0, make sure to update your project template. See https://github.com/quantumblacklabs/kedro/blob/master/RELEASE.md for how to migrate your Kedro project.

context is also not loaded into the notebook. 

I am using kedro 0.15.1 itself.

## Context
I cannot read in the datasets/config parameters etc. into notebooks as context is also not loaded. Command line still works fine.

It's a bit weird as it used to work fine for a long time, untill it didn't. I did not update/even install any new packages. Infact when I faced this issue for the first time, one of  my notebooks was running fine but when i opened a new one i started getting this issue.

## Steps to Reproduce
I am not sure how this could be done, but:
1. kedro jupyter notebook
2. Open a notebook and run %reload_kedro. Or try running context. (context is not loaded)

```
FileNotFoundError                         Traceback (most recent call last)
~/anaconda3/envs/myenv/lib/python3.6/site-packages/kedro/context/context.py in load_context(project_path, **kwargs)
    397     try:
--> 398         with kedro_yaml.open("r") as kedro_yml:
    399 

~/anaconda3/envs/myenv/lib/python3.6/pathlib.py in open(self, mode, buffering, encoding, errors, newline)
   1182         return io.open(str(self), mode, buffering, encoding, errors, newline,
-> 1183                        opener=self._opener)
   1184 

~/anaconda3/envs/myenv/lib/python3.6/pathlib.py in _opener(self, name, flags, mode)
   1036         # A stub for the opener argument to built-in open()
-> 1037         return self._accessor.open(self, flags, mode)
   1038 

~/anaconda3/envs/myenv/lib/python3.6/pathlib.py in wrapped(pathobj, *args)
    386         def wrapped(pathobj, *args):
--> 387             return strfunc(str(pathobj), *args)
    388         return staticmethod(wrapped)

FileNotFoundError: [Errno 2] No such file or directory: '/home/path/to/repository/project_dir/notebooks/.kedro.yml'

During handling of the above exception, another exception occurred:

KedroContextError                         Traceback (most recent call last)
<ipython-input-1-4924b8705645> in <module>
      2 from datetime import datetime
      3 notebook_start = time.time()
----> 4 get_ipython().run_line_magic('reload_kedro', '')

~/anaconda3/envs/myenv/lib/python3.6/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2312                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2313             with self.builtin_trap:
-> 2314                 result = fn(*args, **kwargs)
   2315             return result
   2316 

~/path/to/repository/project_dir/.ipython/profile_default/startup/00-kedro-init.py in reload_kedro(project_path, line)
     28         startup_error = err
     29         logging.error("Kedro's ipython session startup script failed:\n%s", str(err))
---> 30         raise err
     31 
     32 

~/path/to/repository/project_dir/.ipython/profile_default/startup/00-kedro-init.py in reload_kedro(project_path, line)
     14         from kedro.context import load_context
     15 
---> 16         context = load_context(project_path)
     17 
     18         logging.info("** Kedro project {}".format(context.project_name))

~/anaconda3/envs/myenv/lib/python3.6/site-packages/kedro/context/context.py in load_context(project_path, **kwargs)
    404             "your project with Kedro version <0.15.0, make sure to update your project template. "
    405             "See https://github.com/quantumblacklabs/kedro/blob/master/RELEASE.md "
--> 406             "for how to migrate your Kedro project.".format(str(project_path))
    407         )
    408 

KedroContextError: Could not retrive 'context_path' from '.kedro.yml' in /home/path/to/repository/project_dir/notebooks. If you have created your project with Kedro version <0.15.0, make sure to update your project template. See https://github.com/quantumblacklabs/kedro/blob/master/RELEASE.md for how to migrate your Kedro project.
```

```
-- Separate them if you have more than one.
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): kedro, version 0.15.1
* Python version used (`python -V`): Python 3.6.9 :: Anaconda, Inc.
* Operating system and version: Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.6 LTS
Release:	14.04
Codename:	trusty

ipython version: 7.9.0

jupyter notebook --version: 6.0.1

**Comment by selfishhari** [comment]
I tried to reinstall in an entirely new conda environment(And then git cloning my repo). Same issue.

However,tried a fresh kedro project from scratch is not having this issue.

Didn't understand why it is trying to look for .kedro.yml in notebooks folder. It is present in the parent project folder.

**Comment by selfishhari** [comment]
I figured this out.

Apparently, i had imported a node module wrongly in another one of my nodes. When kedro starts jupyter apparently this wrong import was preventing startup files to load context properly.

To understand this error, we must run `kedro ipython` in terminal. That will print the error from our modules. Fix that and everything will be fine.

The whole issue was because kedro jupyter notebook doesn't print startup errors properly. Or is there something i havent understood??

[(https://github.com/ipython/ipython/issues/10068#issuecomment-263692621)]

**Comment by yetudada** [comment]
Thanks for raising this @selfishhari. I'm glad you managed to figure out the error in the end. 

At first glance, I thought your issue was related to a bug we addressed in [`kedro 0.15.4`](https://github.com/quantumblacklabs/kedro/blob/master/RELEASE.md#bug-fixes-and-other-changes) which would result in the IPython script trying to load context from the wrong location. But you may be right that it's related to how errors are reported on Jupyter notebooks. 

I'll add this to the backlog to see how we can assist on error reporting.

**Comment by selfishhari** [comment]
Thank you.

This error can now be reproduced easily from the startup template that you provide with example.py node.

1. Open example.py node and add a import something that doesn't exist.
`"""Example code for the nodes in the example pipeline. This code is meant
just for illustrating basic Kedro features.

PLEASE DELETE THIS FILE ONCE YOU START WORKING ON YOUR OWN PROJECT!
"""
# pylint: disable=invalid-name

import logging
from typing import Any, Dict

import numpy as np
import pandas as pd
import THIS_MODULE_DOESNT_EXIST_ANYWHERE`

2. run `kedro jupyter notebook` from project folder.

3. Create a new notebook and run `%reload_kedro`. You get the error i was talking about, but nothing about missing module.

4. Now go back to your terminal and execute `kedro ipython`. There you see error about the missing module.

Hope it helps

**Comment by ZainPatelQB** [comment]
What happens when you run `startup_error` in a jupyter notebook in that scenario?

**Comment by selfishhari** [comment]
> What happens when you run `startup_error` in a jupyter notebook in that scenario?

Same as :

> root - ERROR - Kedro's ipython session startup script failed: Could not retrive 'context_path' from '.kedro.yml' in /path/to/project/notebooks. If you have created your project with Kedro version <0.15.0, make sure to update your project template. See https://github.com/quantumblacklabs/kedro/blob/master/RELEASE.md for how to migrate your Kedro project.

But this is after i run `%reload_kedro` once. Before running `%reload_kedro`, `startup_error` gives nothing

**Comment by lorenabalan** [comment]
Hi @selfishhari , this is fixed in more recent versions of Kedro (I've tried reproducing this with 0.15.5 as well and works better). My best guess, off the top of my head, is that it has to do with this line in the 0.15.4 release notes:
`* Fixed a bug in IPython startup script, attempting to load context from the incorrect location.`
The best solution be to upgrade your kedro project to a newer kedro version. Otherwise you can try copying the contents over from the new [startup script](https://github.com/quantumblacklabs/kedro/blob/develop/kedro/template/%7B%7B%20cookiecutter.repo_name%20%7D%7D/.ipython/profile_default/startup/00-kedro-init.py).

**Comment by lorenabalan** [comment]
Closing this as resolved, please feel free to open a new one if you come up against other problems.

**Comment by abhishekh-cpnet** [comment]
@ZainPatelQB  @yetudada  Hi! Guys. 
I am having problem with launching the jupyter notebook from my current repository with the following a command 

> kedro jupyter notebook 

i get the following error:
kedro.framework.cli.utils.KedroCliError: Cannot load commands from /home/abhishekh/kedro-environment/spb-proto/kedro_cli.py

Kedro version: 0.16.3

![kedro_cli](https://user-images.githubusercontent.com/65624095/87482565-af80af00-c5ff-11ea-842d-a4a2a22f8ac1.png)

**Comment by mzjp2** [comment]
@abhishekh-cpnet I presume this is running a Kedro project that was generated using an older version of Kedro? If so, Kedro 0.16 is a breaking change and old projects will need some manual upgrades to run with the newer version of Kedro. You have two options:

1. do `kedro new` and manually port over code aka regenerate a new project
2. Follow the [migration guide](https://github.com/quantumblacklabs/kedro/blob/master/RELEASE.md#migration-guide-from-kedro-015-to-016) here. Specifically the portion of [modifying your kedro cli file](https://github.com/quantumblacklabs/kedro/blob/master/RELEASE.md#migration-for-cli-and-kedro_env-environment-variable)

Let me know if that helps!

**Comment by abhishekh-cpnet** [comment]
Thanks.  It did solve the jupyter notebook error. However, while running the 'reload_kedro'  command I get the following error: 

Your Kedro project version 0.15.9 does not match Kedro package version 0.16.3 you are running. Make sure to update your project template. See https://github.com/quantumblacklabs/kedro/blob/master/RELEASE.md for how to migrate your Kedro project. 

I have made the changes mentioned in the release.md but I still get the error.

**Comment by mzjp2** [comment]
You need to update the project version attribute in your `ProjectContext` class in `src/<proj>/run.py` from 0.15.9 to 0.16 after making the changes.
