### ISSUE TITLE
kedro is not compatable with python=3.8

### ISSUE THREAD

**Issue by WaylonWalker** [quantumblacklabs/kedro#185]
## Description
_kedro needs more walrus :=_

When `pip install kedro` in an environment using `pytho=3.8` it installs `kedro=0.0.1` and tells me that `0.15.5` is not compatable.

I am mostly curious if there is a reason other than the way that it is tagged on pypi.

## Context

I would like to use the latest version of python.  I have no intense need for the newest features.  It also results in confusion when kedro does not install correctly with the latest version.

## Steps to Reproduce
``` bash
conda create -n python38 python=3.8
```

## Expected Result

pip should install the latest version.

## Actual Result
pip installed `kedro==0.0.1`

**Comment by lorenabalan** [comment]
Hi @WaylonWalker , no version of kedro supports python 3.8 yet (see [this line](https://github.com/quantumblacklabs/kedro/blob/613a297e3564e38593d3c409d9d588ef27759073/setup.py#L82)). Please see https://github.com/quantumblacklabs/kedro/issues/124 as this is where we're tracking progress on this topic.

**Comment by WaylonWalker** [comment]
Thanks @lorenabalan  I should have searched a bit harder 😊
