### ISSUE TITLE
Kedro Tutorial ImportError

### ISSUE THREAD

**Issue by BalazsKonigQB** [quantumblacklabs/kedro#196]
## Description/Context
A step fails with ImportError in the Spaceflights tutorial of the Kedro tutorials.

## Steps to Reproduce
1. Kedro Tutorials
2. > Setting Up Data
3. >> Reference All Datasets
4. >>> "open a kedro ipython session and run"
(https://kedro.readthedocs.io/en/latest/03_tutorial/03_set_up_data.html)

## Expected Result
The built-in Kedro library code should run, so that I can check out one of the .csv datafiles within that session.

## Actual Result
The run session fails with ImportError. This is because in pipeline.py, line 33-34, the code tries to import data_engineering and data_science from kedro_tutorial.pipelines, but at this point of the tutorial those don't exist. (They would exist if one chose to include the dummy data when creating the Kedro project, but in this tutorial that isn't the case.)

I checked the previous commits - in the last one (**[KED-1128] Add kedro lint with isort, flake8 and black (#334)**) these two import lines were moved out of an if-statement (that was only importing these if the dummy data was chosen to be included).

```
File "/Users/balazs_konig/kedro-tutorial/src/kedro_tutorial/pipeline.py", line 33, in <module>
    from kedro_tutorial.pipelines import data_engineering as de
ImportError: cannot import name 'data_engineering'
```

## Your Environment
* Kedro version used (`pip show kedro` or `kedro -V`): 0.15.5
* Python version used (`python -V`): 3.6.10
* Operating system and version: MacOS Catalina

**Comment by 921kiyo** [comment]
Hi @BalazsKonigQB 
Thank you for reporting the bug. We will put the import back to inside the Jinja if-statement.

**Comment by ebalp** [comment]
Hello, 
Thanks for solving this issue so fast.
I am actually having the same problem with 
`kedro new`
`kedro install`
`kedro ipython`

I see in this thread that the bug is now fixed in the branch develop. Even though I _pip install --upgrade kedro_ , this doesn't seem to work. How can I make it work?

**Comment by 921kiyo** [comment]
`pip install --upgrade kedro` will install Kedro from master branch, not develop branch. The easiest way to fix on your side is manually delete the two lines that were changed in https://github.com/quantumblacklabs/kedro/pull/197. 

Please let us know if you have any questions :)

**Comment by 921kiyo** [comment]
I am closing this issue as it is fixed in https://github.com/quantumblacklabs/kedro/pull/197
