### ISSUE TITLE
[KED-1349] DOCS - How to Upgrade Kedro

### ISSUE THREAD

**Issue by WaylonWalker** [quantumblacklabs/kedro#198]
Link to page: https://kedro.readthedocs.io/en/latest/06_resources/01_faq.html#how-do-i-upgrade-kedro

## Description

How to upgrade should include instructions to upgrade the `project_version` inside of the ProjectContext.

**Comment by lorenabalan** [comment]
Thanks Waylon! :) We'll add update the docs to reflect a bit more detail than it does currently.

**Comment by lorenabalan** [comment]
Closing this as resolved in https://github.com/quantumblacklabs/kedro/commit/417847f2cbabbb5dea3a7af87c6eeb850a20cad5

**Comment by WaylonWalker** [comment]
Perfect, Thanks for fixing!
