### ISSUE TITLE
Using hierachical parameter/catalog files in configurations

### ISSUE THREAD

**Issue by khdlim** [quantumblacklabs/kedro#206]
## Description

Disclaimer: I guess this is not really a feature request since most of the functionality seems to exist in the existing library - just wondering why it is not the default right now for templated projects.

I would like to define parameters gradually in a hierachical manner in the ``conf/`` directory.

For example, I could have a dataset ``MyDataSet`` for which I could use both of ``Model1`` and ``Model2`` with diferent experiment settings ``Experiment1``, ``Experiment2`` etc. for each.

Ideally, I would like to define the data catalog in in ``./conf/mydataset/catalog.yml``, since it doesn’t change with the model/experimental settings, provide some fixed options (e.g. the model class name and some fixed hyperparameters, this can vary during the project) for ``Model1`` in ``./conf/mydataset/model1/parameters.yml`` and then experiment-specific parameters in ``./conf/mydataset/model1/experiment1/parameters.yml``.

Then, when I specify ``env`` as ``./conf/mydataset/model1/experiment1/``, the parameters and data catalog should be propagated from the root directory ``./conf/mydataset`` all the way to the final ``env`` directory. 

It seems that the ``ConfigLoader`` actually has been built with this functionality that I am looking for.

https://github.com/quantumblacklabs/kedro/blob/2a71b784fc2940934363b38f3befb2bd52bffda5/kedro/config/config.py#L56-L87

However, for some reason it is not currently being used because in ``KedroContext`` only the final ``env`` directory is being added to ``conf_paths`` along with ``base``. 

https://github.com/quantumblacklabs/kedro/blob/2a71b784fc2940934363b38f3befb2bd52bffda5/kedro/context/context.py#L295-L306

I am wondering if this is by design or not?

## Context
It is important because each ``env`` directory needs a ``catalog.yml`` and ``parameters.yml`` of its own right now - the only other ``env`` they inherit from is ``conf/base``. Hence if I have two experimental runs which use the same data and keep 8 out of 10 parameters the same, I have to replicate all configs and if I make any changes to the data catalog it needs to be duplicated manually across each ``env`` directory that uses the same dataset, which is likely to cause errors (this happened to me a lot even pre-Kedro). I believe there should be a lot of users who experience the same issues.

## Possible Implementation
I think to get the functionality I want, we just have to add all intermediate directories, i.e. ``./conf/mydataset``, ``./conf/mydataset/model1``, ``./conf/mydataset/model1/experiment1`` to ``conf_paths``.

Currently, I have attempted a quick prototype overloading ``get_config_loader`` in  ``ProjectContext`` below to do this in Ubuntu and it seems to work as intended for now (I am not an expert on filesystem paths but I imagine it would need modifications for Windows and other error checking/edge cases).

```python
    def _get_config_loader(self):
        """A hook for changing the creation of a ConfigLoader instance.

        Returns:
            Instance of `ConfigLoader` created by `_create_config_loader()`.

        """
        intermediate_dirs = self.env.split('/')
        intermediate_paths = ['/'.join(intermediate_dirs[:i+1])
                           for i, _ in enumerate(intermediate_dirs)]

        conf_paths = (
            [str(self.project_path / self.CONF_ROOT / "base")] +
            [str(self.project_path / self.CONF_ROOT / ip) for ip in intermediate_paths]
        )
```
So far, it seems to do what I want, including logging an INFO message when top-level parameters are changed by ``parameter.yml`` files further in the directory structure.

**Comment by 921kiyo** [comment]
For duplicate parameters, you can use `TemplatedConfigLoader` (see https://kedro.readthedocs.io/en/latest/kedro.contrib.config.templated_config.TemplatedConfigLoader.html?#kedro.contrib.config.templated_config.TemplatedConfigLoader). But it is for overloading `create_config_loader`, not the `conf_paths` as you suggested. You could have all common parameters in `globals.yml` like in the doc example, which might simplify your situations a bit.

**Comment by khdlim** [comment]
@921kiyo Thanks, I did not know this feature existed, will look into it!
