### ISSUE TITLE
No matching distribution for kedro

### ISSUE THREAD

**Issue by nraw** [quantumblacklabs/kedro#209]
## Description
Can't install Kedro inside of the basic python docker container

## Context
How has this bug affected you? What were you trying to accomplish?

## Steps to Reproduce
1. docker run -it --rm --name test python:3.8-buster /bin/bash
2. pip install kedro

## Expected Result
Kedro gets installed

## Actual Result
Error is raised and installation stops

```
ERROR: Could not find a version that satisfies the requirement kedro (from versions: none)
ERROR: No matching distribution found for kedro
```

## Your Environment
It's a python docker container.

* Kedro version used (`pip show kedro` or `kedro -V`): NA
* Python version used (`python -V`): Python 3.8.1
* Operating system and version: Linux 7b328e6ab0cb 4.19.76-linuxkit #1 SMP Thu Oct 17 19:31:58 UTC 2019 x86_64 GNU/Linux

**Comment by nraw** [comment]
```
python_requires=">=3.5, <3.8"
```
oh, never mind, sorry

**Comment by lorenabalan** [comment]
Hi @nraw , Kedro isn't currently available on Python 3.8, which is why you can't pip install it in your environment. You can track the progress of our 3.8 support [here](https://github.com/quantumblacklabs/kedro/issues/124).

**Comment by cpoptic** [comment]
Over a year later, is Python 3.7 or 3.8 or 3.9 or 3.10 support available yet for Kedro?

**Comment by Harshikerfuffle** [comment]
I am facing the same issue. I brought my python and pip to their respective latest versions [3.9.7 and 21.3.1] and seems that kedro cannot be installed with those yet. Will try rolling back my version of python. Also, I am unable to `pip install kedro`. I had to do `pip3 install kedro`
