### ISSUE TITLE
Can Kedro handle templated queries?

### ISSUE THREAD

**Issue by atercygnus** [quantumblacklabs/kedro#214]
I apologize if this feature is already implemented, but I can't find one.

Need to have SQLQueryDataSet with parameters.
Something like:

```
**catalog.yml:**

foo_dataset:
    type: SQLQueryDataSet
    credentials: foo_cred
    sql:
        select id, ... from foo_table where id in ({%ids})

**notebook or .py file:**

ids_tofetch = [...]
df = context.catalog.load('foo_dataset', {'ids':ids_tofetch})
```

Can this be done for now?

**Comment by atercygnus** [comment]
Hi @yetudada! Thanks for answering!

This is nice, and solves a part of my problem, but is many cases sql queries are too complicated to be a single query, and it's convenient to  fetch parts of the data separately, and then merge them in python. In this case it is essential to have templated queries without using additional file globals.yml.

**Comment by lorenabalan** [comment]
Closing this issue as stale, but please feel free to raise a new one if you encounter other problems. As Yetu noted, `TemplatedConfigLoader` could be helpful here. Otherwise maybe a local customisation for the `SQLDataSet` is the best guess.
