### ISSUE TITLE
Add Great Expectations to Kedro

### ISSUE THREAD

**Issue by JasonLeungQB** [quantumblacklabs/kedro#215]
Incorporate [Great expectation](https://github.com/great-expectations/great_expectations) to Kedro to validate data ingestion.  On many projects, we have to combine current data with previous achieved data, we would like to validate the two sets of data.

**Comment by ZainPatelQB** [comment]
Similar issue here https://github.com/quantumblacklabs/kedro/issues/207

**Comment by JasonLeungQB** [comment]
I will take a stab on incorporating Great expectation to Kedro w/ Deepyaman Datta.
