### ISSUE TITLE
[KED-1371] Confusion around notebooks in Spaceflight Tutorial

### ISSUE THREAD

**Issue by Arcticnode** [quantumblacklabs/kedro#217]
There is some confusion at the point where the spaceflight tutorial starts talking about Jupyter notebooks since they are not introduced.

https://kedro.readthedocs.io/en/latest/03_tutorial/04_create_pipelines.html

Section: "Creating a master table"
We need to add a function to join together the three dataframes into a single master table in a cell in the notebook as follows:

**Comment by ZainPatelQB** [comment]
Hi 👋, thanks for raising this! The start of the guide does mention Jupyter notebooks briefly, but I agree that the rest of the guide doesn't really talk about notebooks much and then suddenly brings it up again in that section. I'll tag this with our internal ticket number to help keep track of it.

**Comment by laisbsc** [comment]
Hello @Arcticnode, hope you are all good :)

Ever since you raised this issue we revamped the Table of Contents on our docs. We also released a updated version of the SpaceFlights tutorial.
Have you had a chance to check it out? Let us know what you think!

Also, are you happy for me to close this ticket?

**Comment by Arcticnode** [comment]
> Hello @Arcticnode, hope you are all good :)
> 
> Ever since you raised this issue we revamped the Table of Contents on our docs. We also released a updated version of the SpaceFlights tutorial.
> Have you had a chance to check it out? Let us know what you think!
> 
> Also, are you happy for me to close this ticket?

Yes, I am happy with that. Thank you for taking my comment into consideration! :)
