### ISSUE TITLE
".jsonl" datasets support

### ISSUE THREAD

**Issue by eawer** [quantumblacklabs/kedro#227]
## What are you trying to do?
I'm trying to load a dataset that contains of JSON objects - one JSON object per line (http://jsonlines.org/). I tried both `JSONLocalDataSet` and `JSONDataSet` like this:
```
users:
    type: JSONDataSet
    filepath: data/01_raw/users.jsonl
```

If I try to run `context.catalog.load('users')` I see the error
```
DataSetError: Failed while loading data from data set JSONDataSet(filepath=data/01_raw/users.jsonl, protocol=file).
Trailing data
```
Can you tell me if I can load `jsonl` datasets right now?

**Comment by 921kiyo** [comment]
Hi @eawer, thank you for your question! As you can see in https://github.com/quantumblacklabs/kedro/blob/develop/kedro/extras/datasets/pandas/json_dataset.py#L142, `JSONDataSet` uses `pd.read_json` behind the scene, and it takes an argument `lines=True` to accept JSONL (see https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_json.html). So you could pass it something like 
```
users:
    type: JSONDataSet
    filepath: data/01_raw/users.jsonl
    load_args:
       lines: True
```

Hope this helps :) 
Btw, we also keep eyes on StackOverflow with kedro tags, so if you have any other questions in the future, please post it there (https://stackoverflow.com/questions/tagged/kedro)

**Comment by eawer** [comment]
Works like a charm, thanks!
