### ISSUE TITLE
Add in more Python virtual environment information

### ISSUE THREAD

**Issue by yetudada** [quantumblacklabs/kedro#230]
## Description
We've been asked how Kedro works with `venv` and `pipenv` and have prepared documents that have never landed up in our core documentation. 

## Context
This would help users with their queries about `venv` and `pipenv`.

## Possible Implementation
- We follow this documentation style guide: https://github.com/quantumblacklabs/kedro/blob/develop/docs/README.md
- We have the documentation specified in our `kedro-examples` repository [**here**](https://github.com/quantumblacklabs/kedro-examples/blob/master/kedro-training/docs/02_virtual-environment.md)
- You could just copy the docs in, or if you want you could create new docs for us

**Comment by priyanka1414** [comment]
Taking this one

**Comment by DmitriiDeriabinQB** [comment]
Addressed in #260
