### ISSUE TITLE
Document all decorators in `kedro.extras.decorators`

### ISSUE THREAD

**Issue by yetudada** [quantumblacklabs/kedro#231]
## Description
- Our contribution process has changed recently with the introduction of [`kedro.extras`](https://github.com/quantumblacklabs/kedro/tree/develop/kedro/extras), the new 🏡 for all of our datasets, decorators and transformers. 
- It's in this place that all contributor can add extensions to Kedro
- We want to track contributions to [`kedro.extras.decorators`](https://github.com/quantumblacklabs/kedro/tree/develop/kedro/extras/decorators) by including a directory-level `README.md` that describes what's in this directory 
- Currently this page just supports the installation requirements for the Memory Profiler, which can be moved further down the page

## Context
- It will help us keep track of all of the amazing contributions that the open source developers make
- It also gives users a high-level view of all the decorators we support in [`kedro.extras.decorators`](https://github.com/quantumblacklabs/kedro/tree/develop/kedro/extras/decorators)

## Possible Implementation
- We follow this documentation style guide: https://github.com/quantumblacklabs/kedro/blob/develop/docs/README.md
- Each section for each tool could have the following: 
  - A human-understandable title of the decorator e.g. Memory Profiler
  - A brief description of what the decorator does
  - Who created it (we suggest just leaving the header for this as you will not know this)
  - How to install it? (Optional)

**Comment by foolsgold** [comment]
I'm working on this!
