### ISSUE TITLE
[KED-1395] Document all datasets in `kedro.extras.datasets`

### ISSUE THREAD

**Issue by yetudada** [quantumblacklabs/kedro#232]
## Description
- Our contribution process has changed recently with the introduction of [`kedro.extras`](https://github.com/quantumblacklabs/kedro/tree/develop/kedro/extras), the new 🏡 for all of our datasets, decorators and transformers. 
- It's in this place that all contributor can add extensions to Kedro
- We want to track contributions to [`kedro.extras.datasets`](https://github.com/quantumblacklabs/kedro/tree/develop/kedro/extras/datasets) by including a directory-level `README.md` that describes what's in this directory 
- This could be a table or even paragraph description of what you'll find here

## Context
- It will help us keep track of all of the amazing contributions that the open source developers make
- It also gives users a high-level view of all the datasets we support in [`kedro.extras.datasets`](https://github.com/quantumblacklabs/kedro/tree/develop/kedro/extras/datasets)

## Possible Implementation
- We follow this documentation style guide: https://github.com/quantumblacklabs/kedro/blob/develop/docs/README.md

We're thinking of doing something like this in this doc

`pandas`

| Dataset Name | Saving Mechanism | Creator      |
|--------------|------------------|--------------|
| `CSVDataSet` | `pandas`         | QuantumBlack |
| ...          | ...              | ...          |

`spark`

| Dataset Name   | Saving Mechanism | Creator      |
|----------------|------------------|--------------|
| `SparkDataSet` | `spark`          | QuantumBlack |
| ...            | ...              | ...          |

...

**Comment by Klio-Foxtrot187** [comment]
I am working on this task at the moment.

**Comment by yetudada** [comment]
@Klio-Foxtrot187 Let us know how you're getting on with this. Thank you so much for helping us!

**Comment by Klio-Foxtrot187** [comment]
> @Klio-Foxtrot187 Let us know how you're getting on with this. Thank you so much for helping us!

Hi, apologies for the delay as I am currently in my exam week, with resume with this next week!

**Comment by yetudada** [comment]
We merged this as part of #305
