### ISSUE TITLE
[KED-1397] Document all transformers in `kedro.extras.transformers`

### ISSUE THREAD

**Issue by yetudada** [quantumblacklabs/kedro#233]
## Description
- Our contribution process has changed recently with the introduction of [`kedro.extras`](https://github.com/quantumblacklabs/kedro/tree/develop/kedro/extras), the new 🏡 for all of our datasets, decorators and transformers. 
- It's in this place that all contributor can add extensions to Kedro
- We want to track contributions to [`kedro.extras.transformers`](https://github.com/quantumblacklabs/kedro/tree/develop/kedro/extras/transformers) by including a directory-level `README.md` that describes what's in this directory 
- This could be a table or even paragraph description of what you'll find here

## Context
- It will help us keep track of all of the amazing contributions that the open source developers make
- It also gives users a high-level view of all the datasets we support in [`kedro.extras.transformers`](https://github.com/quantumblacklabs/kedro/tree/develop/kedro/extras/transformers)

## Possible Implementation
- We follow this documentation style guide: https://github.com/quantumblacklabs/kedro/blob/develop/docs/README.md
- Each section for each tool could have the following: 
  - A human-understandable title of the transformer e.g. Time Profiler
  - A brief description of what the transformer does
  - Who created it (we suggest just leaving the header for this as you will not know this)

**Comment by Klio-Foxtrot187** [comment]
I am currently working on this.

**Comment by yetudada** [comment]
This was completed in #259. Thank you @Klio-Foxtrot187!
