### ISSUE TITLE
[KED-1403] Delete `kedro.contrib`

### ISSUE THREAD

**Issue by yetudada** [quantumblacklabs/kedro#235]
## Description
- We recently introduced [`kedro.extras`](https://github.com/quantumblacklabs/kedro/tree/develop/kedro/extras), the new 🏡 for all of our datasets, decorators and transformers. 
- [`kedro.extras`](https://github.com/quantumblacklabs/kedro/tree/develop/kedro/extras) replaces a number of files and directories in Kedro
- In this task, you need to deprecate [`kedro.contrib`](https://github.com/quantumblacklabs/kedro/tree/develop/kedro/contrib), all functionality in this library has been moved to [`kedro.extras`](https://github.com/quantumblacklabs/kedro/tree/develop/kedro/extras)

## Context
- You're helping with our large-scale clean-up of Kedro
- Removing [`kedro.contrib`](https://github.com/quantumblacklabs/kedro/tree/develop/kedro/contrib) allows us to help users with #178 
 
## Possible Implementation
- Just delete the folder and we should be good to go

**Comment by probablyhungryrn** [comment]
I am happy to work on this one!

**Comment by ashutosh1919** [comment]
@yetudada , isn't `kedro.contrib` already removed? because I am not able to see it in the repository.

**Comment by yetudada** [comment]
Hi @ashutosh1919! Thanks for flagging this! You're correct. We handled this change with this [commit](https://github.com/quantumblacklabs/kedro/commit/ecd7277c28b7c962d9ab7f25a1f240d540a206c9). I'll close this issue.
