### ISSUE TITLE
[KED-1433] Create an end-to-end test to verify that new patch release doesn't break backward compatibility 

### ISSUE THREAD

**Issue by limdauto** [quantumblacklabs/kedro#236]
## Description

We want to maintain backward compatibility in Kedro's patch releases. For example, releasing `0.15.6` shouldn't break the main `kedro run` for projects generated with version `0.15.0` to `0.15.5`. Therefore, we should write an end-to-end test in which we generate a project using the earliest Kedro patch version (i.e. `0.X.0`) for the current minor version (`0.X`) and make sure that `kedro run` doesn't break.

## More information:

* Kedro's end-to-end tests are written using [behave](https://github.com/behave/behave)
* You can run Kedro's end-to-end tests with `make e2e-tests` or simply just running `behave`
* The tests are located in [`features`](https://github.com/quantumblacklabs/kedro/tree/develop/features)

As usual, check out the [contributing guide](https://github.com/quantumblacklabs/kedro/blob/master/CONTRIBUTING.md) for more information.

**Comment by yetudada** [comment]
We're going to handle this task internally after we release 0.16.0.
