### ISSUE TITLE
[KED-1404] Remove trufflehog pinned dependency in test_requirements.txt

### ISSUE THREAD

**Issue by 921kiyo** [quantumblacklabs/kedro#237]
## Description

One of trufflehog's dependencies dependency upgraded itself and broke everything (see https://github.com/dxa4481/truffleHog/issues/200). 

We've pinned it inside test_requirements as a temporary workaround, but it is fixed in their side. So we would like to remove the line in `test_requirements.txt`

```
gitdb2==3.0.0 # pin trufflehog dependency to get it working for now https://github.com/dxa4481/truffleHog/issues/200
```
While doing this,  remember to bump the lower bound of trufflehog.

**Comment by Seraph2000** [comment]
I'm looking into this one!

**Comment by 921kiyo** [comment]
Resolved in https://github.com/quantumblacklabs/kedro/commit/43788266d5d69a961d81fef299f3c959e35f8f92
