### ISSUE TITLE
[KED-1442] Delete `extras`

### ISSUE THREAD

**Issue by yetudada** [quantumblacklabs/kedro#238]
## Description
- We're busy with house-cleaning and in this task, you need to deprecate this [`extras`](https://github.com/quantumblacklabs/kedro/tree/develop/extras) directory
- It's been relocated in the latest release to [**here**](https://github.com/quantumblacklabs/kedro/tree/develop/tools)

## Context
- You're helping with our large-scale clean-up of Kedro
 
## Possible Implementation
- You're going to be deleting this directory: https://github.com/quantumblacklabs/kedro/tree/develop/extras

**Comment by WKND21** [comment]
Currently working on this

**Comment by andrii-ivaniuk** [comment]
`extras` was deleted. Merge commit: ecd7277c28b7c962d9ab7f25a1f240d540a206c9
