### ISSUE TITLE
[KED-1408] Delete some of the `AbstractDataSets` in `kedro.io`

### ISSUE THREAD

**Issue by yetudada** [quantumblacklabs/kedro#241]
## Description
- We recently introduced [`kedro.extras`](https://github.com/quantumblacklabs/kedro/tree/develop/kedro/extras), the new 🏡 for all of our datasets, decorators and transformers. 
- [`kedro.extras`](https://github.com/quantumblacklabs/kedro/tree/develop/kedro/extras) replaces a number of files and directories in Kedro
- In this task, you need to deprecate some of the datasets in [`kedro.io`](https://github.com/quantumblacklabs/kedro/tree/develop/kedro/io), all functionality in this library has been moved to [`kedro.extras.datasets`](https://github.com/quantumblacklabs/kedro/tree/develop/kedro/extras/datasets)

## Context
- You're helping with our large-scale clean-up of Kedro
- Removing [`kedro.io`](https://github.com/quantumblacklabs/kedro/tree/develop/kedro/io) allows us to help users with #178 for the next major release of Kedro
 
## Possible Implementation
- You're going to be deleting the following files: 
  - https://github.com/quantumblacklabs/kedro/blob/develop/kedro/io/csv_http.py
  - https://github.com/quantumblacklabs/kedro/blob/develop/kedro/io/csv_local.py
  - https://github.com/quantumblacklabs/kedro/blob/develop/kedro/io/csv_s3.py
  - https://github.com/quantumblacklabs/kedro/blob/develop/kedro/io/excel_local.py
  - https://github.com/quantumblacklabs/kedro/blob/develop/kedro/io/hdf_local.py
  - https://github.com/quantumblacklabs/kedro/blob/develop/kedro/io/hdf_s3.py
  - https://github.com/quantumblacklabs/kedro/blob/develop/kedro/io/json_dataset.py
  - https://github.com/quantumblacklabs/kedro/blob/develop/kedro/io/json_local.py
  - https://github.com/quantumblacklabs/kedro/blob/develop/kedro/io/parquet_local.py
  - https://github.com/quantumblacklabs/kedro/blob/develop/kedro/io/pickle_local.py
  - https://github.com/quantumblacklabs/kedro/blob/develop/kedro/io/pickle_s3.py
  - https://github.com/quantumblacklabs/kedro/blob/develop/kedro/io/sql.py
  - https://github.com/quantumblacklabs/kedro/blob/develop/kedro/io/text_local.py
- And you will have to look into our `requirements.txt` and remove the following dependencies: 
  - `pyarrow`
  - `s3fs`
  - `SQLAlchemy`
  - `xlrd`
  - `xlsxwriter`
- And we think `tables` and `requests` will have to be removed too

**Comment by priyanka1414** [comment]
Got this one

**Comment by yetudada** [comment]
Handled this change with this [commit](https://github.com/quantumblacklabs/kedro/commit/ecd7277c28b7c962d9ab7f25a1f240d540a206c9). I'll close this issue.
