### ISSUE TITLE
[KED-996] Parallelise loading and saving of datasets

### ISSUE THREAD

**Issue by lorenabalan** [quantumblacklabs/kedro#242]
## Description & context
Currently, when running a node, input datasets are loaded sequentially, and similarly on saving. The relevant code snippet is under `def run_node` in `kedro.runner.runner`. One way to optimise this is to instead load and save in parallel, so we save time. 

## Possible Implementation
There could be a flag on the runner class (see `AbstractRunner`), which would allow users to opt-in if they would like parallel loading/saving, otherwise defaults to current behaviour. The flag could be passed as an argument into the `_run()` method of the runner, or as an attribute into the instantiation of the runner class.
Would be nice if the documentation also makes it clear that if datasets are not thread-safe, this feature won't work as expected.

**Comment by w0rdsm1th** [comment]
i am looking at this one!

**Comment by w0rdsm1th** [comment]
> i am looking at this one!

nevermind, somebody else already looking at it

**Comment by 921kiyo** [comment]
Resolved in https://github.com/quantumblacklabs/kedro/commit/a6ed5e8612e2ca34b4975965b63c54acc5f06558
