### ISSUE TITLE
[KED-950] Turn on the branch coverage for unit tests

### ISSUE THREAD

**Issue by 921kiyo** [quantumblacklabs/kedro#243]
## Description
Kedro has to have 100% test coverage at C0 (every instruction), but we could make it more robust by changing from C0 to C1 (branch coverage).

See the coverage level in  https://grosser.it/2008/04/04/whats-my-coverage-c0-c1-c2-c3-path-coverage/

## Context
This would improve the test coverage of Kedro codebase, meaning our codebase will be more robust. 

For the detail of branch coverage measurement, see 
https://coverage.readthedocs.io/en/v4.5.x/branch.html

## Possible Implementation

In `.coveragerc`, add
```
[run]
branch=True
```
which will likely make the coverage <100%. If so, add additional unit tests to make it 100% 
 (I haven't tested the possible implementation, so might need extra tweak to make it work)

**Comment by Cheukting** [comment]
I can have a look at this

**Comment by yetudada** [comment]
We're closing this PR! Thank you for the help but we found it was a bit too much effort to do for the gain.
