### ISSUE TITLE
Convert Pharmaceutical ML pipeline into a pipeline `.json`

### ISSUE THREAD

**Issue by yetudada** [quantumblacklabs/kedro#244]
## Description
- We have GitHub issues in other Kedro repositories
- Here is the link to this one: https://github.com/quantumblacklabs/kedro-examples/issues/24

**Comment by w0rdsm1th** [comment]
i'm gonna work on this one!

**Comment by w0rdsm1th** [comment]
all done (i think)

**Comment by yetudada** [comment]
You are! Thank you @w0rdsm1th! I'll close this ticket now.
