### ISSUE TITLE
Update training documentation to reflect changes to project template

### ISSUE THREAD

**Issue by yetudada** [quantumblacklabs/kedro#247]
## Description
- We have GitHub issues in other Kedro repositories
- Here is the link to this one: https://github.com/quantumblacklabs/kedro-examples/issues/25

**Comment by bayesianluxury** [comment]
Mine!

**Comment by bayesianluxury** [comment]
Updated here - https://github.com/quantumblacklabs/kedro-examples/pull/29

**Comment by yetudada** [comment]
Thank you so much @bayesianluxury! Great work! I'll close this issue now because it's complete.
