### ISSUE TITLE
[KED-1404] Remove trufflehog pinned dependency in test_requirements.txt for Kedro-Airflow

### ISSUE THREAD

**Issue by 921kiyo** [quantumblacklabs/kedro#248]
## Description
- We have GitHub issues in other Kedro repositories
- Here is the link to this one: https://github.com/quantumblacklabs/kedro-airflow/issues/47

**Comment by pitterb** [comment]
I'm taking this one

**Comment by 921kiyo** [comment]
Resolved in https://github.com/quantumblacklabs/kedro-airflow/pull/48
