### ISSUE TITLE
Consider adopting the term "workflow" in place of "partial pipeline"

### ISSUE THREAD

**Issue by ankostis** [quantumblacklabs/kedro#25]
Congratulations for your new project.

I just like to suggest to replace the 2-word term "partial-pipeline" with "(actual) workflow", which i find it more intuitive.

**Comment by ankostis** [comment]
Actually, the "instantiated pipeline" executed on each run is always different from the "pipeline definition", even if they both contain the exact same nodes.  
But for that case, the "*partial* pipeline" is a misnomer.

**Comment by idanov** [comment]
@ankostis Thank you very much for your feedback! Could you please provide links to the places in the documentation which make the term `partial pipeline` confusing? Would something like `subpipeline` be more appropriate there?

**Comment by ankostis** [comment]
I think you missunderstood me, there is no confusion in the docs as it is now. 
My suggestion is a matter of adopting terminology closely related to ETL solutions.

When a pipeline gets instantiated, it can be called "instantiated pipeline" but you can also adopt the term "workflow" to describe it in a single word.  And then the "partial instantiated pipeline" becomes "partial workflow", which is handily shorter.

If you disagree, please, feel free to close this issue.

**Comment by idanov** [comment]
@ankostis Sorry for the missunderstanding, I think I get now what you meant. Thank you for raising this! At the moment it doesn't make sense for us to change the term to `workflow` since we don't use that term internally. However I think it's worth leaving the issue open and if more people express interest in changing that term to `workflow`, we'll be happy to change it.

**Comment by 921kiyo** [comment]
I am closing this now, but we might re-open it if more people express interest :)
