### ISSUE TITLE
[KED-1456] Include Dockerfile to run tests

### ISSUE THREAD

**Issue by crdoconnor** [quantumblacklabs/kedro#254]
## Description

Problem:

* the unit tests have specific environmental requirements - both a specific version of miniconda and java - #255 
* The behave tests also have specific environment requirements - #262 

## Context

Checking out the project and running pytest on an average ubuntu distro fails with cryptic error message (related to environment, but this isn't obvious, tests require specific version of java).

## Possible Implementation

Run pytest tests and behave tests in docker container with environment set up correctly (possibly via make).

**Comment by yetudada** [comment]
Hi @crdoconnor! We had a chat about this one and the resolution we're going to implement will be a way to tests without the use of Spark, and therefore the Java requirement falls away. Do let me know if this will resolve your error. 

The other suggested plan of action was a suggestion to use our [`kedro-docker`](https://github.com/quantumblacklabs/kedro-docker) plugin to help you with this packaging. Let me know if you have any other thoughts on this, if not I'll close over the next few days.

**Comment by felipepenha** [comment]
Hi @yetudada I am experiencing similar issues. The patch "tests without the use of Spark" will not work out for me, since I actually would like to use Spark in my code. I would like to use Spark in the Docker container, and not in my machine, does I keep getting errors on the test (that runs locally).

**Comment by mzjp2** [comment]
I'll go ahead and close this issue, from the reasons mentioned in @yetudada comment. We don't think the use of a docker container for developing on `kedro` itself is necessary, and we've slimmed down on the pre-requisites for working on Kedro. If you come up with any other issues, please feel free to open another issue and thank you for raising this one! :)
