### ISSUE TITLE
pytest fails on freshly checked out codebase if certain environmental prerequisites are not met

### ISSUE THREAD

**Issue by crdoconnor** [quantumblacklabs/kedro#255]
## Description

Fails with a somewhat cryptic error:

```
IllegalArgumentException                  Traceback (most recent call last)
~/code/kedro/kedro/contrib/decorators/pyspark.py in <module>
----> 1 arg.toPandas()

~/code/kedro/venv/lib/python3.7/site-packages/pyspark/sql/dataframe.py in toPandas(self)
   2148 
   2149         # Below is toPandas without Arrow optimization.
-> 2150         pdf = pd.DataFrame.from_records(self.collect(), columns=self.columns)
   2151 
   2152         dtype = {}

~/code/kedro/venv/lib/python3.7/site-packages/pyspark/sql/dataframe.py in collect(self)
    532         """
    533         with SCCallSiteSync(self._sc) as css:
--> 534             sock_info = self._jdf.collectToPython()
    535         return list(_load_from_socket(sock_info, BatchedSerializer(PickleSerializer())))
    536 

~/code/kedro/venv/lib/python3.7/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

~/code/kedro/venv/lib/python3.7/site-packages/pyspark/sql/utils.py in deco(*a, **kw)
     77                 raise QueryExecutionException(s.split(': ', 1)[1], stackTrace)
     78             if s.startswith('java.lang.IllegalArgumentException: '):
---> 79                 raise IllegalArgumentException(s.split(': ', 1)[1], stackTrace)
     80             raise
     81     return deco

IllegalArgumentException: 'Unsupported class file major version 55'
```

## Context

Was running all the tests with pytest.

## Steps to Reproduce

1. Check out project
2. Run pytest.

## Expected Result

Tests should pass.

## Actual Result

Tests don't pass.

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used : latest
* Python version used : 3.7
* Operating system and version: ubuntu 19.10

**Comment by ZainPatelQB** [comment]
Is this because of your java version? We’ve added a small note in the `CONTRIBUTING.md` under the “running tests locally” section about this: https://github.com/quantumblacklabs/kedro/blob/develop/CONTRIBUTING.md#ci--cd-and-running-checks-locally

**Comment by neomatrix369** [comment]
Potentially can be fixed with a Docker environment proposed by #46 and #254, we could ensure the specific version of Java is installed in the image.

**Comment by yetudada** [comment]
@crdoconnor Is this related to your Java version? If yes, then the update on this one is that we're going to implement will be a way to tests without the use of Spark, and therefore the Java requirement falls away. Do let me know if this will resolve your error.

**Comment by crdoconnor** [comment]
Yes, this was Java related.

**Comment by neomatrix369** [comment]
> @crdoconnor Is this related to your Java version? If yes, then the update on this one is that we're going to implement will be a way to tests without the use of Spark, and therefore the Java requirement falls away. Do let me know if this will resolve your error.

Could you please point me to docs that explain what Java dependencies are required apart from the JDK installed (I have Java 8 build 172 on my path), I'm looking at #267 and currently 72 tests are failing due to this. I'll also try to dig into the issue in the meanwhile. Thanks

**Comment by mzjp2** [comment]
We've removed the need to have Spark or Java installed to run the tests, as mentioned by @yetudada so this issue should be resolved now. I'll go ahead and close this, but if you're still running into any trouble please feel free to re-open or create a new issue! :)
