### ISSUE TITLE
[KED-1457] behave fails on freshly checked out repo

### ISSUE THREAD

**Issue by crdoconnor** [quantumblacklabs/kedro#262]
## Description

Behave tests fail on freshly checked out repo.

## Actual Result

```
HOOK-ERROR in before_all: FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp_fhmby84/bin/pip': '/tmp/tmp_fhmby84/bin/pip'

ABORTED: By user.
0 features passed, 0 failed, 0 skipped, 11 untested
0 scenarios passed, 0 failed, 0 skipped, 20 untested
0 steps passed, 0 failed, 0 skipped, 0 undefined, 139 untested
Took 0m0.000s

```

Error appears to be related to this line:

```
context.venv_dir = Path(create_new_venv())
```

The behave tests run correctly if the environment variable E2E_VENV is set, suggesting that this is related to a failure to create a virtualenv in behave.

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used : latest version of master branch
* Python version used (`python -V`): python 3.7
* Operating system and version: ubuntu 17.10

**Comment by yetudada** [comment]
Hi @crdoconnor, we're going to look into this one. I've created a ticket on it on our backlog. Thanks for raising this!

**Comment by 921kiyo** [comment]
Hi, thank you for reporting the bug! Could you please describe the steps of commands you ran, so we can reproduce the error?

**Comment by crdoconnor** [comment]
I got the error running the behave test command with make on a freshly
checked out repo on Ubuntu 17.10.

**Comment by yetudada** [comment]
Hi @crdoconnor! We hope that you're well. We have made some changes to the behave environment setup recently. You should try to see if this works. I'm going to close this ticket but it can be reopened if you still have issues.
