### ISSUE TITLE
Link locations for example datasets don't point to raw data

### ISSUE THREAD

**Issue by awqb** [quantumblacklabs/kedro#27]
## Description

The links in the "Adding your datasets to `data`" section of [this page](https://kedro.readthedocs.io/en/latest/03_tutorial/03_set_up_data.html) do not point straight at the CSV / xlsx. So, they cannot be downloaded using `wget` or similar. They could be replaced with links to the raw content, e.g.:

https://raw.githubusercontent.com/quantumblacklabs/kedro/develop/docs/source/03_tutorial/data/reviews.csv

Happy to submit a PR with these changes.

## Context
I was trying to download the data for the spaceflights tutorial using `wget`.

## Steps to Reproduce

1. Do: `wget https://github.com/quantumblacklabs/kedro/tree/develop/docs/source/03_tutorial/data/reviews.csv` 
2. Inspect `reviews.csv`, it is html.

## Expected Result
I expected the actual CSV to be returned.

## Actual Result
I got html instead.

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.14.2
* Python version used (`python -V`): 3.7.2
* Operating system and version: macOS High Sierra

**Comment by yetudada** [comment]
Thanks for opening up this issue @awqb! 🎉

**Comment by idanov** [comment]
This was resolved by #28.
