### ISSUE TITLE
Is MatplotlibLocalWriter same to MatplotlibWriter?

### ISSUE THREAD

**Issue by 8-u8** [quantumblacklabs/kedro#271]
I'm trying to save some plots to local folder by matplotlib based on [this document](https://kedro.readthedocs.io/en/stable/kedro.contrib.io.matplotlib.MatplotlibLocalWriter.html?highlight=matplot).

However, I received `ImportError` below: 
>`cannot import name 'MatplotlibLocalWriter' from 'kedro.contrib.io.matplotlib'`.

I checked function names in `kedro.contrib.io.matplotlib`, and found similarly function `MatplotlibWriter`.

Are they same function? If so, I suggest to edit that documents.

Thank you for your help.

**Comment by yetudada** [comment]
Hi @8-u8! Thank you for raising this error. What version of Kedro are you using? 

In `kedro 0.15.6` and `kedro 0.15.7`, we are deprecating [`MatplotlibLocalWriter`](https://kedro.readthedocs.io/en/stable/kedro.contrib.io.matplotlib.MatplotlibLocalWriter.html) in favour of [`MatplotlibWriter`](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.matplotlib.MatplotlibWriter.html). We released a new series of datasets that have file storage abstraction, have a look at the Release notes [**here**](https://github.com/quantumblacklabs/kedro/releases/tag/0.15.6). 

If you are using `MatplotlibWriter` with the YAML API in `kedro 0.15.6` and `kedro 0.15.7` then your `catalog.yml` would look like this:
```
results_plot:
  type: matplotlib.MatplotLibWriter
  filepath: 08_results/plots/output_1.jpg
```

**Comment by 8-u8** [comment]
Thank you @yetudada !
I've checked version, then it was 0.15.5....!
I will upgrade Kedro to latest version.

**Comment by yetudada** [comment]
Upgrade and let me know if this sorts out your issue. I'll only close this issue when you have successfully managed to use the new `MatplotlibWriter`.

**Comment by 921kiyo** [comment]
Closing this, but if you still need any help with this, feel free to reopen it.
