### ISSUE TITLE
Installation instruction does not contain set up with Docker

### ISSUE THREAD

**Issue by kuldeep-singh-duhan** [quantumblacklabs/kedro#272]
## Description
Most of the developers are using python with Docker now a days and I see instructions contain only conda and pycharm. I will suggest to have the setup with Docker as well

## Context
I still find it difficult to setup Kedro on localsetup, however when I did with Docker it was much simpler and reproducible, hence would like to add this feature and if needed I can do that and contribute as well

## Possible Implementation
We could use a base python image or a standard image loaded with other packages and extend it

**Comment by neomatrix369** [comment]
@kuldeep-singh-duhan good idea, please have a look at the issue #265 and also the PR #268 - please see if what you have expressed above is covered partially if not fully.

**Comment by kuldeep-singh-duhan** [comment]
Yes, it looks good and work. I will close my issue
