### ISSUE TITLE
request cli command - kedro list

### ISSUE THREAD

**Issue by WaylonWalker** [quantumblacklabs/kedro#273]
## Description

I have some use cases where it would be nice to list things out of the command line. 

## Context

I would like to do things such as saving all pipelines to JSON from the command line, but in order to do that, I need a way to list the pipelines.

## Possible Implementation
 I think rather than cluttering all the top level with many list commands I think a single list command with various flags would be appropriate.

``` bash
❯ kedro list --help
Usage: kedro list [OPTIONS]

  list things about the project

Options:
  -p, --pipelines
  -t, -- tags
  -l, -- layers
  -d, -- datasets
  -n, -- nodes
  -- parameters
```

## Possible Alternatives

I am open to anything you have.

# 👏 Thank You

Thank you for open sourcing everything in and around kedro, it is such an amazing project!

**Comment by ZainPatelQB** [comment]
I think this is something we’re actively working on at the moment! 😀

**Comment by WaylonWalker** [comment]
> I think this is something we’re actively working on at the moment! 😀

Great! Thanks for the quick reply @ZainPatelQB.
