### ISSUE TITLE
Getting errors Using SQL with Kedro

### ISSUE THREAD

**Issue by vincenzo-scotto001** [quantumblacklabs/kedro#274]
What I am trying to do is pass in credentials to the catalog.yml file. The error I keep getting is: 
(pyodbc.InterfaceError) ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')
(Background on this error at: http://sqlalche.me/e/rvf5)

I checked my ODBC and tested all the drivers and all give me this error. Here is the connection string I am attempting to use:
"mssql+pyodbc://{driver}:username:password@IPaddress/dbname"

I also tried:
mssql+pymssql://username:password@IPaddress/dbname

That also did not work. Any help would be appreciated!

**Comment by vincenzo-scotto001** [comment]
So it seems that that isn't exactly the correct syntax. I had to do something along these lines to get my next error:
"DRIVER={SQL Server Native Client 11.0};SERVER="111.11.111.11";DATABASE="DBname";UID="Username";PWD="password""

Error is:
get_single_data
    node = self.get_single_node()
  File "ext\_yaml.pyx", line 707, in _yaml.CParser.get_single_node
  File "ext\_yaml.pyx", line 725, in _yaml.CParser._compose_document
  File "ext\_yaml.pyx", line 776, in _yaml.CParser._compose_node
  File "ext\_yaml.pyx", line 890, in _yaml.CParser._compose_mapping_node
  File "ext\_yaml.pyx", line 776, in _yaml.CParser._compose_node
  File "ext\_yaml.pyx", line 892, in _yaml.CParser._compose_mapping_node
  File "ext\_yaml.pyx", line 905, in _yaml.CParser._parse_next_event
yaml.parser.ParserError: while parsing a block mapping

**Comment by vincenzo-scotto001** [comment]
I solved the issue. 

Seems like odbc does not work nicely with Kedro. For anyone else that may have a similar issue in the future, use myssql instead for the connection string in the credentials.yml file.

**Comment by lucasjamar** [comment]
For anyone who is wondering on how to convert a odbc connection to a mysql, I used the following [solution](https://stackoverflow.com/a/48861231):

from urllib.parse import quote_plus

conn =  "DRIVER={ODBC Driver 17 for SQL Server};SERVER=IP_ADDRESS;DATABASE=DataLake;UID=USER;PWD=PASS"
quoted = quote_plus(conn)
new_con = 'mssql+pyodbc:///?odbc_connect={}'.format(quoted)
