### ISSUE TITLE
[KED-1561] Rename SparkHiveDataSet

### ISSUE THREAD

**Issue by mrg143504** [quantumblacklabs/kedro#278]
## Description
`SparkHiveDataSet` does not really depend on Hive but on tables that are registered in `spark.sql`. There are some cases where `spark.sql()` does not point to a Hive database (e.g. in Databricks you can access data that is registered in spark tables but the backend might not be a Hive database). 
Now that datasets are undergoing a big refactoring, how about renaming this to `SparkTableDataSet` or something like it?

**Comment by yetudada** [comment]
Thanks for this feedback @mrg143504! How would something like a `SparkSQLDataSet` sound instead? We struggled with `SparkTableDataSet` because it's a bit too close to `SparkDataSet`.

**Comment by mrg143504** [comment]
Hi @yetudada , sounds good! 
Also, now that I think about it let me make it harder and bring into the table another candidate: how about `SparkSQLTableDataSet`? Sounds more consistent with the already existing `SQLTableDataSet` (even though the API for both is different) and would leave it open if someone wanted to develop a `SparkSQLQueryDataSet`. 
I leave the choice up to you! I'll edit the title of the issue.

**Comment by deepyaman** [comment]
@yetudada On the topic of renaming, can we remove the `Spark` prefix from all of these dataset names? :) They're already in the `spark` package, and you don't name everything else with a `Pandas` prefix.

**Comment by mrg143504** [comment]
@deepyaman @yetudada I think this is an interesting topic and we should open a new issue to discuss it in detail. I'm not so sure if we should leave or remove the prefix but I think the point here is how to manage different python libraries to manipulate data. Today kedro assumes pandas as default since is the most used library to manipulate in memory dataframes, but probably more tools will become popular soon (pyarrow, dask, etc.) and it would be good to start thinking how to manage that.

**Comment by mzjp2** [comment]
> @deepyaman @yetudada I think this is an interesting topic and we should open a new issue to discuss it in detail. I'm not so sure if we should leave or remove the prefix but I think the point here is how to manage different python libraries to manipulate data. Today kedro assumes pandas as default since is the most used library to manipulate in memory dataframes, but probably more tools will become popular soon (pyarrow, dask, etc.) and it would be good to start thinking how to manage that.

I think we're on the same page with you there @mrg143504. This is what we're moving towards!

We recently shifted to the `kedro.extras` model and you opt-in to the dependencies you need based on what data you work with.

At the moment, we have `pandas` as a "default" (bundled with our `kedro` package) to preserve backwards compatibility, but we're looking to decouple the I/O completely for precisely the reasons you mention (people who intend to use Pyspark exclusively don't need to spend time installing pandas, etc.)

We're moving to a `dask`-like model where you `pip install "kedro[pandas]"` or `pip install "kedro[spark]"` and loads of others based on what you need to use.

**Comment by yetudada** [comment]
@deepyaman Thanks for throwing a spanner in our renaming 😆 

Can you help us with verifying if the following naming scheme would work? 
`SparkDataSet` -> `DataFrame` so that you can write `spark.DataFrame`
`SparkHiveDataSet` -> `SQLTableDataSet` so that you can write `spark.SQLTableDataSet`
`SparkJDBCDataSet` - `JDBCDataSet` so that you can write `spark.JDBCDataSet`

**Comment by deepyaman** [comment]
> @deepyaman Thanks for throwing a spanner in our renaming 😆
> 
> Can you help us with verifying if the following naming scheme would work?
> `SparkDataSet` -> `DataFrame` so that you can write `spark.DataFrame`
> `SparkHiveDataSet` -> `SQLTableDataSet` so that you can write `spark.SQLTableDataSet`
> `SparkJDBCDataSet` - `JDBCDataSet` so that you can write `spark.JDBCDataSet`

@yetudada Two clarifications:

* Would `DataFrame` not still need "DataSet" in the name? Would `spark.DataSet` be sufficient? `DataFrame` is just what it's backed by once loaded into memory, not on disk (by that logic, almost all of them would be `DataFrame`).
* `spark.SQLTableDataSet` seems OK, but one thing that came to mind a couple days back was if this would get confused with a database table. In this one case, does `SparkSQLTableDataSet` still make sense, if the actually storage format is specific to Spark. This would be unlike CSV or Parquet, where the storage format itself is (mostly) backend-indepdendent.

**Comment by deepyaman** [comment]
@mrg143504 I finally actually got a chance to look into this, and I'm not sure dropping `Hive` from the name would be entirely accurate. While [`_load`](https://github.com/quantumblacklabs/kedro/blob/develop/kedro/extras/datasets/spark/spark_hive_dataset.py#L221-L232) is independent of whether or not the table is actually backed in Hive, [`_save`](https://github.com/quantumblacklabs/kedro/blob/0.15.9/kedro/extras/datasets/spark/spark_hive_dataset.py#L234-L244) ends up calling https://github.com/quantumblacklabs/kedro/blob/0.15.9/kedro/extras/datasets/spark/spark_hive_dataset.py#L211, which actually creates a Hive table, and not a view (as far as I can tell).

I don't know if it makes sense to create a flag/variant to simply save a view.

**Comment by deepyaman** [comment]
As yet another side-note, I'm a bit concerned over the fact that the dataset creates a view always named `tmp` all over the place. How does this play with existing views named `tmp` (less of a concern, mitigable by using something more reserved like `__tmp__`) and parallel execution (I feel like this will cause race conditions).

**Comment by yetudada** [comment]
I'm going to close this ticket. Perhaps there can be work done to rebuild the Hive DataSet and that should be captured in another ticket? 😄
