### ISSUE TITLE
[KED-1514] Add `--check-only` option to verify code is linted

### ISSUE THREAD

**Issue by deepyaman** [quantumblacklabs/kedro#289]
## Description / Context
The way it’s written, `kedro lint` does not "work" as part of a CI process. You run `kedro lint` as a build step, it will see incorrectly sorted imports or unblacked code and fix them then and there--on the build image--and pass the build step.

If `kedro lint` isn’t intended to be used in CI processes, the current implementation is sufficient. However, I would argue that including `kedro lint` in a CI process is a common way of using it (especially at QuantumBlack, because old versions of KernelAI used it as such). In that case, my suggestion would be to have a `kedro lint --check-only` option that you can use in builds.

(synthesized from a Slack conversation with @lorenabalan)

**Comment by lorenabalan** [comment]
Closing as addressed in https://github.com/quantumblacklabs/kedro/commit/8bfa0a8ce0e3bef194ba8d4ca682becf8accdc24
