### ISSUE TITLE
<Question>

### ISSUE THREAD

**Issue by jorge-datanalyst** [quantumblacklabs/kedro#294]
Hello, I am trying to follow the example tutorial but I am having trouble in session https://kedro.readthedocs.io/en/latest/03_tutorial/04_create_pipelines.html#working-in-a-jupyter-notebook, I am trying to run the code shown here but throws an error and although I have tried several things I can not solve the error.

I opened a notebook to test the kedro notebooks session and when I run the following code:

preprocessed_shuttles = catalog.load("preprocessed_shuttles")
preprocessed_companies = catalog.load("preprocessed_companies")
reviews = catalog.load("reviews")

master = create_master_table(preprocessed_shuttles, preprocessed_companies, reviews)
master.head()

and I get the following error:

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-7950015db63b> in <module>
----> 1 preprocessed_shuttles = catalog.load("preprocessed_shuttles")
      2 preprocessed_companies = catalog.load("preprocessed_companies")
      3 reviews = catalog.load("reviews")
      4 
      5 

NameError: name 'catalog' is not defined

I have tried to call the catalog module in various ways, but I cannot get it right. If you can guide me to a solution I thank you.

Sorry for my bad English

**Comment by 921kiyo** [comment]
Hi @jorge-datanalyst thank you for using Kedro!

Did you start the notebook with `kedro jupyter notebook`, not `jupyter notebook`? `kedro jupyter notebook` will run the ipython config under `.ipython/profie_default/startup/00-kedro-init.py` in your project, where you can find `global catalog` variable which is available in your notebook. 

If you did run `kedro jupyter notebook` and got this error, you can inspect it by running `startup_error`, which will hopefully give you some useful error message. 

Hope this helps :) 

Btw, we have StackOverflow tags for `kedro`, where we answer user's questions :) 
https://stackoverflow.com/questions/tagged/kedro

**Comment by jorge-datanalyst** [comment]
It worked, thanks a lot for your help.
