### ISSUE TITLE
[KED-930] Configuration path should allow paths relative to the root of the project

### ISSUE THREAD

**Issue by sansagara** [quantumblacklabs/kedro#3]
## Description

When calling the ConfigLoader from a nested folder, it would be nice if it will still detect paths relative to the root of the project (As well as to the calling script).

It should be easy to implement with the help of  ´os.path.dirname´.
I'll do some tests and try to come up with a suggestion and do a PR.

**Comment by sansagara** [comment]
Please change the Label to Feature Request. 
I opened it as an Issue by mistake.

**Comment by yetudada** [comment]
Hi @sansagara! Thank you for submitting this issue! What were you trying to achieve? We might need more information to address your thoughts and it would be great if you could share an example.

**Comment by lorenabalan** [comment]
I've updated the PR title with our internal ticket number to keep track of this more easily. :)
@sansagara, before we can provide any guidance on this, would you be able to provide more context around your use case, as per @yetudada's request?

**Comment by 921kiyo** [comment]
I am closing this issue for now, but feel free to re-open it with more context.
