### ISSUE TITLE
[KED-1545] Create a Matplotlib Writer that supports versioning

### ISSUE THREAD

**Issue by TomaszKaczmarczyk** [quantumblacklabs/kedro#311]
## Description
Current version of MatplotlibWriter dataset does not support versioning of datasets.

## Context
It's very useful to have versioned charts when running multiple iterations of data science models.

## Possible Implementation
Add support for versioning to the current MatplotlibWriter class.

**Comment by 921kiyo** [comment]
@TomaszKaczmarczyk 

Thank you for the feature request! I've created a ticket and it is in the backlog. Meanwhile, we are more than welcome for anyone's contributing to this extension task :)

**Comment by TomaszKaczmarczyk** [comment]
@921kiyo 

I've created a PR that resolves it - please take a look at https://github.com/quantumblacklabs/kedro/pull/312 :)

**Comment by andrii-ivaniuk** [comment]
Versioning support was added. It will be available in a future release.
