### ISSUE TITLE
[KED-1455] kedro run pdb flag

### ISSUE THREAD

**Issue by d-chambers** [quantumblacklabs/kedro#325]
## Description
When prototyping a pipeline not everything goes right the first time. I often find myself digging through tracebacks so I can determine where to drop a `breakpoint` the I run the node/pipeline again. It would be great if `kedro run` supported a pdb flag to drop the user into an interactive debugging session when an un-handled exception surfaces.

pytest implements [this exact feature](https://docs.pytest.org/en/latest/usage.html#dropping-to-pdb-python-debugger-on-failures).

I know kedro supports pytest for testing pipelines but in some single-use workflows spending time writing tests seems overkill as the pipeline will only ever see one dataset. 

## Possible Implementation
Usage would be as follows:
```
kedro run --pdb
```

## Possible Alternatives
I am not aware of any.

**Comment by d-chambers** [comment]
I just discovered a usable workaround. kedro can be run like this to achieve the desired effect:

```
python -m pdb -m kedro run
```

**Comment by lorenabalan** [comment]
Hi @d-chambers apologies, this somehow got lost in the inbox. We have an item in our backlog to have a look at our interactive/debug workflow with Kedro, we'll make sure to keep your observation in mind as well. It might end up just being a documentation exercise, or some changes to our framework might be done to better facilitate that effort. We ask that you're a little patient with us, we're working through a long series of improvements for our next release. 🙏 
Possibly related to https://github.com/quantumblacklabs/kedro/pull/225 .

**Comment by d-chambers** [comment]
Hi @lorenabalan, thanks for the update. I am certainly in no rush, especially since there is a workaround. A big thanks to you and your team making a great open-source tool!

**Comment by lorenabalan** [comment]
Hi @d-chambers , good news! This has become significantly easier since we introduced [Hooks](https://kedro.readthedocs.io/en/stable/04_user_guide/15_hooks.html) in 0.16.*. @limdauto and @mzjp2 went ahead and included an example in our docs that you might find useful: https://github.com/quantumblacklabs/kedro/commit/f227d4dc2ec22e89fa519457b690111c8a8827b0. Bear in mind this will only be available on develop, so on the `latest` readthedocs url.

**Comment by lorenabalan** [comment]
Closing this as resolved as per https://kedro.readthedocs.io/en/latest/04_user_guide/16_debugging.html

**Comment by WaylonWalker** [comment]
> Hi @d-chambers , good news! This has become significantly easier since we introduced [Hooks](https://kedro.readthedocs.io/en/stable/04_user_guide/15_hooks.html) in 0.16.*. @limdauto and @mzjp2 went ahead and included an example in our docs that you might find useful: [f227d4d](https://github.com/quantumblacklabs/kedro/commit/f227d4dc2ec22e89fa519457b690111c8a8827b0). Bear in mind this will only be available on develop, so on the `latest` readthedocs url.

@lorenabalan can hooks reference cli arguments?  It would be nice to be able to have a `--pdb` option similar to frameworks like pytest even if its not native.

**Comment by lorenabalan** [comment]
If I understood your question right, you can have hooks that inspect `click.get_current_context` to look for a debugging flag and start a `pdb` session based on that. :)
