### ISSUE TITLE
Path of an input instead of an input dataset

### ISSUE THREAD

**Issue by Chtchou** [quantumblacklabs/kedro#334]
For a given node, is it possible to obtain a dataset file path from the catalog? By default, if we add the name of the dataset as input it will load the dataset from the path defined in the catalog.

Thanks!

**Comment by WaylonWalker** [comment]
Given a node named `"A"` we can find the path to its input by first asking for its input to get the catalog entry name, then we can get the path from the catalog by using the `datasets` attached to the catalog.

## If you have only one input
_simple_

``` python
>>> a_inputs = pipeline.only_nodes("A").inputs[0]
'raw_A'
>>> a_inputs_datasets= getattr(catalog.datasets, entry)
<kedro.io.csv_s3.CSVS3DataSet at 0x7fffbd07e850>
>>> a_inputs_paths = dataset.filepath
'data/raw/a'
```

## If you have only multiple inputs
_more robust_

``` python
>>> a_inputs = pipeline.only_nodes("A").inputs
['raw_A']
>>> a_inputs_datasets= [getattr(catalog.datasets, entry) for entry in a_inputs]
[<kedro.io.csv_s3.CSVS3DataSet at 0x7fffbd07e850>]
>>> a_inputs_paths = [dataset.filepath for dataset in datasets]
['data/raw/a']
```

**Comment by lorenabalan** [comment]
Hi @Chtchou , can I ask what is your use case for filepaths inside the nodes? Also is it for an interactive workflow, or a pipeline run, etc?

@WaylonWalker 's code snippets are pretty much on point, the only difference is `filepath` is a private attribute in kedro datasets, so it'll be `catalog.datasets.input_name._filepath`. 

An alternative would be to create a custom dataset that on load returns the filepath, not the data, but that feels a bit like an anti-pattern, depending on how it's used.

**Comment by Chtchou** [comment]
Hi @WaylonWalker, thank you for your answer it kinds of help but doesn't seem to be what I was exactly looking for. I will give more detail below.

Hi @lorenabalan,

Thank you for getting back to me. I did some preprocessing to obtain a JSON file (as a node output) and I saved it by writing it in the catalog. After that, I need the path of the JSON file to be read by a detection library, that's why I want to read the file path. It is possible for me to instead of returning a dataset to return a file path or modify the detection library for that. But it seems to kind of defeat the purpose of using the catalog to load objects or creating library modifications which would be probably erased after each library update.

**Comment by lorenabalan** [comment]
Thanks for the additional context. Not entirely certain what the detection library does, but what about creating a custom dataset that integrates the library? So on load it reads using this detection library. You can use [transcoding](https://kedro.readthedocs.io/en/stable/04_user_guide/04_data_catalog.html#transcoding-datasets) to facilitate the use case of reading and writing the same file format (in your case, JSON) in 2 different ways.

```
my_data@json:
  type: JSONDataSet
  filepath: data/02_intermediate/data.json

my_data@wow:
  type:WowDataSet
  filepath: data/02_intermediate/data.json
```

**Comment by Chtchou** [comment]
Seems a very good solution! Thank you for your help I will give it a shot!
