### ISSUE TITLE
[KED-1569] Documentation as PDF or ePub

### ISSUE THREAD

**Issue by jahas** [quantumblacklabs/kedro#338]
Hi guys,

I really appreciate your work. I will take a deep look at your work later, but now I'd like to read documentation :)

Could you please activate building documentation to PDF or ePub at readthedocs ?
It would be nice, I could read it at Kindle device then.

Thank you in advance!
Adam

**Comment by 921kiyo** [comment]
@jahas Thank you for the suggestion! This is a great idea! I've put this request in the backlog and will investigate it :)

**Comment by lorenabalan** [comment]
Hi @jahas , pdf docs have been enabled (you can see the develop ones here https://kedro.readthedocs.io/_/downloads/en/latest/pdf/), so I'll go ahead and close this as resolved.  Thanks a lot for the suggestion! 😊

**Comment by gitgud5000** [comment]
Hi, the latest docs available in pdf are for Kedro 0.18.5; are there any plans to update this?

https://readthedocs.org/projects/kedro/downloads/

**Comment by astrojuanlu** [comment]
Hi @gitgud5000, I disabled PDF docs in #2362:

> Also, I removed the PDF documentation, because it's making build longers at the cost of producing a 730-page document that I bet almost nobody is reading... but I could be wrong here, happy to rollback.

This proves that at least _someone_ is reading said PDF :) could you comment on how do you find the 0.18.5 one? Are you using it often?

Sphinx PDF backend is finicky to say the least, so it takes some resources to keep them working.
