### ISSUE TITLE
kedro install fails

### ISSUE THREAD

**Issue by f-istvan** [quantumblacklabs/kedro#340]
## Description
Running `$ kedro install` fails with:

```
Usage: kedro [OPTIONS] COMMAND [ARGS]...
Try 'kedro -h' for help.

Error: No such command 'install'.
```

## Environment
$ python --version
`Python 3.6.6`

$ kedro info
```
 _            _
| | _____  __| |_ __ ___
| |/ / _ \/ _` | '__/ _ \
|   <  __/ (_| | | | (_) |
|_|\_\___|\__,_|_|  \___/
v0.15.9

kedro allows teams to create analytics
projects. It is developed as part of
the Kedro initiative at QuantumBlack.

No plugins installed
```

Thank you for the answers!

**Comment by mzjp2** [comment]
Are you inside a Kedro project? `kedro install` is a project-specific from your `kedro-cli.py` and you need to be in the root directory of your Kedro project to be able to use it.

It's there to install your project dependencies and so is necessarily a project-specific command.

**Comment by f-istvan** [comment]
Hi,

That's exactly what I missed. I have:
`kedro-exercises  kedro-hooks-tutorial  kedro-training  kedro-tutorial  LICENSE.md  README.md
`
and had to go into `cd kedro-tutorial`.

The error message is very misleading though.

Thank you!

**Comment by mzjp2** [comment]
Glad to hear its sorted now and thank you for the feedback on the error being misleading (I tend to agree). I'll file a ticket about making the error more specific and will close this for now as it's fixed. Feel free to open another issue if you come across anything else. :)
