### ISSUE TITLE
pandas.CSVDataset imports unnecessary packages such as google-cloud-bigquery

### ISSUE THREAD

**Issue by Minyus** [quantumblacklabs/kedro#342]
## Description

Importing `pandas.CSVDataset` runs unnecessary modules such as [`kedro.extras.datasets.pandas.gbq_dataset.py`](https://github.com/quantumblacklabs/kedro/blob/develop/kedro/extras/datasets/pandas/gbq_dataset.py) in addition to [`kedro.extras.datasets.pandas.csv_dataset.py`](https://github.com/quantumblacklabs/kedro/blob/develop/kedro/extras/datasets/pandas/csv_dataset.py) due to
[`kedro.extras.datasets.pandas.__init__.py`](https://github.com/quantumblacklabs/kedro/blob/develop/kedro/extras/datasets/pandas/__init__.py)

## Context
I'm trying to use `pandas.CSVDataset`, but I get an error in google-cloud-bigquery package which is not necessary.

## Steps to Reproduce
1. Import `pandas.CSVDataset`

## Expected Result
Run only [`kedro.extras.datasets.pandas.csv_dataset.py`](https://github.com/quantumblacklabs/kedro/blob/develop/kedro/extras/datasets/pandas/csv_dataset.py)

## Actual Result
I get
```
File "/usr/local/lib/python3.6/dist-packages/google/cloud/bigquery/schema.py", line 17, in <module>
    from six.moves import collections_abc
ImportError: cannot import name 'collections_abc'
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): The latest `develop` branch (commit e2c271be3646d6c564a67960b67fb74c6ba1ece8)
* Python version used (`python -V`): 3.6.8
* Operating system and version: Ubuntu 18.04.3 LTS

**Comment by mzjp2** [comment]
Hi @Minyus 👋!

Thanks for raising this and I'm totally on board with your concerns. The reason we moved to the `kedro.extras.datasets` model in the first place was to cut down on dependencies and give users more granular control over what they need. I think we haven't got this quite right and we have an internal ticket open on our backlog pending a technical design session to discuss this and settle on a decision.

The issue stems from us allowing users to specify the dataset type via `pandas.CSVDataSet` which means we need to place `CSVDataSet` in the `__init__` of `kedro.extras.datasets.pandas` and so everything in `kedro.extras.datasets.pandas` gets loaded in.

We'll keep you updated on what we decide and if you have any ideas you'd like to contribute, please feel free to share them here!

**Comment by Minyus** [comment]
Hi @mzjp2 

Thank you for explanation.

I understood that the current design came from the installation commands.
Then the following ways seem to be modular and make more sense (at least to me).

- `pip install kedro[bigquery]` to use `GBQTableDataSet` in  [gbq_dataset.py](https://github.com/quantumblacklabs/kedro/blob/develop/kedro/extras/datasets/pandas/gbq_dataset.py)
- `pip install kedro[sqlalchemy]` to use `SQLTableDataSet` in [sql_dataset](https://github.com/quantumblacklabs/kedro/blob/develop/kedro/extras/datasets/pandas/sql_dataset.py)
- `pip install kedro[pyarrow]` to use `ParquetDataSet` in [parquet_dataset.py](https://github.com/quantumblacklabs/kedro/blob/develop/kedro/extras/datasets/pandas/parquet_dataset.py)

**Comment by mzjp2** [comment]
Those make sense, but some of the tradeoffs are that we lose consistency with our `extra_requires` (some are groups, and others are individual datasets) and is `pip install kedro[pyarrow]` really that helpful over `pip install pyarrow` for example? Is it also scaleable as we people contribute more and more datasets? These are the questions we're wrestling with when trying to design a solution to this.

**Comment by Minyus** [comment]
Yes, I understand designing a solution is tough.
I'm now wondering that lazy loading (deferring to load the module until the dataset object is actually used after importing) could be a solution.

**Comment by mzjp2** [comment]
Just a quick update on this, I have a prototype up and being dogfooded currently, will update here once I get some feedback and make some more progress.

The lazy loading was a good idea and was my initial first thought too, but ended up being a massive pain re: linting/typing/parsing and so I ditched it. Currently going for `try/except`s in the `__init__` files and also doing some refactoring to be able to tell when an import fail because of dependencies missing so we can raise the right error message.

**Comment by mzjp2** [comment]
Hi @Minyus, another update. I'm going to go ahead and close this via https://github.com/quantumblacklabs/kedro/commit/16604ec0203432b9897abb34e3bb4d1c59d1f81d -- you can see the commit for the solution we ended up designing. I think it's an all around win:

* Lets you selectively install dataset dependencies and will let you use a specific dataset within a group without having all other dependencies for that group installed.
* Keeps smart error messages for missing dependencies that you do __need__ to run your pipeline that happens on `config` load and not at runtime of the pipeline itself.

**Comment by Minyus** [comment]
Fair enough. Users can now use `pandas.CSVDataSet` as long as the actual dependency of the DataSet is met. Thanks @mzjp2 !
