### ISSUE TITLE
[KED-1629] Enable caching for all datasets in the `DataCatalog`

### ISSUE THREAD

**Issue by tsanikgr** [quantumblacklabs/kedro#345]
## Description
The `CachedDataset` enables caching of data on memory instead of loading from disk/network after the first load/save, and can save a lot of time if some datasets are loaded multiple times in a single run.

Declaring all datasets in the data catalog as `CachedDatasets` is very verbose, and need manual work to check what is used more than once, so I typically do this in code.

It would be nice if we could enable/disable caching on the `DataCatalog` level.

## Context
Performance and less verbose code.

## Possible Implementation
A possible implementation is presented in #346

**Comment by yetudada** [comment]
As remarked in #346, we'll revisit ideas here when we pick up a design for component-based design for IO.
