### ISSUE TITLE
Provide an ubuntu package

### ISSUE THREAD

**Issue by fkromer** [quantumblacklabs/kedro#347]
## Description

`kedro` allows users to encapsulate projects into `Docker` containers with `kedro-docker`. This means for running a `kedro` project `kedro` and `kedro` plugins are the only Python package dependencies in the OS, user or virtualenv (project) level.

## Context

If `kedro` would be available as package for Ubuntu (snap, flatpak) users would not have to care about this Python runtime dependency at all.

## Possible Implementation

Ubuntu: snap, flatpak

I've created an [experimental snap](https://github.com/fkromer/snap-kedro) which works quite well.

## Possible Alternatives

?

**Comment by 921kiyo** [comment]
@fkromer Thank you for using Kedro and your suggestion/feedback! 

We discussed this option internally just now. We understand that some Python packages with C-extensions might be available in snap. However Kedro is written in pure Python and Pypi is the community standard for a Python package. Therefore, unfortunately, we decided not to publish Kedro on snap. 

Kedro is also in conda btw https://github.com/quantumblacklabs/kedro/issues/313#issuecomment-617753974

I'm closing this issue, but feel free to reopen it if you have further questions.
