### ISSUE TITLE
[KED-1619] logging.yaml configuration reference

### ISSUE THREAD

**Issue by fkromer** [quantumblacklabs/kedro#348]
I'd like to understand what valid entries in `logging.yaml` files are. Searching the kedro docs did not provide the info I was looking for. Is related to https://github.com/quantumblacklabs/kedro/issues/344 .

**Comment by lorenabalan** [comment]
There's an example [in the docs](https://kedro.readthedocs.io/en/stable/08_logging/01_logging.html#logging-for-anyconfig) but this relates to native Python logging, nothing special that Kedro does on top.

**Comment by fkromer** [comment]
@lorenabalan Thanks for the hint. [`anyconfig.validate (data, schema, ac_schema_safe=True, ac_schema_errors=False, **options)`](https://github.com/ssato/python-anyconfig#features) was what I was looking for.
