### ISSUE TITLE
[KED-1619] parameters.yaml configuration reference

### ISSUE THREAD

**Issue by fkromer** [quantumblacklabs/kedro#349]
I'd like to understand what valid entries in `parameters.yaml` files are. Searching the kedro docs did not provide the info I was looking for. Is related to https://github.com/quantumblacklabs/kedro/issues/344 .

**Comment by lorenabalan** [comment]
Hi @fkromer , there's an example [in the user guide](https://jira.quantumblack.com/browse/KED-1615), but it's basically just regular yaml syntax, no extra reserved words. #344 has been further addressed with json schemas to integrate in your IDE to aid the development workflow.

**Comment by lorenabalan** [comment]
Closing this as answered
