### ISSUE TITLE
Kedro viz & kedro run --parallel don't work when working with Spark

### ISSUE THREAD

**Issue by zhangchi1** [quantumblacklabs/kedro#351]
## Description
Kedro viz doesn't work when I follow the [Working with PySpark
](https://kedro.readthedocs.io/en/stable/04_user_guide/09_pyspark.html) tutorial

## Context
I'd like to use Spark session in my nodes to retrieve some data from my snowflake database. So, I followed the tutorial to initialize a SparkSession under `__init__` in `run.py`. It seems like `kedro viz` doesn't like me to initialize a SparkSession  under `__init__`. I have to comment out `self.init_spark_session()` in order to run `kedro viz`. 

Similarly, when I init SparkSession under `__init__` in `run.py`, I got the same error message when I run `kedro run --parallel`.

Where should I do `init_spark_session()` except in the `__init__` under, class `ProjectContext`,in `run.py`?

In addition, I am wondering what is the best practice to pass in a SparkSession in my nodes? What I did is to add a parameter in the `create_pipelines` method: 
`create_pipelines(spark: SparkSession, **kwargs)`

## Steps to Reproduce
1. Follow the [Working with PySpark
](https://kedro.readthedocs.io/en/stable/04_user_guide/09_pyspark.html) tutorial
2. Run `kedro viz` under terminal

## Actual Result
Running `Kedro viz` or `kedro run --parallel` will give us the error message: 
`Error: It appears that you are attempting to reference SparkContext from a broadcast variable, action, or transformation. SparkContext can only be used on the driver, not in code that it run on workers. For more information, see SPARK-5063.`

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.15.9
* Python version used (`python -V`): 3.6.6
* Operating system and version: Mac OS
* Spark: 2.4.4

~~ Thank you so much for the help! Kedro is an awesome ML framework!

**Comment by 921kiyo** [comment]
Hi @zhangchi1 Thank you for opening the issue! We were aware of this issue, and have fixed it in https://github.com/quantumblacklabs/kedro/commit/af39796ac5fa1ed904d9c82cb283e783011344d3 (it is still in dev and we will release it soon. Please have a look at the diff).

You could pass the spark session object from `create_pipelines`. Another way I can think of is to override `_get_feed_dict` from `ProjectContext(KedroContext)` in your `run.py` like below. 

```python
class ProjectContext(KedroContext):
     ....
    def _get_feed_dict(self):
           params = super()._get_feed_dict()
           params['spark_session'] = spark_session
```

This will be passed to your catalog, so you could refer to it in your node like
`node(<node_func>, "spark_session", <output>)`

Hope this helps :)

**Comment by zhangchi1** [comment]
Hello Kiyohito, thank you so much for your reply.

Yes, I pass the spark_session from `create_pipelines(self._spark_session)`. In order to serialize my nodes (I want to run kedro in parallel), I make my node as a class with a `spark_session` field. For example, I do `my_nodes = ClassNode(spark_session)` and `func=my_nodes.my_func`in the pipeline. Do you think that's a good practice?    

Right now, I'm able to run the project in sequential and run `kedro viz` with commented out `self.init_spark_session()`. So is that means I can run both `kedro run --parallel` and `kedro viz` in the next version release?

Again, thank you so much for your help~~

**Comment by 921kiyo** [comment]
I assume you are referring to ParallelRunner? It does not work nicely with Spark, unfortunately, but we just added `ThreadRunner` in https://github.com/quantumblacklabs/kedro/commit/c79c21a50924b2f79f1207de167b27d7c7e8bef0 which would work with SparkDataSet (will be releasing in the next version).

**Comment by zhangchi1** [comment]
Yes, I am talking about `ParallelRunner`. Thanks for pointing me to the updated docs [kedro spark](https://github.com/quantumblacklabs/kedro/commit/af39796ac5fa1ed904d9c82cb283e783011344d3). At least, I can do `kedro run` now~~

**Comment by 921kiyo** [comment]
You are welcome! I'm closing this issue, but feel free to reopen/ask us any more questions (we also have Stackoverflow https://stackoverflow.com/questions/tagged/kedro)!
