### ISSUE TITLE
[KED-1649] Add a decorator for validating inputs other than dataframes

### ISSUE THREAD

**Issue by juan-carlos-calvo** [quantumblacklabs/kedro#356]
## Description
a decorator to validate types and expected properties of inputs other than dataframes (I leave the validation of dataframe expectations to Great Expectations).

## Context
It is very common to pass parameters to a node via a dictionary as in `params` or `params:train_params`. Usually, you would have to validate (inside the node function) that the dictionary has the fields you expect and that its values have the properties you expect. However, a decorator and the specification of a model for the inputs would be a more elegant way to address this scenario.

## Possible Implementation
wrap `validate_arguments` (from pydantic) so that the decorator takes as argument the inputs variables to validate.

**Comment by 921kiyo** [comment]
Thank you for the suggestion! I've logged this and will discuss internally next week. It would be great if you could show a toy example code of how you would apply this decorator (in one node for example). 

> dictionary has the fields you expect

For the dict key, if it doesn't exist, it will simply fail before going to the node function. So I am not sure what you mean by validating it inside the node function. Maybe an example of validating fields and properties using your decorator would be great :)

**Comment by juan-carlos-calvo** [comment]
will do.
