### ISSUE TITLE
IncrementalDataSet partition by strings contains integers

### ISSUE THREAD

**Issue by yzhu32** [quantumblacklabs/kedro#358]
## Description
The IncrementalDataSet feature is great. However, if the partitions are a list of strings with integers: `e.g. ["95/", "950/", "1003/", ]`, given the current `_list_partitions()` implementation, it returns `['1003/', '95/', '950/']`, but ideally it should return `["95/", "950/", "1003/"]` and save `1003/` into the checkpoint.

```
@lru_cache(maxsize=None)
    def _list_partitions(self) -> List[str]:
        checkpoint = self._read_checkpoint()
        checkpoint_path = self._filesystem._strip_protocol(  # pylint: disable=protected-access
            self._checkpoint_config[self._filepath_arg]
        )

        def _is_valid_partition(partition) -> bool:
            if not partition.endswith(self._filename_suffix):
                return False
            if partition == checkpoint_path:
                return False
            if checkpoint is None:
                # nothing was processed yet
                return True
            partition_id = self._path_to_partition(partition)
            return self._comparison_func(partition_id, checkpoint)

        return sorted(
            part
            for part in self._filesystem.find(self._normalized_path, **self._load_args)
            if _is_valid_partition(part)
        )
```

## Context
The current implementation is great if the partitions are strings like timestamp, but not correct for cases string contains integers

## Possible Implementation
Can use `natsort` to solve this kind of issue

## Possible Alternatives
(Optional) Describe any alternative solutions or features you've considered.

**Comment by 921kiyo** [comment]
@yzhu32 Thank you for the suggestion! While the default partition assumes the timestamp, you can also custom it by passing `comparision_func`. See https://kedro.readthedocs.io/en/latest/04_user_guide/08_advanced_io.html?Dataset#special-checkpoint-config-keys

Would that help your use case?

**Comment by yzhu32** [comment]
@921kiyo Thanks! That makes sense.
