### ISSUE TITLE
Flexibility for APIDataSet 

### ISSUE THREAD

**Issue by Minyus** [quantumblacklabs/kedro#362]
## Description
The provided `APIDataSet` allows to use only `text` or `json()` and does not support to get binary contents.

## Context
Getting binary contents such as images, models, and zip files are in demand.

## Possible Implementation
Allow users to specify the attribute to return.

**Comment by mzjp2** [comment]
Hey @Minyus, thanks again for raising this issue and the associated PR. 🙌

We've had a discussion and think that simplifying the interface of the `APIDataSet` is the direction that we're going in by only loading the `response` object and delegating what attributes to fetch from it to the loadee within a `node`. This was done in commit https://github.com/quantumblacklabs/kedro/commit/b2368656bbfc5ee719873c94134ae2df59003ff9

It also helps this dataset remain consistent with some of our others, like the `pillow.ImageDataSet` that returns an `Image` object without providing any kind of attribute fetching on it, which I think should remain out of scope for a dataset class. :)

I'll go ahead and close this and the related PR!

**Comment by Minyus** [comment]
Fair enough. It now can be used to download a binary file. Thanks @mzjp2 !
