### ISSUE TITLE
Standardize legal headers and `LICENSE.md`

### ISSUE THREAD

**Issue by deepyaman** [quantumblacklabs/kedro#366]
## Description
`legal_header.txt` (and the corresponding legal headers on top of source files) has nonstandard indentation on [line 22](https://github.com/quantumblacklabs/kedro/blob/d2d5ca1804d8a5b1d4ea2fe67ac09732e92956dc/legal_header.txt#L22) (middle line below):

```python
# Trademarks or any confusingly similar mark as a trademark for your product,
#     or use the QuantumBlack Trademarks in any other manner that might cause
# confusion in the marketplace, including but not limited to in advertising,
```

Upon further investigation, this line isn't indented in `LICENSE.md`, but the Apache link is: https://github.com/quantumblacklabs/kedro/blob/d2d5ca1804d8a5b1d4ea2fe67ac09732e92956dc/LICENSE.md#L7

## Context
Why is this change important to you? How would you use it? How can it benefit other users?

Other users can sleep easy at night, no longer haunted by the fact that a random line is over-indented.

Issue also applies to https://github.com/quantumblacklabs/kedro-viz, https://github.com/quantumblacklabs/causalnex, etc.

## Possible Implementation
See #365 

## Possible Alternatives
You can still keep `legal_header.txt`, if you foresee it diverging from `LICENSE.md` in the near future. I'd prefer to add it back later, if and when necessary, though.

**Comment by 921kiyo** [comment]
Resolved in https://github.com/quantumblacklabs/kedro/commit/648f8943f3ff40515c23319b335f803fb41afb02 Thank you for your contribution!
