### ISSUE TITLE
"kedro ipython" doesn't leverage ScientificView in PyCharm

### ISSUE THREAD

**Issue by 6Hhcy** [quantumblacklabs/kedro#37]
## Description
I'm working my way through the Kedro tutorial. When I set `df = io.load("foo.csv")` for the iris data, I get the interactive mode in Terminal as expected, however I can't see the contents of the dataframe in PyCharm's data viewer.

Is there a way to tell Kedro to run its IPython mode using the native IPython setup in Pycharm? 

![image](https://user-images.githubusercontent.com/39071791/60224007-17186f00-98c4-11e9-8f6b-4c419c76560b.png)

## Context
Im trying to use the data viewer in Pycharm's ScientificView

## Steps to Reproduce

1. Install Pycharm Pro
2. Install sample project
3. run `kedro ipython`
4. Load a sample dataset `df = io.load("foo.csv")`

## Expected Result
I would like to have ScientificView populated with the contents of the Dataframe

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used 0.14.2
* Python version used 3.6.8
* Operating system and version: Win10

**Comment by idanov** [comment]
Hi @6Hhcy, thank you very much for reporting this. We've added the issue on our internal backlog and will try to reproduce the issue, and eventually resolve it. We might need to come back to you with some questions if we can't reproduce it, would you be open to add more details upon request?

**Comment by 6Hhcy** [comment]
sure

**Comment by tsanikgr** [comment]
Hi @6Hhcy 

As far as I am aware, to get PyCharm's scientific view you have to be running your code using PyCharm's run configurations or jupyter functionality, and _not_ within PyCharm's terminal.

`kedro ipython` is the same is `ipython`, it just also runs the startup script in `<project>/.ipython/profile_default/startup/00-kedro-init.py`. Running `ipython` in PyCharm's terminal won't give you the scientific view AFAIK.


To get PyCharm Pro's scientific view working with `kedro`, maybe the best way is to run `kedro jupyter notebook` in a terminal, then copy the server URL and configure PyCharm to use it.

<img width="2032" alt="Screenshot 2019-07-03 at 12 13 13" src="https://user-images.githubusercontent.com/3808292/60587401-3fa0dd00-9d8c-11e9-89d1-f5dbf77418db.png">

**Comment by tsanikgr** [comment]
Hello again,

The above solution is not giving you access to the SciView, but the below will.

You 'll have to copy paste the contents of `<project>/.ipython/profile_default/startup/00-kedro-init.py` in "Starting script" (as shown below). You 'll also have to change the 3rd from the last line to

```python
proj_dir = os.path.abspath(os.path.join(os.path.dirname('.')))
```

I tried making this work by setting `PYTHONPATH` in the environment variables but it does not seem to work.

<img width="1920" alt="Screenshot 2019-07-03 at 14 39 30" src="https://user-images.githubusercontent.com/3808292/60596302-a6c88c80-9da0-11e9-869c-bd9acb809904.png">

**Comment by 6Hhcy** [comment]
Thank you for looking into it. On the sample Kedro project (where my project is called "cd") I get the following error:

```Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 7.5.0
2019-07-11 10:16:31,764 - root - ERROR - Kedro appears not to be installed in your current environment.
Traceback (most recent call last):
  File "C:\Users\micro\Miniconda3\envs\MyEnv\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-9086caca7945>", line 69, in <module>
    reload_kedro()
  File "<C:\Users\micro\Miniconda3\envs\MyEnv\lib\site-packages\decorator.py:decorator-gen-117>", line 2, in reload_kedro
  File "C:\Users\micro\Miniconda3\envs\MyEnv\lib\site-packages\IPython\core\magic.py", line 220, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)
  File "<ipython-input-1-9086caca7945>", line 59, in reload_kedro
    raise err
  File "<ipython-input-1-9086caca7945>", line 22, in reload_kedro
    from cd.run import create_catalog, get_config
  File "C:\Program Files\JetBrains\PyCharm 2019.1.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'cd'```

**Comment by 6Hhcy** [comment]
Having said that, the command: `kedro jupyter notebook` executed in the top level directory of the project does work...
