### ISSUE TITLE
[KED-1677] Allow easily extending built-in cli commands from plugins

### ISSUE THREAD

**Issue by tsanikgr** [quantumblacklabs/kedro#382]
## Description
I would love to see something similar to what pytest does. If I install `pytest-xdist`, a new option `-n` is available which allows me to run my tests in parallel. Eg `pytest -n 8` would run my tests in 8 processes.

Would be could if we could do this with `kedro run`, e.g. `kedro run --my_option` without having to touch the `kedro_cli.py` file.

**Comment by yetudada** [comment]
You'll be excited to note that we have addressed this feature in https://github.com/quantumblacklabs/kedro/commit/794a6ad1e2066c4eac414d05c431b96ba4fce57f. I'll go ahead and close this. Thank you so much for reporting this @tsanikgr!
