### ISSUE TITLE
Integration of requirement management tool

### ISSUE THREAD

**Issue by fkromer** [quantumblacklabs/kedro#389]
## Description

As a data Scientist/consultant I want to be able to deliver requirements and related tests to stakeholders/customers.

## Context

Stakeholders/customers do not care about  API documentation. The Sphinx documentation is suboptimal as Delivery artifact. Instead they are interested in the high level functionality implemented and if there are corresponding tests.

## Possible Implementation

doorstop seems to be the most feature rich package implementing requirement management right now and would play well with kedro's VCS oriented lightweight approach .

## Possible Alternatives

?

**Comment by lorenabalan** [comment]
Hi @fkromer! Inside a kedro project, users are currently able to manage their requirements using [pip-tools](https://pypi.org/project/pip-tools/), via `kedro build-reqs`, which does a pretty reasonable job. However users are still free to override the behaviour of the CLI command to use something else, in the `kedro_cli.py` file of their project. 

We don't want to impose a specific tool to use in a space that there is no "clear" winner yet (although Poetry is gaining ground), and we believe there's value in leaving it open for now and leave it to the users to customise their own projects as they see fit. To quote @limdauto, generally we are hesitant to bring too many things in-house and would love to see an ecosystem forming around Kedro. It could be a separate plugin?

**Comment by fkromer** [comment]
@lorenabalan Actually it is not about dependency requirements, but stakeholder requirements. However I think you're right. Not every user will need this functionality. It should be placed into a separate plugin.
