### ISSUE TITLE
Question: Unconventional Python package dependency management

### ISSUE THREAD

**Issue by fkromer** [quantumblacklabs/kedro#391]
I'm writing a plugin for Kedro right now. In the Python world one usually uses Pipenv or Poetry for package dependency management. I've never seen a project where package dependency management has been done manually. Both tools are capable of exporting production and test dependencies into `requirements.txt` and `test_requirements.txt` respectively. Is there a reason why you don't use Pipenv or Poetry? What kind of dependency management is the recommendation for plugin contributers?

**Comment by lorenabalan** [comment]
Hi @fkromer , great to hear you're developing a plugin! Would be great to have it featured in our community-developed plugins list.

We have actually taken a stab at moving to Poetry about 3 months ago, but it created more problems than it solved, so we decided to park it for the time being. The main packaging offenders were the `cookiecutter` template and the built documentation.

However you are welcome to use whichever dependency management system you prefer to develop the plugin, as long as it's published on PyPI in the end. Is there any problem that the dependency management system Kedro uses internally is causing you in the plugin development process?

**Comment by fkromer** [comment]
> Hi @fkromer , great to hear you're developing a plugin! Would be great to have it featured in our list of community-developed plugins.

@lorenabalan The plugin under development is [kedro-doorstop](https://github.com/fkromer/kedro-doorstop). A package dependency is LGPL-licensed. Is it suitable for the list given this license?

> We have actually taken a stab at moving to Poetry about 3 months ago, but it created more problems than it solved, so we decided to park it for the time being. The main packaging offenders were the cookiecutter template and the built documentation.

What's the limitation which blocked you from migrating?

> However you are welcome to use whichever dependency management system you prefer to develop the plugin, as long as it's published on PyPI in the end. Is there any problem that the dependency management system Kedro uses internally is causing you in the plugin development process?

I use Poetry for package dependency management. As it [is capable of exporting `requirements.txt` and `test_requirements.txt` files in the required format](https://github.com/fkromer/kedro-doorstop/blob/master/Makefile#L21) I'm totally fine with the Kedro way of package management.

**Comment by lorenabalan** [comment]
To quote from some of the findings at the time:

> - Installing Kedro from source (`poetry install`) fails because cookiecutter template is recognised by poetry as a subpackage (similar issue - https://github.com/python-poetry/poetry/issues/1492). The workaround proposed in the issue may work, however it would look quite hacky and ugly.
> - Packaging built docs from `kedro/html` into the wheel required yet another workaround - the location had to be temporarily excluded from .gitignore, otherwise poetry does not include it in `package_data` when generating `setup.py`

Licenses don't interfere with us simply linking to plugins [here](https://kedro.readthedocs.io/en/stable/04_user_guide/10_developing_plugins.html#community-developed-plugins). Please feel free to raise a PR when you're happy with it.
I'll go ahead and close this issue as answered.

**Comment by Kastakin** [comment]
Really hoping for Poetry migration aswell!
