### ISSUE TITLE
[KED-1834] Notify on new versions

### ISSUE THREAD

**Issue by tsanikgr** [quantumblacklabs/kedro#393]
## Description
The github cli notifies on new versions as follows.
Would be nice if the `kedro` cli did the same :)

<img width="385" alt="Screenshot 2020-05-30 at 16 58 21" src="https://user-images.githubusercontent.com/3808292/83330308-c9a43f00-a296-11ea-8471-65411673e880.png">

**Comment by yetudada** [comment]
We would have loved to have done this but we suspect that it might slow down our CLI (even more). We'll park this one for now, unless you have any more ideas for it?
