### ISSUE TITLE
How do I fill the credentials from environment variables

### ISSUE THREAD

**Issue by HugoPerrier** [quantumblacklabs/kedro#403]
## Issue description
I would like to set placeholders in my credential files and have them filled with environment variables.
Exemple of **credentials.yml** file (in this case connection to a postgre database):
```
dev_sql:
  con: "postgresql://${USERNAME}:${PASSWORD}@${SERVERNAME}:${PORT}/${NAME}"
```

## My solution (thanks DmitriiDeriabinQB and [documentation](https://kedro.readthedocs.io/en/stable/kedro.config.TemplatedConfigLoader.html#kedro.config.TemplatedConfigLoader)):

Edit the run.py file to :

1. Create a class inheriting from KedroContext (the default ProjectContext works fine)
2. If you don't use the ProjectContext class, adapt the .kedro.yml file
3. Override the KedroContext method `_create_config_loader`
4. Use a TemplatedConfigLoader instead of a ConfigLoader and pass the environment variable dict as `globals_dict` argument

My run.py file looks as follows:
```
class ProjectContext(KedroContext):
    """Users can override the remaining methods from the parent class here,
    or create new ones (e.g. as required by plugins)
    """

    project_name = "my_project"
    project_version = "0.16.1"
    package_name = "my_package"

    def _get_pipelines(self) -> Dict[str, Pipeline]:
        return create_pipelines()

    # Get credentials from environment variables
    def _create_config_loader(self, conf_paths):
        return TemplatedConfigLoader(conf_paths, globals_dict=os.environ)
```

_Originally posted by @HugoPerrier in https://github.com/quantumblacklabs/kedro/issues/49#issuecomment-637656025_

**Comment by mzjp2** [comment]
Hey @HugoPerrier -- thanks for creating this issue. It looks like you've gotten it solved with help from Dmitrii and have been kind enough to post your solution so others can benefit from it. I'll go ahead and close this as done. Thank you!

**Comment by bensdm** [comment]
Hi, i am trying to find the cleanest way to provide credentials as input to a node. Not sure if this is the best place to ask the question. Is there a way to load credentials.yml in the dataCatalog like the parameters.yml. Thanks

**Comment by hugo-quantmetry** [comment]
### UPDATE for kedro 0.18
It seems like many people are still reading this issues so I'll post an update.

The solution proposed above is obsolete.
To inject credentials through environment variables, I suggest the following.

Modify the file _project_name/src/package_name/settings.py_ as follows :

```
# Class that manages how configuration is loaded.
from kedro.config import TemplatedConfigLoader
import os
CONFIG_LOADER_CLASS = TemplatedConfigLoader
# Keyword arguments to pass to the `CONFIG_LOADER_CLASS` constructor.
CONFIG_LOADER_ARGS = {
#    "globals_pattern": "*globals.yml",
    "globals_dict": os.environ,
}
```

Then you will be able to use environment variables in your conf files.   

Ex: You can set environment variables _MY_LOGIN_ and _MY_PASSWORD_.
Modify the file _project_name/conf/base/parameters.py_ as follows :
```
my_login : ${MY_LOGIN}
my_password : ${MY_PASSWORD}
```
And your kedro parameters _params:my_login_ and _params:my_password_ will take the value of the corresponding environment variables.

### Explanation
By default, kedro uses a regular _ConfigLoader_ object to load the conf files.
The settings file let's you change from a regular _ConfigLoader_ class to a _TemplatedConfigLoader_ class.
The _TemplatedConfigLoader_ allows the usage of variables in the conf files with the syntax ${MY_VARIABLE}.
The variables that can be used in the conf can be specified in two ways:

- **global_patterns** : Variables specified in a yaml file "globals.yml" (ex: _project_name/conf/base/globals.yml_)
- **global_dict** : Variable specified as a python dict-like object. 

By passing _os.environ_ for the _global_dict_ argument, environment variables are made available :)

**Comment by schoobani** [comment]
How can we access `os.environ` when calling a custom dataset?

**Comment by noklam** [comment]
@schoobani Hey! Sorry that you have to find this old issue. This should be the most up-to-date way to do so. https://docs.kedro.org/en/stable/configuration/advanced_configuration.html#how-to-load-credentials-through-environment-variables
