### ISSUE TITLE
Kedro user feedback sessions! 👋

### ISSUE THREAD

**Issue by GabrielComymQB** [quantumblacklabs/kedro#408]
## Description
We want to bring the open-source community closer to the design process!
Your feedback is essential to making Kedro even better! To this end, we'll be running regular feedback sessions with our core and most enthusiastic users.

In the sessions, we'll learn how you've been using Kedro, review feature designs and bounce some ideas. We're looking forward to making Kedro better with you :)

## Sign-up
Sign-up for a user feedback session using this [**link**](https://bit.ly/kedro-feedback). The link will direct you to a questionnaire that will allow you to enter your contact details so that we can reach to you to arrange a Kedro feedback session.

**Comment by datajoely** [comment]
I'm closing this since [Discord](https://discord.gg/akJDeVaxnB) is now our best way to engage! [Sign up here](https://discord.gg/akJDeVaxnB)!
