### ISSUE TITLE
[KED-1749] `fsspec.filesystem` doesn't (reliably) expose `pathsep` property

### ISSUE THREAD

**Issue by saludes** [quantumblacklabs/kedro#411]
## Description
Cannot save a list of  figures

## Steps to Reproduce
On `kedro ipython`:
```
from kedro.extras.datasets.matplotlib import MatplotlibWriter
import matplotlib.pyplot as plt
lp = MatplotlibWriter(filepath='mab_list')
plots = []
for i in range(5):
    plots.append(plt.figure())
    plt.plot([1,2,3], [4,5,6+i])
    plt.close()
lp.save(plots)
```

## Expected Result
Create a folder named *mab_list* with 5 PNG files.

## Actual Result

```
DataSetError: Failed while saving data to data set MatplotlibWriter(filepath=mab_list, protocol=file).
'LocalFileSystem' object has no attribute 'pathsep'
```

## Fix
I just changed `.pathsep` by `.sep` in line:
https://github.com/quantumblacklabs/kedro/blob/32180557299a196b82a7d1ad7bf93d94627e1a3e/kedro/extras/datasets/matplotlib/matplotlib_writer.py#L169

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): Version: 0.16.1
* Python version used (`python -V`): Python 3.8.3
* Operating system and version: mcOS Catalina 10.15.5

**Comment by saludes** [comment]
… and also in https://github.com/quantumblacklabs/kedro/blob/32180557299a196b82a7d1ad7bf93d94627e1a3e/kedro/extras/datasets/matplotlib/matplotlib_writer.py#L176

**Comment by ssYkse** [comment]
I was just about to report the same bug :)

**Comment by DmitriiDeriabinQB** [comment]
@saludes @ssYkse thank you both for reporting this! We confirm that we aware of that and the fix will be available in the next release.
Surprisingly, `pathsep` property 'magically' appears in the filesystem object if you do `pip install "kedro[pandas]==0.16.2"` beforehand. Seems that it relies on _some_ dependency inside our `pandas` extra. So this might be the interim solution while the fix is not yet available.

**Comment by DmitriiDeriabinQB** [comment]
Fixed in a095523a180411683c7b62d966725a871746e342

**Comment by saludes** [comment]
Just wanted to remark that i'm not using Windows (but OSX).

**Comment by DmitriiDeriabinQB** [comment]
@saludes Yes, that was clear from your comment. Let me make the issue title less confusing 🙂

**Comment by lorenabalan** [comment]
Closing this as resolved, will be be available in the next release. :)
