### ISSUE TITLE
[KED-1798] AbstractDataSet.__str__ excludes zero-valued integers

### ISSUE THREAD

**Issue by seeM** [quantumblacklabs/kedro#413]
_(Apologies for deviating from the template, but this is quite straightforward and probably doesn't need all of those sections)_

### Example

```pycon
>>> from kedro.io import AbstractDataSet
>>> class MyDataSet(AbstractDataSet):
...     def __init__(self, var):
...         self.var = var
...     def _describe(self):
...         return dict(var=self.var)
...     def _load(self):
...         pass
...     def _save(self, data):
...         pass
...
>>> str(MyDataSet(1))
'MyDataSet(var=1)'
>>> str(MyDataSet(0))
'MyDataSet()'
```

`var` isn't displayed when its value is zero, even though that could be a meaningful thing to display. This is due to the `if value` filter below:

https://github.com/quantumblacklabs/kedro/blob/c141467739d696c1f69dfd51be33b8d02d45b501/kedro/io/core.py#L266

Is falsiness an appropriate check, or should numeric values be included even when they're zero?

**Comment by DmitriiDeriabinQB** [comment]
Resolved in #418
