### ISSUE TITLE
[KED-519] Support template variables in configuration files

### ISSUE THREAD

**Issue by JoostDuisters** [quantumblacklabs/kedro#42]
## Description

As a user of kedro I would like to be able to parameterize/template my config files, in order to be able to change configurations of lots of datasets, accross config files, by changing only one variable in a centralized place.

This would allow me to for instance:
 * Create flexible folderpaths for all (or a large subset of) Datasets, allowing me to
    * Quickly switch root directories from a dev/test environment to a prod environment 
    * Work with data iterations 
    * Have pipelines for different countries run using the same config files
 * Reduce the size of my config files by templating common parts (for instance I could parameterize the 'save_args' or 'load_args' of a Spark Dataset)

## Context
User stories/ideas from current users have mainly focussed on the templating of the folderpath. 

Some more advanced ideas have inlcuded:
 *  Allowing for boolean logic inside the template and the values to allow for easier switching (e.g. one could have a parameter dev=True, and when this gets switched to False, all the conifg that depends on this boolean switches. This would be usefull if for instance both the folderpath and the load_args change when running in dev vs prod, in this case only one parameter would have to be changed)
 *  Allowing for templating inside the template values. This would reduce the chance of errors in complex config folders, that all have a similar root but might have multiple parameters in them. Example:
```
	raw_employees:
	  type: kedro.contrib.io.pyspark.SparkDataSet
	  filepath: s3a://${s3_bucket}/${country}/${raw_folder}/employees.csv
	  file_format: csv
	  load_args:
	    delimiter: ";"
	    header: true
```

with values.yml:

```
	s3_bucket: 'bucketname'
	country: 'uk'
	raw_folder: '00_raw'
```

you could have:

```
	raw_employees:
	  type: kedro.contrib.io.pyspark.SparkDataSet
	  filepath: ${raw_root}/employees.csv
	  file_format: csv
	  load_args:
	    delimiter: ";"
	    header: true
```
	
with values.yml:

```
	s3_bucket: 'bucketname'
	country: 'uk'
	raw_folder: '00_raw'
	raw_root: s3a://${s3_bucket}/${country}/${raw_folder}
```

Lots of people I spoke to have created their own version of this on kedro projects (mostly the simple one without templating inside the values.yml). It would be good to make a solution for it in the kedro core, incorporating best-practices and unit-tests.

## Possible Implementation
You can make a class that inherits from ConfigLoader with an extra class called resolve that is similar to the .get method with the only difference being that it applies the default value dict to config before returning it. 

One way this could be done is using the string Template class in python. Otherwise, some logic needs to be written to replace template variables with defaults.

## Checklist
Include labels so that we can categorise your issue:

- [ ] Add a "Component" label to the issue
- [ ] Add a "Priority" label to the issue

**Comment by DmitriiDeriabinQB** [comment]
Resolved in #41
