### ISSUE TITLE
GitHub Pull Request Template has an incorrect Contributing Link

### ISSUE THREAD

**Issue by tamsanh** [quantumblacklabs/kedro#422]
## Description
Link points to "https://github.com/quantumblacklabs/kedro/CONTRIBUTING.md"
When it should point to "https://github.com/quantumblacklabs/kedro/blob/master/CONTRIBUTING.md" instead.

## Context
Was just trying to look at the contributing.md

## Steps to Reproduce
1. Open a pull request
2. click on the 'contributing' link in "Read the contributing guidelines"

## Expected Result
Should have seen the CONTRIBUTING.md file.

## Actual Result
Got a "Not Found" error.

## Your Environment
Web

**Comment by mzjp2** [comment]
The `README.md` link is also broken (in the PR) -- can see why. Will push a fix, thank you! :)

**Comment by mzjp2** [comment]
Fixed, the commit should be synced anytime now! :)
