### ISSUE TITLE
Memory leak with MatplotLibWriter

### ISSUE THREAD

**Issue by williamashfordQB** [quantumblacklabs/kedro#423]
## Description
When saving a matplotlib figure, the writer doesn't close the figure afterwards, resulting in a memory leak for applications which write many plots. Users are prompted with the below warning:

```
2020-06-25 23:30:38,615 - py.warnings - WARNING - More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory
. (To control this warning, see the rcParam `figure.max_open_warning`).
```

## Context
This bug presented itself in a Kedro project with a very large number of MatplotLib datasets used for BI/Translator interpretation. 

## Steps to Reproduce
1. Create a kedro node that produces 20+ plots. 
2. Run the node

## Expected Result
The MatplotLibWriter should close the figures. 

## Actual Result
The MatplotLibWriter doesn't close the figures. 

```
2020-06-25 23:30:38,615 - py.warnings - WARNING - More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory
. (To control this warning, see the rcParam `figure.max_open_warning`).
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.16.1
* Python version used (`python -V`): 3.6.10
* Operating system and version: MacOS and Debian GNU/Linux

## Suggested fix

Ammend the save method in the MatplotLibWriter:

```
def _save(self, data: Union[figure, List[figure], Dict[str, figure]]) -> None:
        save_path = self._get_save_path()

        if isinstance(data, list):
            for index, plot in enumerate(data):
                full_key_path = get_filepath_str(
                    save_path / f"{index}.png", self._protocol
                )
                self._save_to_fs(full_key_path=full_key_path, plot=plot)
                plot.close()           # < ---- Closing the plot after saving should release the memory

        elif isinstance(data, dict):
            for plot_name, plot in data.items():
                full_key_path = get_filepath_str(save_path / plot_name, self._protocol)
                self._save_to_fs(full_key_path=full_key_path, plot=plot)
                plot.close() 

        else:
            full_key_path = get_filepath_str(save_path, self._protocol)
            self._save_to_fs(full_key_path=full_key_path, plot=data)
            data.close()

        self._invalidate_cache()
```

**Comment by 921kiyo** [comment]
Thank you for reporting this! The original implementation assumes that users call `plt.close()` windows themselves before saving 
https://kedro.readthedocs.io/en/latest/kedro.extras.datasets.matplotlib.MatplotlibWriter.html?kedro.extras.datasets.matplotlib.MatplotlibWriter

But I think the dataset should also check it (and close them) in cases users forget to close them. We will improve handling plot figures to mitigate memory leak :)
