### ISSUE TITLE
How to specify dtypes in catalog for pandas.CSVDataSet

### ISSUE THREAD

**Issue by widovanheemstra** [quantumblacklabs/kedro#428]
## Load CSV data with forced types
I have a CSV dataset with one column containing integers. They get loaded as floats. In Pandas you can specify this with the dtype parameter containing a dict. When I try this in the catalog yaml the np.int32 is not recognised and results in an error.

How can I specify the correct types for loading CSV data?

**Comment by deepyaman** [comment]
@widovanheemstra You can't specify `np.int32` per se in the catalog, as it's an object that the YAML parser won't understand--it sees it as a string. However, you can just use `int32`, a string that will get interpreted as the same dtype.

```python
>>> import numpy as np
>>> import pandas as pd
>>> 
>>> df = pd.read_csv("blah.csv", dtype={"blah": np.int32, "bleh": "int32", "bloo": "int"})
>>> df
   blah  bleh  bloo
0     1     2     3
>>> df.dtypes
blah    int32
bleh    int32
bloo    int64
dtype: object
>>> 
```

**Comment by limdauto** [comment]
Hi @widovanheemstra, I'm closing this as @deepyaman' suggestion to use "int32" should work in the catalog YAML. Please do re-open the issue if that doesn't fix your problem.
