### ISSUE TITLE
[KED-1853] GCP Datastore support

### ISSUE THREAD

**Issue by f-istvan** [quantumblacklabs/kedro#429]
## Description
Add data connector for GCP Datastore.
Data connectors for Google Cloud Storage and Google Big Query was implemented as part of [KED-928] https://github.com/quantumblacklabs/kedro/issues/11
However, there is no support for GCP Datastore at the moment.

## Context
This feature would increase the possibilities of using GCP services.

**Comment by lorenabalan** [comment]
Hi @f-istvan , thank you for raising this issue. We encourage users to [write their own custom datasets](https://kedro.readthedocs.io/en/stable/03_tutorial/03_set_up_data.html#creating-custom-datasets) as per their needs, and it should be fairly straightforward. We welcome contributions in this space!
I've tagged it with an internal ticket number for tracking purposes but it's likely, given our current roadmap and priorities, it will not be immediately looked into unless we see it gaining traction/interest from more users.

**Comment by vhawk19** [comment]
Hey @laisbsc, are there any resources or related PRs where I could read upon similar data connector additions? I'd love to contribute if this is open for contribution.
