### ISSUE TITLE
[KED-1852] Customizable Run Record Data

### ISSUE THREAD

**Issue by tamsanh** [quantumblacklabs/kedro#431]
## Description
The problem I'm having is I'm trying to grab some extra data inside of my custom hooks.

I just want to grab the `project_name` and a custom `user_id` variable from the environment.

One simple way to do this would be to pass these values through the run_params object that gets put into the hook calls.

## Context
This will allow me to create some advanced hooks that do monitoring inside of `after_pipeline_run` and `before_pipeline_run`.

Considering the relatively limited amount of data that hooks get access to, it gets a bit hard.

## Possible Implementation

It would be great if the `record_data` object inside of `context.py` could be exposed as an instance function. That would make it far easier to override a custom implementation of it.

```python
class KedroContext(abc.ABC):
  def _generate_run_params(
      run_id:str,
      project_path:Path,
      env:str,
      kedro_version:str,
      tags:Iterable[str,
      from_nodes:Iterable[str,
      to_nodes:Iterable[str,
      node_names:Iterable[str,
      from_inputs:Iterable[str,
      load_versions: Dict:[str, str],
      pipeline_name:str,
      extra_params: Dict[str, Any],
  ):
        record_data = {
        "run_id": run_id,
        "project_path": project_path,
        "env": env,
        "kedro_version": project_version,
        "tags": tags,
        "from_nodes": from_nodes,
        "to_nodes": to_nodes,
        "node_names": node_names,
        "from_inputs": from_inputs,
        "load_versions": load_versions,
        "pipeline_name": pipeline_name,
        "extra_params": extra_params,
    }
    return record_data
  ...
  def _run(...):
    ...
    record_data = self._generate_run_params(
      run_id=run_id,
      project_path=str(self.project_path),
      env=self.env,
      kedro_version=self.project_version,
      tags=tags,
      from_nodes=from_nodes,
      to_nodes=to_nodes,
      node_names=node_names,
      from_inputs=from_inputs,
      load_versions=load_versions,
      pipeline_name=pipeline_name,
      extra_params=self._extra_params,
    )
    ...
    self._hook_manager.hook.before_pipeline_run(
      run_params=record_data, pipeline=filtered_pipeline, catalog=catalog
    )
    ...
```

## Possible Alternatives
Enforcing the record data dict with a `class` to require `run_id` and other necessary variables.

**Comment by lorenabalan** [comment]
Thanks @tamsanh this sounds interesting. Tagged it with our internal ticket number for tracking, I know there have been conversations around this already so we might be able to look into this in the near future.

**Comment by lorenabalan** [comment]
Hi @tamsanh , starting Kedro 0.16.5 you'll be able to fetch static information like `project_name` using [`get_static_project_data()`](https://github.com/quantumblacklabs/kedro/blob/8e6e8b2d2076a10ac5aa8fbd539fc759a1440647/kedro/framework/context/context.py#L796). Another alternative, if it's related to runtime CLI arguments, is to use `click.get_current_context()`, like we do [here](https://github.com/quantumblacklabs/kedro/blob/8e6e8b2d2076a10ac5aa8fbd539fc759a1440647/kedro/framework/session/session.py#L157).
Would this be enough for your use case?

**Comment by lorenabalan** [comment]
Closing this as answered, please feel free to re-raise/raise new issue if your use case is still not satisfied.
