### ISSUE TITLE
Too Many config files

### ISSUE THREAD

**Issue by WaylonWalker** [quantumblacklabs/kedro#439]
## Description

Kedro implements its own proprietary `.kedro.yml` config file.  This is great to have a place to configure the project, but these files can really add up.  Other python libraries/tools,  such as mypy and flake8, allow multiple config file options.  They typically set up proprietary config file locations but also allow for generic options like `setup.cfg` or `pyproject.toml` to be used to consolidate tooling config in one place.

[mypy config file docs](https://mypy.readthedocs.io/en/stable/config_file.html)
[flake8 config file docs](https://flake8.pycqa.org/en/latest/user/configuration.html#configuration-locations)

## Possible Implementation
_setup.cfg_

Follow suit of other libraries for config resolution.  Look for `kedro.yml` then `.kedro.yml`, then look for a kedro key in `setup.cfg`, then look for a key in `pyproject.toml`

**Comment by DmitriiDeriabinQB** [comment]
Hi @WaylonWalker, thanks for raising this! This is a valid point, I will add it to the technical discussion.

**Comment by andrii-ivaniuk** [comment]
Hi @WaylonWalker,
Thanks for raising this issue. Kedro was extended and now it is possible to configure it via `pyproject.toml`. All the Kedro-related parameters should be provided under `[tool.kedro]` section.

In general, Kedro will try to read `.kedro.yml` file. If it doesn't exist, it will read `pyproject.toml`.

These changes are available in 69c1d1cc4d2e6f51d72fc008a9a972cca13d2857 commit.

**Comment by WaylonWalker** [comment]
Awesome!!  Can't wait to see `16.5` released.
