### ISSUE TITLE
Allow nodes to have no inputs defined

### ISSUE THREAD

**Issue by WaylonWalker** [quantumblacklabs/kedro#444]
## Description

When incorporating kedro in with existing libraries designed to fetch datasets similar to [pandas-datareader](https://pandas-datareader.readthedocs.io/en/latest/) its frustrating that I need to setup a `dummy` dataset to pass in even though it is not used.

## Context

I have existing libraries that I use daily that fetch data for me with a single function.  These functions tie into kedro extremely well, except for functions that do not require input.

This example from the first page of the [pandas-datareader](https://pandas-datareader.readthedocs.io/en/latest/) docs is a great example of what I am trying to do.  This function returns 5-years of 10-year constant maturity yields on U.S. government bonds with a single keyword argument no data input required.

``` python
import pandas_datareader as pdr
pdr.get_data_fred('GS10')
```

## Possible Implementation
Allow for `inputs=None`  currently kedro checks for None and throws an error.

https://github.com/quantumblacklabs/kedro/blob/master/kedro/pipeline/node.py#L553-L557

## Possible Alternatives

If the above is desired by other use cases.  The error could be toggled off with a configuration such as `strict_node_input`.

**Comment by 921kiyo** [comment]
Hi @WaylonWalker Thank you for reporting!

Kedro node allows `None` inputs (see https://github.com/quantumblacklabs/kedro/blob/master/kedro/pipeline/node.py#L48). 

You can have `node(func, inputs=None, output="something")` or `node(func, inputs="something", output=None)`, but cannot have `node(func, inputs=None, output=None)`. 

Maybe it would be helpful if you could paste the actual error stack in here :)

**Comment by WaylonWalker** [comment]
Wow this one got stale on me.  I just updated some of my pipelines that needed to use None.  Thanks for the feedback.
