### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by yetudada** [quantumblacklabs/kedro#447]
## Description

- We need your help with fixing a broken link in our documentation
- Follow the [markdown syntax for links](https://guides.github.com/features/mastering-markdown/) to fix this problem
- A picture of the affects area is below, and can be found in [this section of our docs](https://github.com/quantumblacklabs/kedro/blob/master/docs/source/01_introduction/01_introduction.md)

![Screenshot 2020-07-24 at 09 28 32](https://user-images.githubusercontent.com/43755008/88373629-146e9e80-cd90-11ea-9d60-900015528405.png)

**Comment by vjkr** [comment]
i will try this, :)

**Comment by stichbury** [comment]
We spotted this in the Kedro team too! It'll be fixed in the next few days. How embarassing that it's on the front page of the docs :blush:
