### ISSUE TITLE
Remove image description text

### ISSUE THREAD

**Issue by yetudada** [quantumblacklabs/kedro#448]
## Description
- We struggle with how our docs render image description text and often have to include images by doing `![](/images/logo.png)` instead of `![GitHub Logo](/images/logo.png)`
- You need to remove the image description text from [this](https://github.com/quantumblacklabs/kedro/blob/master/docs/source/02_get_started/02_install.md#verify-a-successful-installation) and [this](https://kedro.readthedocs.io/en/latest/03_tutorial/01_spaceflights_tutorial.html#kedro-project-development-workflow) sections in our documentation

### Section 1
<img width="799" alt="Screenshot 2020-07-24 at 09 38 20" src="https://user-images.githubusercontent.com/43755008/88374363-8bf0fd80-cd91-11ea-9f29-f4d68fc031a1.png">

### Section 2
<img width="792" alt="Screenshot 2020-07-24 at 09 38 34" src="https://user-images.githubusercontent.com/43755008/88374381-94e1cf00-cd91-11ea-92c5-d67932a4f43a.png">

**Comment by vjkr** [comment]
I will try to work on this :):)

**Comment by yetudada** [comment]
This work is picked up in #454
