### ISSUE TITLE
Add `json.JSONDataSet` to list of Versioned DataSets

### ISSUE THREAD

**Issue by yetudada** [quantumblacklabs/kedro#451]
## Description
- We struggle to keep our list of versioned datasets up to date because manually append this list
- Recently, we added a new `kedro.extras.datasets.json.JSONDataSet` 
- You just need to add this dataset as a new bullet to this list 

## Expected Result
- The list of supported datasets should include `kedro.extras.datasets.json.JSONDataSet` as a new bullet

**Comment by vjkr** [comment]
I will give a try

**Comment by yetudada** [comment]
Sorry about that @vjkr! It's here: https://github.com/quantumblacklabs/kedro/blob/master/docs/source/05_data/02_kedro_io.md#supported-datasets
