### ISSUE TITLE
Docker image for Kedro build tools

### ISSUE THREAD

**Issue by evanmiller29** [quantumblacklabs/kedro#46]
## Description
Not all developers have access to Linux environments.

## Context
A docker image that contains all the tools required would enable any developer to contribute and test on the same environment that the core development team. 

## Possible Implementation
The addition of a DockerFile/docker-compose.yml to contrib. 

I currently have a bare bones implementation working that runs the tests ([here](https://github.com/evanmiller29/kedro_testing_docker)) but it would need more work to implement it with the current kedro structure.

**Comment by yetudada** [comment]
@evanmiller29 We might have this solved for you. Please check out our recently released plugin, [`kedro-docker`](https://github.com/quantumblacklabs/kedro-docker).
