### ISSUE TITLE
Contributing.md - add info on running tests excluding spark related tests

### ISSUE THREAD

**Issue by sebastianbertoli** [quantumblacklabs/kedro#465]
## Description
I would propose adding a one-liner to [First time one off](https://github.com/quantumblacklabs/kedro/blob/master/CONTRIBUTING.md#first-time-one-off) saying that if there are issues with the tests relating to the Spark functionality of Kedro one can run the test-suite excluding Spark related tests with the command `make test-no-spark`.

## Context
I think it would make it easier for people to get started and make new contributors aware that they could be running into issues with Spark. Furthermore, it would also save them some time. 

## Possible Implementation
I could add a sentence to the documentation. Along the lines of:

> If the Spark related tests are failing, and you are not planning to work on those features the following command will exclude them from being tested:
> `make test-no-spark`

## Possible Alternatives
Alternatively, we could add steps to the guide / setup scripts so that those tests succeed.

**Comment by limdauto** [comment]
@sebastianbertoli thank you for your suggestion. A PR is very welcome for this.

**Comment by 921kiyo** [comment]
Addressed in https://github.com/quantumblacklabs/kedro/pull/485 Thank you for your contribution!
