### ISSUE TITLE
[KED-922] IO Dataset class to load and save feather files

### ISSUE THREAD

**Issue by mdomarsaleem** [quantumblacklabs/kedro#48]
## Description
A dataset class to load and save feather files.

## Context
Feather is a useful format for large storage and quick access where it is cpp binding which gives a very good write and read speed. The feature format will be a good format for the intermediate storage files.

## Possible Implementation
Copyright 2018-2019 QuantumBlack Visual Analytics Limited

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
 NONINFRINGEMENT. IN NO EVENT WILL THE LICENSOR OR OTHER CONTRIBUTORS
 BE LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER LIABILITY, WHETHER IN AN
 ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF, OR IN
 CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

 The QuantumBlack Visual Analytics Limited ("QuantumBlack") name and logo
 (either separately or in combination, "QuantumBlack Trademarks") are
 trademarks of QuantumBlack. The License does not grant you any right or
 license to the QuantumBlack Trademarks. You may not use the QuantumBlack
 Trademarks or any confusingly similar mark as a trademark for your product,
     or use the QuantumBlack Trademarks in any other manner that might cause
 confusion in the marketplace, including but not limited to in advertising,
 on websites, or on software.

 See the License for the specific language governing permissions and
 limitations under the License.

"""``FeatherLocalDataSet`` loads and saves data to a local feather format file
(https://github.com/wesm/feather). The
underlying functionality is supported by pandas, so it supports all operations the pandas supports.
"""
from pathlib import Path
from typing import Any, Dict

import pandas as pd

from kedro.io.core import AbstractDataSet, DataSetError, FilepathVersionMixIn, Version

class FeatherLocalDataSet(AbstractDataSet, FilepathVersionMixIn):
    """``FeatherLocalDataSet`` loads and saves data to a local feather file. The
    underlying functionality is supported by pandas, so it supports all
    allowed pandas options for loading and saving csv files.

    Example:
    ::

        >>> from kedro.contrib.io import FeatherLocalDataSet
        >>> import pandas as pd
        >>>
        >>> data = pd.DataFrame({'col1': [1, 2], 'col2': [4, 5],
        >>>                      'col3': [5, 6]})
        >>> data_set = FeatherLocalDataSet(filepath="test.feather",
        >>>                                  load_args=None,
        >>>                                  save_args={"index": False})
        >>> data_set.save(data)
        >>> reloaded = data_set.load()
        >>>
        >>> assert data.equals(reloaded)

    """

    def _describe(self) -> Dict[str, Any]:
        return dict(
            filepath=self._filepath,
            load_args=self._load_args,
            save_args=self._save_args,
            version=self._version,
        )

    def __init__(
            self,
            filepath: str,
            load_args: Dict[str, Any] = None,
            save_args: Dict[str, Any] = None,
            version: Version = None,
    ) -> None:
        """Creates a new instance of ``FeatherLocalDataSet`` pointing to a concrete
        filepath.

        Args:
            filepath: path to a feather file.
            load_args: feather options for loading feather files.
                Here you can find all available arguments:
                https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_feather.html#pandas.read_feather
                All defaults are preserved.
            save_args: None
            version: If specified, should be an instance of
                ``kedro.io.core.Version``. If its ``load`` attribute is
                None, the latest version will be loaded. If its ``save``
                attribute is None, save version will be autogenerated.
        """
        default_save_args = {"index": False}
        default_load_args = {}
        self._filepath = filepath
        self._load_args = (
            {**default_load_args, **load_args}
            if load_args is not None
            else default_load_args
        )
        self._save_args = (
            {**default_save_args, **save_args}
            if save_args is not None
            else default_save_args
        )
        self._version = version

    def _load(self) -> pd.DataFrame:
        load_path = self._get_load_path(self._filepath, self._version)
        return pd.read_feather(load_path, **self._load_args)

    def _save(self, data: pd.DataFrame) -> None:
        save_path = Path(self._get_save_path(self._filepath, self._version))
        save_path.parent.mkdir(parents=True, exist_ok=True)
        data.to_feather(str(save_path))

        load_path = Path(self._get_load_path(self._filepath, self._version))
        self._check_paths_consistency(
            str(load_path.absolute()), str(save_path.absolute())
        )

    def _exists(self) -> bool:
        try:
            path = self._get_load_path(self._filepath, self._version)
        except DataSetError:
            return False
        return Path(path).is_file()

## Possible Alternatives
(Optional) Describe any alternative solutions or features you've considered.

**Comment by DmitriiDeriabinQB** [comment]
Hi @mdomarsaleem, thank you for submitting this issue! Please feel free to create a pull request against this repository and add `FeatherLocalDataSet` to `kedro.contrib.io`. Please also add the corresponding unit tests for your dataset (example can be found in `tests/contrib/io/azure/test_csv_blob.py`).

**Comment by 921kiyo** [comment]
Merged in https://github.com/quantumblacklabs/kedro/pull/59
