### ISSUE TITLE
Broken link in readthedocs

### ISSUE THREAD

**Issue by vjkr** [quantumblacklabs/kedro#484]
I really do not know how to put this.
But while trying to install i found this link not working
https://kedro.readthedocs.io/en/stable/02_getting_started/01_prerequisites.html
at 
https://pypi.org/project/kedro/
Thanks

**Comment by s-mawjee** [comment]
Seems like the "02_getting_started" changed to "02_get_started"

Link is: https://kedro.readthedocs.io/en/stable/02_get_started/01_prerequisites.html

**Comment by limdauto** [comment]
Hi @vjkr, thank you very much for raising this. The correct link is https://kedro.readthedocs.io/en/stable/02_get_started/01_prerequisites.html. We will also fix it in the README as well.
