### ISSUE TITLE
Update pandas version

### ISSUE THREAD

**Issue by crypdick** [quantumblacklabs/kedro#488]
## Description
According to https://github.com/quantumblacklabs/kedro/blob/master/setup.py#L41 Kedro requires `pandas>=0.24, <1.0.4` due to [this issue](https://github.com/pandas-dev/pandas/issues/34467). According to https://github.com/pandas-dev/pandas/issues/34467#issuecomment-644069002 this issue has been fixed.

## Context
pandas 1.0.3 causes a dependency with Modin, which requires v1.0.5. This has been causing me trouble with conda environment solving, and prints ugly errors from Modin or Kedro.

![2020-08-20_17-14](https://user-images.githubusercontent.com/5415776/90821073-b4283980-e308-11ea-9d51-0fe103420ca8.png)

**Comment by JMBurley** [comment]
Shared dependencies with issue https://github.com/quantumblacklabs/kedro/issues/489  if upgrading to pandas 1.1.0. Independent if upgrading to 1.0.5.

**Comment by crypdick** [comment]
@JMBurley I'm kinda amazed that you reported #489 less than 1 minute after I reported this

(closing as duplicate)
