### ISSUE TITLE
Consider dropping support for template_files and doc_html

### ISSUE THREAD

**Issue by WaylonWalker** [quantumblacklabs/kedro#496]
## Description

A Kedro install is around 15M in site-packages, but only about 1M of that is even runnable code.  Much of it is the docs and template.  With the docs now deployed to readthedocs and kedro starters being released,  these two components are only adding bloat and should be considered for deprecation in favor of better solutions that are already in place.

## Context

While 14M is not a lot of space, it only slows down installs and docker builds for unnecessary components.

## Possible Implementation

Remove ` template_files + doc_html_files` from [setup.py](https://github.com/quantumblacklabs/kedro/blob/master/setup.py#L179)

**Comment by yetudada** [comment]
This is actually a good point @WaylonWalker! I'll note it down for discussion. We did do a check a while ago of who was using `kedro docs` and a few legacy users still relied on it. I might just check in to see if it would be okay if we deprecated it.

**Comment by WaylonWalker** [comment]
Thanks for considering @yetudada.

**Comment by WaylonWalker** [comment]
Have you found anyone utilizing the docs command?  It would be great to see kedro a bit lighter.

**Comment by MerelTheisenQB** [comment]
Hi @WaylonWalker, we suspect we still have users that are using the `kedro docs` command. We're implementing product usage analytics which will show how many users still need this. Stay tuned until we know whether we can drop the support for `template_files` and `doc_html`
