### ISSUE TITLE
    for k, v in anyconfig.load(config_file).items() AttributeError: 'str' object has no attribute 'items'

### ISSUE THREAD

**Issue by deveraj54** [quantumblacklabs/kedro#498]
for k, v in anyconfig.load(config_file).items()
AttributeError: 'str' object has no attribute 'items'

I am getting an error. Need help to resolve this issue

**Comment by lorenabalan** [comment]
Closing this as it is a generic issue, not Kedro-related, and it provides no useful information to reproduce/debug. If it is a **kedro-specific** error, please raise in a separate issue with enough details for us to be able to understand what is happening.
