### ISSUE TITLE
Coloured log outputs at checkpoints

### ISSUE THREAD

**Issue by debugger24** [quantumblacklabs/kedro#500]
## Description
We can have colored outputs for some of the important logs like for node/pipeline completion. Let me know what you think about this.

![image](https://user-images.githubusercontent.com/12707743/92311387-3173cf80-efd4-11ea-885f-af6593695c3d.png)

## Context
When we have a lot of logs, and I want to keep progress on how much it is completed, it painful to go through all the logs when it is running, highlighting of green color for the success of nodes and red for error in my nodes will be nice. 

## Possible Implementation
We can use termcolor python library. https://pypi.org/project/termcolor/

**Comment by yetudada** [comment]
Hi @debugger24! Thanks for raising this issue. I'm going to add it to a larger epic that we're working on that will improve the UX on the CLI. A side question for you, I see you're using the `PartitionedDataSet` in your runs, what has your experience using it been like?

**Comment by debugger24** [comment]
I loved the partitioned dataset. It was very useful for my usecase.

**Comment by yetudada** [comment]
I just realised that we do actually have this functionality in Kedro! Check out [this link](https://kedro.readthedocs.io/en/stable/kedro.extras.logging.ColorHandler.html) in the docs. I'll close this ticket now.
