### ISSUE TITLE
Path management in data catalog

### ISSUE THREAD

**Issue by remiromi** [quantumblacklabs/kedro#502]
Hello, I am creating a pipeline in which I have to download/upload files form a Windows shared folder.
I put the folder in a data catalog entry as a partitioned dataset and it works on Windows, but if I try on linux of course the path cannot be read. 

In the catalog I have
`dataset_name:
  type: PartitionedDataSet
  dataset: kedro.extras.datasets.text.TextDataSet
  path: //host/path/to/folder`

Is there a way in kedro to use a single data catalog entry for both OSs or should I use a different config file?

I tried to use pathlib to create Path objects (so '/' and '\\' do not matter) but it's still out of the data catalog. The optimal thing would be a unique configuration, system independent. Is https://pypi.org/project/smbprotocol/ the solution (without using the catalog)? 

I looked here and in the docs but I did not find anything similar.

Thank you in advance!

**Comment by yetudada** [comment]
Hi @remiromi! Thank you for this question. I would recommend using additional configuration. You're right that it's related to the file paths and requires an additional configuration file. We document how to add an additional environment [here](https://kedro.readthedocs.io/en/stable/04_kedro_project_setup/02_configuration.html#additional-configuration-environments).

Your solution would be something like:
- Your dataset entry for the version of your `catalog.yml` with the Windows file path being located in `conf/base` 
- An additional environment, perhaps something like `conf/linux` with a `catalog.yml` that has the Linux file path 
- When you do a `kedro run` you would do `kedro run --env linux` to run the version of `catalog.yml` with the Linux version of that file path

Let us know if this helps!

**Comment by remiromi** [comment]
Hello @yetudada ! Thanks for the quick reply, in the end I solved as you suggested, having two separate config files with the specific environment settings. Thank you!
