### ISSUE TITLE
[KED-2141] Impala support for kedro, custom SQLdataset

### ISSUE THREAD

**Issue by noklam** [quantumblacklabs/kedro#504]
## Description
To use `kedro` with impala.  Is is possible to extend the current SQLDataset to create a connection instead of accepting a string only?

## Context
Integration with Impala is useful.

## Possible Implementation
I am using the python package impyla. To query something with pandas, I need to first create a connection.

```python
from impala.dbapi import connect

user=user
password=password
host=host

conn = connect(host=host, port=21050, user=user, password=password)
sql = 'select * from trable'
pd.read_sql(sql, conn)
```

In theory, as long as I can implement the connection creation logic manually, the rest should just match the standard pandasSQLdataset.

**Comment by yetudada** [comment]
Hi @noklam! Thank you for this query. We think it may be possible to support Impala in the way that you would prefer by creating your own version of the `SQLDataSet`. We detail how to create a custom dataset in our documentation: https://kedro.readthedocs.io/en/stable/07_extend_kedro/01_custom_datasets.html

Do let us know if this would be helpful, if so then I'll be able to close this issue.

**Comment by 921kiyo** [comment]
I've logged how Kedro could support with Impala :)

**Comment by brendalf** [comment]
Is there anything left to do here?

**Comment by MerelTheisenQB** [comment]
Hi @brendalf, there hasn't been an attempt yet to implement this, so if you're interested in helping out we'd be more than happy to accept a PR 😄

**Comment by noklam** [comment]
Any thoughts from Kedro team? If not I may try to implement one, but cannot guarantee it works for every platform.

I am mainly a Window user, getting impala to works in Window is a bit tricky.

**Comment by MerelTheisenQB** [comment]
@noklam This isn't a priority for the team at the moment, so we'd be very happy to accept a PR.
