### ISSUE TITLE
Can't instantiate abstract class ProjectContext with abstract methods project_name, project_version

### ISSUE THREAD

**Issue by adamginza** [quantumblacklabs/kedro#523]
Hi,

I'm new to kedro and I have a problem when opening Jupyter Lab/Notebook from Kedro using the command `kedro jupyter lab`. The error was:

**TypeError: Can't instantiate abstract class ProjectContext with abstract methods project_name, project_version Run with --verbose to see the full exception Error: Unable to load Kedro context with environment `None`. Make sure it exists in the project configuration. Error: Can't instantiate abstract class ProjectContext with abstract methods project_name, project_version**

I have been following the steps in [kedro official docs](https://kedro.readthedocs.io/en/stable/) website , but didn't succeed. For reproducibility  purpose, here are the steps I performed:

1. Create new conda environment: `conda create --name myenv`
2. Activate the environment: `source activate myenv`
3. Create new kedro project with pyspark starter: `kedro new --starter=pyspark`
4. Go to newly created project folder: `cd my_project`
5. Install requirements: `kedro install`
6. Open jupyter lab: `kedro jupyter lab --no-browser`

Step 6 where gave me the error. As a side note, I had to do point 5 twice because the first time gave me incompatible error, but then I executed it again and it works.

Sorry in advance if I didn't put enough detail. Feel free to ask any details you need, I'll be gladly to answer them.

Thank you.

**Comment by laisbsc** [comment]
Hello there @adamginza.

Were are very excited that you've decided to try our Kedro.  

Thanks fro your question. I have a hint on what can be happening to your project. Can you just confirm what version of Python you are using to run the project?

Thanks.

**Comment by 921kiyo** [comment]
Hi! I followed your steps and tried to reproduce the error, but `kedro jupyter lab --no-browser` is working fine for me. 

Did you specify which Python version you want to use when running `conda create --name myenv`(Kedro supports 3.6 and 3.7 for Spark).

**Comment by lorenabalan** [comment]
Hi @adamginza any luck with the above? If not please confirm which Kedro and Python versions you are running. As Kiyo mentioned, 3.8, which I think is the default conda python env, is not well supported for `pyspark`. Otherwise it might be a case of using mismatching kedro version and starter version.

**Comment by adamginza** [comment]
Hi, sorry for late reply. When I created the conda environment I didn't specify the python version. However it automatically has python version **3.6.10** when the new environment has been created.

**Comment by lorenabalan** [comment]
Alright, in that case could you try running `kedro new --starter=pyspark --checkout=0.16.x` where `0.16.x` matches the version of kedro you have installed?

**Comment by limdauto** [comment]
Hi @adamginza I'm going to close this now as we haven't been able to reproduce the issue. Please feel free to reopen the issue if you still haven't resolved it. Many thanks!
