### ISSUE TITLE
kedro.io.core.DataSetError: Failed while saving data to data set MemoryDataSet(). can't pickle _thread.RLock objects

### ISSUE THREAD

**Issue by noklam** [quantumblacklabs/kedro#525]
## Context
I have an experiment session class that need to pass in every steps of the pipeline to log my model metrics etc. But I get an error
```
kedro.io.core.DataSetError: Failed while saving data to data set MemoryDataSet().
can't pickle _thread.RLock objects
```

## Steps to Reproduce
Repository: https://github.com/noklam/kedro_pickle_bug
```python

from trains import Task


def init_exp_logger():
    task = Task.init(project_name="demo_bug", task_name="demo_bug", output_uri=None)
    return task


def dummy_function(exp_logger):
    print("dummy")


def create_pipeline(**kwargs):
    return Pipeline([
        node(
            func=init_exp_logger,
            inputs=None,
            outputs="exp_logger",
            name="init_exp_logger",
        ),
        node(
            func=dummy_function,
            inputs="exp_logger",
            outputs=None,
            name="dummy_function`",
        ),]
    )
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.16.5
* Python version used (`python -V`): 3.7.5
* Operating system and version: Window 10

**Comment by 921kiyo** [comment]
Hi! https://github.com/noklam/kedro_pickle_bug seems to be an empty repo, but I think I know what might cause this. By default MemoryDataSet tries to deepcopy on save/load https://github.com/quantumblacklabs/kedro/blob/master/kedro/io/memory_data_set.py#L84, and I think one of your input/output are not serialisable (e.g Tensorflow object etc.). You can modify the copy_mode in MemoryDataSet as described in https://kedro.readthedocs.io/en/stable/10_tools_integration/01_pyspark.html?#use-memorydataset-with-copy-mode-assign-for-non-dataframe-spark-objects I hope this helps :)

**Comment by 921kiyo** [comment]
Closing this issue, but feel free to re-open it if you have any follow-up question :) There's a community-driven discourse page and you are more than welcome to join https://discourse.kedro.community/ :)

**Comment by noklam** [comment]
@921kiyo 

Sorry for the late reply!  I use `copy_mode : assign` and it works. Is there any drawback if not using deepcopy?

**Comment by 921kiyo** [comment]
Glad it worked :) We use deepcopy by default as a safeguard for not mutating the original data in memory. With `assign`, if you mutate an assigned list, it will change the original list. For example,
```python
a = [1,2]
b = a
b[0] = 10
print(a) -> [10,2]
```
