### ISSUE TITLE
[KED-2131] Incomplete documentation about the Spaceflights tutorial

### ISSUE THREAD

**Issue by falcaopetri** [quantumblacklabs/kedro#527]
## Description

[The docs regarding the Spaceflights tutorial](https://github.com/quantumblacklabs/kedro/blob/8c0a8ccbffa22daf64a31fea138402a34fd51f2b/docs/source/03_tutorial/02_tutorial_template.md) are incomplete, which makes it harder to successfully finish it. 

This has been partially discussed in https://github.com/quantumblacklabs/kedro-examples/issues/58 (including the issue reproducibility). Therefore, I will discuss it in a complementary way.

## Context

There is apparently an ongoing internal issue about improving the organization and sync between the repos `kedro-examples`, `kedro-training`, and `kedro-starter-spaceflights` (https://github.com/quantumblacklabs/kedro-training/pull/1).

As I understood, spaceflight full-repo is moving from `kedro-examples/kedro-tutorial` to `kedro-training/kedro/exercises/spaceflight`.

I'm not sure about what is being tracked internally, so I will list what I've found related to Spaceflights' `requirements.txt`:

- Spaceflights tutorial requires `kedro[pandas.CSVDataSet,pandas.ExcelDataSet]` in requirements. Still, it is not specified in the [docs tutorial](https://kedro.readthedocs.io/en/stable/03_tutorial/02_tutorial_template.html#install-project-dependencies). This results in the missing requirement `pandas` and `xlrd` when trying to load the datasets in [Set up the data](https://kedro.readthedocs.io/en/stable/03_tutorial/03_set_up_data.html#register-the-datasets).
- `kedro-examples/kedro-tutorial` is also missing this requirement in its [`src/requirements.txt`](https://github.com/quantumblacklabs/kedro-examples/blob/a4ef342c47e4c83583212e0e675e315a2a148757/kedro-tutorial/src/requirements.txt), which yielded https://github.com/quantumblacklabs/kedro-examples/issues/58.
- Both [`kedro-training`](https://github.com/quantumblacklabs/kedro-training/blob/90a74d43fb99e8127836a651189daa521a268ad8/kedro-exercises/spaceflight/src/requirements.txt) and [`kedro-starter-spaceflights`](https://github.com/quantumblacklabs/kedro-starter-spaceflights/blob/master/%7B%7B%20cookiecutter.repo_name%20%7D%7D/src/requirements.txt) already have this requirement in their `src/requirements.txt`.

## Actionable
1. `kedro-examples/kedro-tutorial`'s `requirements.txt` should be updated to contain `kedro[pandas.CSVDataSet,pandas.ExcelDataSet]`.
2. Docs should be improved to show that `kedro[pandas.CSVDataSet,pandas.ExcelDataSet]` is required. [`Set up the spaceflights project#Install project dependencies`](https://kedro.readthedocs.io/en/stable/03_tutorial/02_tutorial_template.html#install-project-dependencies) is probably the right place.
3. This also applies to kedro-training docs at [`Create a new project#kedro install`](https://github.com/quantumblacklabs/kedro-training/blob/master/docs/04_new_project.md#kedro-install).
4. [Latest and stable Kedro docs](https://kedro.readthedocs.io/en/latest/03_tutorial/01_spaceflights_tutorial.html) points to `kedro-examples` as the full source to the spaceflights project. I'm not sure, but I guess that this will/should be eventually changed to `kedro-training/kedro-exercises/spaceflight`.

I could work on 1., 2., and 3. if it makes sense (note that they are at 3 different repos).

PS: Sorry for the cross-repos references everywhere. I considered that here was the best place to report it.

**Comment by 921kiyo** [comment]
Thank you for reporting it! We will address your feedback in the docs and spaceflight example code.

**Comment by falcaopetri** [comment]
Thanks for addressing it, @921kiyo. 

If there is still time, I'd like to add three more notes regarding the `docs` and `kedro-training`:
- Doc's [Data science pipeline#Update dependencies](https://kedro.readthedocs.io/en/stable/03_tutorial/04_create_pipelines.html#update-dependencies) adds the `scikit-learn` dependency to `src/requirements.txt` and then runs `kedro install`. Shouldn't it be `src/requirements.in` + `kedro build-deps && kedro install` instead? 
- `kedro-training` also [uses `scikit-learn`](https://github.com/quantumblacklabs/kedro-training/blob/90a74d43fb99e8127836a651189daa521a268ad8/docs/07_pipelines.md#creating-the-data-science-pipeline), and specifies it in the full project [`requirements.txt`](https://github.com/quantumblacklabs/kedro-training/blob/90a74d43fb99e8127836a651189daa521a268ad8/kedro-exercises/spaceflight/src/requirements.txt), but there is no instruction stating that `sklearn` should be installed when following `kedro-training docs`.
- [Interact with Data Engineering Convention](https://kedro.readthedocs.io/en/stable/03_tutorial/06_visualise_pipeline.html#interact-with-data-engineering-convention) has the wrong data type connector `kedro_tutorial.io.xls_local.ExcelLocalDataSet` (well, it is actually defined if you follow [kedro-training](https://github.com/quantumblacklabs/kedro-training/blob/master/docs/13_custom-datasets.md)):
```yaml
shuttles:
  type: kedro_tutorial.io.xls_local.ExcelLocalDataSet
  filepath: data/01_raw/shuttles.xlsx
  layer: raw
```

**Comment by laisbsc** [comment]
Hey there @falcaopetri.

Thanks for reporting this. It is not too late at all!  

I will add your additional comments to our ticket. In the meantime, if you'd like to fix the issues, feel free to make a PR and work on it 😄 We truly appreciate it!

Chat soon.

**Comment by guludo** [comment]
From @falcaopetri's comment:

> Doc's Data science pipeline#Update dependencies adds the scikit-learn dependency to src/requirements.txt and then runs kedro install. Shouldn't it be src/requirements.in + kedro build-deps && kedro install instead?

I have the same question. Adding it to `src/requirements.in` makes more sense to me too.

**Comment by lorenabalan** [comment]
@guludo Apologies, just noticed this has been merged into `develop`, which is not visible on ReadTheDocs. Indeed it should be in `src/requirements.in`, the next version will have the correct docs.

**Comment by lorenabalan** [comment]
Closing this as resolved through linked PRs/issues, as well as https://github.com/quantumblacklabs/kedro/commit/589d6a7a329f453ac91662814ec044dc41d1063c and https://github.com/quantumblacklabs/kedro/commit/0fd6b623bdaa2f69623ad4fdacb022a5862fb590 . Please feel free to open a new issue if there are other observations!
