### ISSUE TITLE
The latest Click version 7.0 is not supported

### ISSUE THREAD

**Issue by Minyus** [quantumblacklabs/kedro#54]
## Description
Kedro requires click==6.7 and causes conflict error if the installed click version is 7.0.

## Context
Support for click 7.0 is in demand since the latest click version 7.0 was released on Sep 26, 2018 and commonly used now. The latest Anaconda uses click 7.0 as well.

Reference: https://docs.anaconda.com/anaconda/packages/py3.7_linux-64/

## Steps to Reproduce
1. Follow the Kedro's getting started: https://kedro.readthedocs.io/en/latest/02_getting_started/04_hello_world.html

## Expected Result
`kedro run` does not return any errors.

## Actual Result
`kedro run` returns conflict error as follows.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/kedro/cli/cli.py", line 519, in _get_plugin_command_groups
    groups.append(entry_point.load())
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2433, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2456, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Click 7.0 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('click==6.7'), {'kedro'})
Error: Loading project commands from kedro-viz = kedro_viz.server:commands
```
![image](https://user-images.githubusercontent.com/33908456/61039950-4a014d80-a402-11e9-89c9-b7d90371856b.png)

## Your Environment
Kedro 0.14.3
Python 3.6.8
Ubuntu 18.04.2 LTS (Bionic Beaver)

**Comment by tolomea** [comment]
Thanks for raising this. A fix for this has been merged.
https://github.com/quantumblacklabs/kedro/commit/065b7cc45da28b67394fb6205d73333c7095d962
This will be in the next release.

**Comment by simontamayo** [comment]
I got this error while trying to run kedro viz, I fixed it upgrading **awscli** and **botocore** :
```
pip install awscli --upgrade
pip install botocore --upgrade
```

**Comment by MarcoGC** [comment]
I have the same error.
