### ISSUE TITLE
[KED-1970] Add documentation about `kedro test`

### ISSUE THREAD

**Issue by laisbsc** [quantumblacklabs/kedro#540]
Tests are fundamental to write good code.

Kedro has the CLI command `kedro test` to help you test your pipelines. We would love to have our section in our docs expanded how to write tests for your Kedro project.

In case you want to work on this issue, you can add your PR to the [Test you project](https://github.com/quantumblacklabs/kedro/blob/develop/docs/source/09_development/03_commands_reference.md#test-your-project) section.

And as consulting material, you can use the help of our super-awesome @dataengineerone videos.  
The pre-selected material is [here](https://www.youtube.com/watch?v=qdZ035dX064&t=116s&ab_channel=DataEngineerOne) and [here](https://www.youtube.com/watch?v=3pF0lZfmvOM&t=70s&ab_channel=DataEngineerOne).

**Comment by brendalf** [comment]
I'm interested in working on this issue.

**Comment by yetudada** [comment]
We have to rethink the way that we do this documentation. We'll be closing this issue to track it back on our internal backlog.
