### ISSUE TITLE
Misleading potential typo in iPython section of docs

### ISSUE THREAD

**Issue by josephhaaga** [quantumblacklabs/kedro#551]
## Description
The [**Converting functions from Jupyter Notebooks into Kedro nodes**](https://kedro.readthedocs.io/en/stable/10_tools_integration/02_ipython.html#converting-functions-from-jupyter-notebooks-into-kedro-nodes) section of the [iPython docs](https://kedro.readthedocs.io/en/stable/10_tools_integration/02_ipython.html) contains an example for converting the `some_action` function into a node, but then explains that running `kedro jupyter convert` will result in a Python file containing the "`convert_me` function definition".

![image](https://user-images.githubusercontent.com/5090136/95357447-dc0e3500-0895-11eb-8474-87c31ffbedee.png)

## Context
Not a severe bug, but could be misleading/confusing to new users.

Looks like the live docs have this page in `10_tools_integration`, but master has it renamed to `11_tools_integration` so I can't verify my hunch that the example used contain a function called `convert_me`, and that one line simply wasn't updated along with the rest of the example.

**Comment by laisbsc** [comment]
Hey @josephhaaga, thanks for reporting it.

Nice catch!
