### ISSUE TITLE
[KED-1691] Create migration guide from old-style to new-style dataset

### ISSUE THREAD

**Issue by laisbsc** [quantumblacklabs/kedro#561]
## Introduction
We need a section in the docs to describe how to migrate from the old-style dataset, e.g. `ParquetS3DataSet` to the new style e.g. `kedro.extras.datasets.pandas.ParquetDataSet`.

## Suggestion
To migrate from `ParquetS3DataSet` to `pandas.ParquetDataSet`, the steps are the following:

In the `catalog.yaml`:
- Change the type from `ParquetS3DataSet` to `pandas.ParquetDataSet`
- Change the filepath from a relative path, e.g. `data/02_intermediate/data.parquet` to an absolute path with S3 protocol: `s3//bucket-name/data/02_intermediate/data.parquet`
- Remove the `bucket_name` argument
- Change `s3fs_args` to `fs_args` (the user might need to double check each option though).

## Testing
Check the [Developer Workflow](https://github.com/quantumblacklabs/kedro/blob/master/CONTRIBUTING.md#developer-workflow) in the CONTRIBUTING.md for more details on how to test and proceed with your contribution.

> NOTE: This ticket falls under the [extras](https://github.com/quantumblacklabs/kedro/blob/master/CONTRIBUTING.md#extras-contribution-process) area of contribution.

**Comment by stichbury** [comment]
I'm not sure exactly where this would sit: it's a decision to make perhaps after the text is created. There is possibly a slot it could go in here https://kedro.readthedocs.io/en/stable/05_data/01_data_catalog.html?highlight=parquet#a-typical-example-of-transcoding

Alternatively, we could create a FAQ entry for it.

Are there any other migrations we need to document likewise?

**Comment by laisbsc** [comment]
> Are there any other migrations we need to document likewise?

I am not 100%. Maybe @limdauto could help us with this one? :)

**Comment by yetudada** [comment]
Thanks for creating this issue @laisbsc ❤️ We're going to close this issue in light of how Kedro has progressed so much since this version. This task is no longer required.
