### ISSUE TITLE
Kedro context  in  jupyterhub

### ISSUE THREAD

**Issue by sergun** [quantumblacklabs/kedro#565]
## What are you trying to do?
In my company we use multi-user jupyterhub installation and have no freedom to start jupyter notebooks with custom ports. Can only execute jupyter notebooks from jupyterhub.
What is best practice to marry kedro and jupterhub? 

I know how to add custom conda environment/kernel and make it visible in jupyterhub.
The question is how to automatically create kedro context on start of notebook of this kernel?

**Comment by mzjp2** [comment]
So, the way that Kedro works is that it has a file located at `.ipython/profile_default/startup/00-kedro-init.py` inside your project, which `jupyter` automatically picks up on. This file is responsible for loading the context and inserting it into the Jupyter session scope.

It's just a matter of you configuring your JupyterHub installation to run that same code on startup. [This SO answer](https://stackoverflow.com/questions/47978586/how-to-config-startup-script-for-jupyterhub) may be helpful, but you may need to do further investigation.

**Comment by lorenabalan** [comment]
Thank you both, I'm closing this as answered. Please feel free to direct questions to StackOverflow (we monitor questions tagged with `kedro`) or get support from the community on [Discourse](https://discourse.kedro.community/). 😊
