### ISSUE TITLE
Loading data from storage.googleapis.com

### ISSUE THREAD

**Issue by kelandrin** [quantumblacklabs/kedro#569]
## What are you trying to do?

**I am trying to load data from a url of this form (where ${(date +"%Y-%m-%d")} is meant to be today's date):**

https://storage.googleapis.com/uc-data4good/US\ SDS/${(date +"%Y-%m-%d")}/sds-v3-full-state.csv.gz

**In the YAML file, I tried**

state_sd:
  type: pandas.CSVDataSet
  filepath: https://storage.googleapis.com/uc-data4good/US\ SDS/${(date +"%Y-%m-%d")}/sds-v3-full-state.csv.gz
  load_args:
    sep: ','
    compression: 'gzip'

**and I keep getting this error**:
 
"google.cloud.bigquery.opentelemetry_tracing - INFO - This service is instrumented using OpenTelemetry.OpenTelemetry could not be imported; pleaseadd opentelemetry-api and opentelemetry-instrumentationpackages in order to get BigQuery Tracing data."

Perhaps I am formatting the YAML file wrong? I am finding it very tricky to know how to format each of these YAML requests; even with the examples from https://kedro.readthedocs.io/en/stable/05_data/01_data_catalog.html

**Comment by mzjp2** [comment]
Are you sure that is an error? It seems to be an `INFO` log rather than a fatal error. I think it becomes because if you ran `pip install "kedro[pandas]"` then it downloaded the dependencies for `pandas.GBQTableDataSet` which has some google cloud python SDKs as dependencies. You can uninstall those dependencies if you don't need them.

Looking at your `filepath` string, it looks like you're trying to insert a dynamic value into there. If so, you need to follow the documentation for [templating configuration](https://kedro.readthedocs.io/en/stable/04_kedro_project_setup/02_configuration.html?highlight=templated#templating-configuration) so you can dynamically insert today's date into the catalog at runtime.

**Comment by kelandrin** [comment]
Gotcha, and to make sure I understand, I need to add this code to the hooks.py file, under class ProjectHooks?

'''
from kedro.config import TemplatedConfigLoader  # new import


class ProjectHooks:
    @hook_impl
    def register_config_loader(self, conf_paths: Iterable[str]) -> ConfigLoader:
        return TemplatedConfigLoader(
            conf_paths,
            globals_pattern="*globals.yml",  # read the globals dictionary from project config
            globals_dict={  # extra keys to add to the globals dictionary, take precedence over globals_pattern
                "bucket_name": "another_bucket_name",
                "non_string_key": 10,
            },
        )
'''

and then I need a new YAML file called globals.yml, or can I just update the catalog.yml that I have the rest of my datasets listed in? 

After that, I can then start using https://storage.googleapis.com/uc-data4good/US\ SDS/${(date +"%Y-%m-%d")}/sds-v3-full-state.csv.gz ? Or how would I configure the variable entry part so that it substitutes?

**Comment by mzjp2** [comment]
> Gotcha, and to make sure I understand, I need to add this code to the hooks.py file, under class ProjectHooks?

Yep! Although beware that there is already an existing `register_config_loader` hook implementation in that class that you need to _replace_ with your quoted code.

> and then I need a new YAML file called globals.yml, or can I just update the catalog.yml that I have the rest of my datasets listed in?

You need a new `globals.yml` file, but in this case - I think you can actually completely do away with one.
 
> After that, I can then start using [https://storage.googleapis.com/uc-data4good/US\](https://storage.googleapis.com/uc-data4good/US%5C) SDS/${(date +"%Y-%m-%d")}/sds-v3-full-state.csv.gz ? Or how would I configure the variable entry part so that it substitutes?

You would need to do something like:

```yaml
# conf/base/catalog.yml

state_sd:
  type: pandas.CSVDataSet
  filepath: https://storage.googleapis.com/ucs-data4good/.../${today_date}/sds-v3...
```

and then in your `hooks.py` file, you do something like:

```python
    @hook_impl
    def register_config_loader(self, conf_paths: Iterable[str]) -> ConfigLoader:
        return TemplatedConfigLoader(
            conf_paths,
            globals_dict={
                "today_date": datetime.now().date().strftime("%Y-%m-%d")
            },
        )
```

with the relevant `datetime` import and correct function to get todays date formatted correctly (random guess there^).

**Comment by kelandrin** [comment]
Amazing! Thank you so much
