### ISSUE TITLE
Extend usage of `params:` syntax to custom YAMLDataSet, JSONDataSet etc.

### ISSUE THREAD

**Issue by jaklan** [quantumblacklabs/kedro#570]
## Description
Currently, we can pass parameters to nodes using `params:` syntax, e.g. `params:cpu_nodes`, which is really convenient. This FR is about extending that functionality to allow the same behaviour for custom YAMLDataSet, JSONDataSet (potentially any format serialized to `dict`), so when you define a sample YAML dataset called `calculated_parameters`, you will be able to access its content using `calculated_parameters:some_value`.

## Context
Sample scenario: during pipeline execution we use initial parameters + data to calculate the new ones. They are saved as a YAMLDataSet. These parameters are then used in the following nodes as function arguments. Various nodes need various calculated parameters, but as for now, we have to pass the whole dataset to each node and retrieve needed values inside the function. It makes function signatures not really informative and needs additional clarification in docstrings.

Of course we can use MemoryDataSets to pass all calculated parameters independently, but a) it's a nightmare when you have many of them b) if you want to use them in an another pipeline, you have to serialize them anyway, so then you would need an additional pre-processing node just to load the YAMLDataSet and return its content as single variables to use them as MemoryDataSets.

## Possible Implementation
It would be valuable to differentiate built-in `params:` and custom datasets. For example we can add additional prefix `dc:` (Data Catalog), e.g. `dc:calculated_parameters:some_value` to make it both clear for users and informative for Kedro to look for the file in Data Catalog.

**Comment by jaklan** [comment]
bump

**Comment by jaklan** [comment]
bump

**Comment by lorenabalan** [comment]
Hi @jaklan thank you for sharing & explaining your context, it makes sense. A while ago we looked at introducing a way to "query" a dataset for information you need in the node, and this suggestion reminds me of that. However we don't want to create our own DSL - it's already not ideal that we rely on `params:x` and `params:x.y`. 

There is a story on our roadmap around re-evaluating and re-constructing the _whole_ configuration workflow, and I've added your use case there for future reference. I believe that we need to think of a more holistic solution, not just one that will satisfy this particular case. Maybe won't necessarily fix it out of the box, but maybe it will enable an easier customisation on your side. 

Hope this makes sense. 🙂
