### ISSUE TITLE
Copy button is broken while on company VPN

### ISSUE THREAD

**Issue by WaylonWalker** [quantumblacklabs/kedro#580]
## Description
While creating #579 I realized that the copy-button.svg was not accessible.

## Context
The docs do not look nice with a broken image link.

![image](https://user-images.githubusercontent.com/22648375/96754068-65456180-1396-11eb-8461-55ae629c5ddd.png)

**Comment by yetudada** [comment]
This is an interesting error and I see that you're trying to fix it too. @stichbury, do you think @WaylonWalker's fix in #581?

**Comment by stichbury** [comment]
> This is an interesting error and I see that you're trying to fix it too. @stichbury, do you think @WaylonWalker's fix in #581?

:eyes:

**Comment by limdauto** [comment]
Thanks for fixing this @WaylonWalker!
