### ISSUE TITLE
Monitor pipeline status leveraging the existing React Viz plugin

### ISSUE THREAD

**Issue by msolano00** [quantumblacklabs/kedro#585]
## Description
It would be great if I could monitor the progress of my pipeline visually, not only from the terminal. It would help me understand quickly if something fails and where it failed.

## Context
Users in general like to keep an eye on the progress of their work. As of now, if a user doesn't have access to a terminal he/she won't have access to see the progress of their pipeline. For a business user this presents a challenge as most likely they won't have access, nor would they care to have access, to a terminal.

## Possible Implementation
Kedro already has a very nice React visualization tool. Can we leverage this UI not only for exploring the pipeline but also for monitoring the execution of the pipeline too?

## Possible Alternatives
Provide developers the ability to tap into some sort of API or socket to fetch the status of the pipeline. That way Kedro can allow developers to build their own monitoring visualizations.

**Comment by mmchougule** [comment]
I have been thinking something similar if we could have a Kedro hook to push events to an endpoint on kedro-viz server, then the React UI could show the node that just finished running as a flashing icon or something. This way we can have kedro-viz to monitor the pipeline run in real time. An example of a hook could be, `after_node_run` would send an event to the viz server and highlight the nodes that have completed the run. We would have to implement Server-Sent-Events on the kedro-viz server. I am working on a quick prototype on this but would love to hear thoughts/suggestions from everyone.

**Comment by msolano00** [comment]
@mmchougule that sounds great. As a future implementation this `after_node_run` hook could be customizable so that developers could potentially send events to things like Kafka. But just having the viz on the React tool itself sounds really good.

**Comment by mzjp2** [comment]
> @mmchougule that sounds great. As a future implementation this `after_node_run` hook could be customizable so that developers could potentially send events to things like Kafka. But just having the viz on the React tool itself sounds really good.

It already is! It’s a _hook_. You can define your own, and have it do whatever, whether it’s sending events to Kafka, Grafana, Slack, emailing yourself, etc... - you can register multiple hooks to do a variety of things across a variety of lifecycle events.

See: https://medium.com/quantumblack/introducing-kedro-hooks-fd5bc4c03ff5

Have a look at the hooks documentation

**Comment by mmchougule** [comment]
Okay great. You should be able to send events to Kafka already. It's already a hook `after_node_run`.

**Comment by mmchougule** [comment]
> > @mmchougule that sounds great. As a future implementation this `after_node_run` hook could be customizable so that developers could potentially send events to things like Kafka. But just having the viz on the React tool itself sounds really good.
> 
> It already is! It’s a _hook_. You can define your own, and have it do whatever, whether it’s sending events to Kafka, Grafana, Slack, emailing yourself, etc... - you can register multiple hooks to do a variety of things across a variety of lifecycle events.
> 
> See: https://medium.com/quantumblack/introducing-kedro-hooks-fd5bc4c03ff5 and the hooks documentation!

@mzjp2 beat me to it ;)

**Comment by msolano00** [comment]
This is great. I will close the ticket since this hook allows us to build code that can satisfy the requirement for monitoring. Thanks @mmchougule and @mzjp2!
