### ISSUE TITLE
Pipeline execution configuration

### ISSUE THREAD

**Issue by msolano00** [quantumblacklabs/kedro#591]
## Description
Right now I need to consume the output of a node as the dependency or argument of another node in order for Kedro to understand the relation (order/structure) between them. This doesn't feel right. Creating dummy outputs just to keep the pipeline structure seems more like a hack.

## Context
Not every node in a pipeline (from a logic perspective not exactly from a Kedro perspective) will always have as a dependency the output of the previous node. It would be nice to have that flexibility of being able to explicitly declare the structure or order in which your nodes will execute instead of only allowing Kedro to infer it. 

## Possible Implementation
Having a configuration file where you can have your pipeline structure somehow.

## Possible Alternatives
The Node class can have an additional optional argument that controls the execution, something like "depends", where we can pass the name of another node. Kedro can then know that Node2 can only run after Node1 has finished.

**Comment by DmitriiDeriabinQB** [comment]
@msolano00 Thanks for the suggestion. We did consider adding a `depends_on` argument to the node API, however the decision has been made not to go that route. 

We believe that the tradeoffs of enabling it overweight the potential benefits. One of the core principles in Kedro is that the pipeline workflow is entirely data-driven, i.e. the dataset dependencies entirely define the execution order within a given pipeline.

`depends_on` would unlock the possibility to completely bypass that principle and make such execution graph completely declarative, which undermines the entire role of the `Pipeline` abstraction. 

It is very much understandable that providing dummy data dependencies is a suboptimal way to fix the order between 2 nodes that don't require that explicitly, however we believe that this is lesser of evils when compared to completely declarative approach. Please let us know if you have any comments on that side.

**Comment by msolano00** [comment]
I understand the approach, thanks for the explanation @DmitriiDeriabinQB

**Comment by jeffkayne** [comment]
I have just encountered this error with one of our pipelines. What makes this a lot worse is that the order of execution is not always the same if there is no output specified from one particular pipeline. Sometimes our pipeline ran in the correct order, sometimes not. I understand the above decision to be data centric, however I think it could be more clear and could be something that is displayed in the logs before the pipeline run.

Would you consider adding to the logs the order of the nodes that are running before the pipeline starts? This could clutter the logs, but would at least provide visibility on exactly what is happening behind the scenes.

**Comment by klaerik** [comment]
This is something we are running into as well. Loading tables that have foreign key dependencies which has to be done in a certain order.

A depends_on parameter would be nice in this respect to avoid having to put in either a dummy data element or the earlier table (which could be large) as an upstream dependency.

**Comment by stbeceti** [comment]
I have a guess how I can influence the order of execution a little bit. Suppose I have a modular pipeline called `mod_pipe` that contains two independent pipelines `indep1` and `indep2` and a third one called `dep` that depends on the output of `indep2`:

```
mod_pipe:
pipeline(pipe=indep1 + indep2) + dep
```

Every time I run `mod_pipe`, `dep` is run last. Is there any guarantee that this will always be the case? I have read the dependency management about pipelines input and output, but still wonder if this is a coincidence.

**Comment by astrojuanlu** [comment]
Hi @stbeceti, could you describe in more detail your setup?

I read the previous comments and, while in principle there is no intention of adding new functionality of how pipelines are declared, if this is something that is frequently surprising users, maybe we could do a better job at documenting it, adding more info to the logs, or making the result more deterministic. Having a test case would be useful.

**Comment by statbece** [comment]
@astrojuanlu I wrote a very dummy example with prints regarding my `mode_pipe` example. I call two independent nodes, both only print "Dummy Function". Afterwards the dependent one is called, which prints "Do Something". 

When running the pipeline `mod_pipe`"Do Something" is printed as last.

```
"""Project pipelines."""
from typing import Dict

from kedro.pipeline import Pipeline, node
from kedro.pipeline.modular_pipeline import pipeline


def register_pipelines() -> Dict[str, Pipeline]:
    """Register the project's pipelines.

    Returns:
        A mapping from pipeline names to ``Pipeline`` objects.
    """

    def dummy_function(inp):
        print("Dummy Function")
        return 0

    def do_something(inp):
        print("Do Something")
        return 1

    indep1 = pipeline(
        [
            node(
                func=dummy_function,
                inputs="parameters",
                outputs="dummy_output1",
            )
        ],
        parameters="parameters"
    )

    indep2 = pipeline(
        [
            node(
                func=dummy_function,
                inputs="parameters",
                outputs="dummy_output2",
            )
        ],
        parameters="parameters"
    )

    dep = pipeline(
        [
            node(
                func=do_something,
                inputs="dummy_output2",
                outputs="output",
            )
        ]
    )
    return {
        "mod_pipe": pipeline(pipe=indep1 + indep2) + dep
    }
```

**Comment by stbeceti** [comment]
@astrojuanlu I wrote a very dummy example with prints regarding my `mod_pipe` example above. I call two independent nodes, both only print “Dummy Function”. Afterwards the dependent one is called, which prints “Do Something”.

When running the pipeline `mod_pipe` ”Do Something” is printed as last.

My `pipeline_registry.py` file looks as follows:

```
"""Project pipelines."""
from typing import Dict

from kedro.pipeline import Pipeline, node
from kedro.pipeline.modular_pipeline import pipeline


def register_pipelines() -> Dict[str, Pipeline]:
    """Register the project's pipelines.

    Returns:
        A mapping from pipeline names to ``Pipeline`` objects.
    """

    def dummy_function(inp):
        print("Dummy Function")
        return 0

    def do_something(inp):
        print("Do Something")
        return 1

    indep1 = pipeline(
        [
            node(
                func=dummy_function,
                inputs="parameters",
                outputs="dummy_output1",
            )
        ],
        parameters="parameters"
    )

    indep2 = pipeline(
        [
            node(
                func=dummy_function,
                inputs="parameters",
                outputs="dummy_output2",
            )
        ],
        parameters="parameters"
    )

    dep = pipeline(
        [
            node(
                func=do_something,
                inputs="dummy_output2",
                outputs="output",
            )
        ]
    )

    return {
        "mod_pipe": pipeline(pipe=indep1 + indep2) + dep
    }
```

**Comment by deepyaman** [comment]
> @astrojuanlu I wrote a very dummy example with prints regarding my `mod_pipe` example above. I call two independent nodes, both only print “Dummy Function”. Afterwards the dependent one is called, which prints “Do Something”.
> 
> When running the pipeline `mod_pipe` ”Do Something” is printed as last.
> 
> My `pipeline_registry.py` file looks as follows:
> 
> ```
> """Project pipelines."""
> from typing import Dict
> 
> from kedro.pipeline import Pipeline, node
> from kedro.pipeline.modular_pipeline import pipeline
> 
> 
> def register_pipelines() -> Dict[str, Pipeline]:
>     """Register the project's pipelines.
> 
>     Returns:
>         A mapping from pipeline names to ``Pipeline`` objects.
>     """
> 
>     def dummy_function(inp):
>         print("Dummy Function")
>         return 0
> 
>     def do_something(inp):
>         print("Do Something")
>         return 1
> 
>     indep1 = pipeline(
>         [
>             node(
>                 func=dummy_function,
>                 inputs="parameters",
>                 outputs="dummy_output1",
>             )
>         ],
>         parameters="parameters"
>     )
> 
>     indep2 = pipeline(
>         [
>             node(
>                 func=dummy_function,
>                 inputs="parameters",
>                 outputs="dummy_output2",
>             )
>         ],
>         parameters="parameters"
>     )
> 
>     dep = pipeline(
>         [
>             node(
>                 func=do_something,
>                 inputs="dummy_output2",
>                 outputs="output",
>             )
>         ]
>     )
> 
>     return {
>         "mod_pipe": pipeline(pipe=indep1 + indep2) + dep
>     }
> ```

You're guaranteed that the node in `indep_2` will execute before than in `dep`, but there's no guarantee as to when the node in `indep_1` will execute. Due to a relatively recent change, I believe the execution order will be consistent across runs IF using `SequentialRunner`, but there is no promise that that consistent order will not change if you modify the overall pipeline.

Dependency order is only guaranteed through inputs and outputs, so Kedro isn't designed for executing arbitrary tasks that don't produce/consume datasets in order; a workflow orchestrator is better suited for such use cases.
