### ISSUE TITLE
missing kedro.yml Kedro==0.16.6

### ISSUE THREAD

**Issue by noklam** [quantumblacklabs/kedro#596]
## Description
Missing kedro.yml, kedro new starter project cannot run kedro lint.

## Context
Missing config => Fail to run kedro lint
## Steps to Reproduce
1. kedro new (and say yes to everything)
2. kedro lint
3. error
## Expected Result
kedro lint should work

## Actual Result
```
kedro.framework.context.context.KedroContextError: Could not find any of configuration files '.kedro.yml, pyproject.toml' in /home/nokchan/dev/cba. If you have created your project with Kedro version <0.15.0, make sure to update your project template. See https://github.com/quantumblacklabs/kedro/blob/master/RELEASE.md#migration-guide-from-kedro-014-to-kedro-0150 for how to migrate your Kedro project.

```
-- If you received an error, place it here.
```

```
-- Separate them if you have more than one.
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`):
 Kedro==0.16.6
* Python version used (`python -V`):
3.7.5
* Operating system and version:
Ubuntu-16.0.4

**Comment by lorenabalan** [comment]
Hi @noklam I was not able to reproduce this issue. Could you please confirm that you are running `kedro lint` from inside the project root directory? Please also confirm that the project was generated with 0.16.6 or with an older version.

**Comment by noklam** [comment]
Sorry @lorenabalan, I closed this issue. I wasn't able to reproduce this issue on my own laptop. There must be some weird setting on my PC.
