### ISSUE TITLE
Kedro lint does not respect setup.cfg 

### ISSUE THREAD

**Issue by Lucianois** [quantumblacklabs/kedro#599]
Hardcoded --max-line-length=88 
 https://github.com/quantumblacklabs/kedro/blob/8942306a549367778e8eea7ca0814e884a4bf5d5/kedro/framework/cli/project.py#L128

**Comment by mzjp2** [comment]
I believe this has been addressed in https://github.com/quantumblacklabs/kedro/pull/576 which is currently in _develop_, so will come out as part of Kedro 0.17.0, because it's a breaking change(?)

**Comment by Lucianois** [comment]
I'm good with it being in 0.17
