### ISSUE TITLE
[KED-2296] Allow getting kedro starter from a repo subdirectory

### ISSUE THREAD

**Issue by takikadiri** [quantumblacklabs/kedro#600]
## Description
I would like my kedro starter to get the coockicutter projet from a repo subdirectory. I can then call the starter with something like this :

`kedro new --starter="starter-pyspark" --starter-repo https://github.com/quantumblacklabs/kedro-starter.git`

`--starter-repo` could have a default value or be preconfigured in the dev environment.

## Context

At our organisation we find it convenient to keep the kedro starters (templates) in one repo (like starters belonging to the same team, or grouped by any other criteria). We want also to keep the release process of these kedo starters consistent with our target infrastrcuture and our CICD. So we prefer having them in one repo alongside other CICD related items.

## Possible Implementation
Coockicutter added the multiple templates per one repository feature since the [1.7.1 release](https://github.com/cookiecutter/cookiecutter/blob/master/HISTORY.md#171-2019-04-21). Unfortunately, it seems that kedro-airlow (and subsequently kedro) has an [incompatibility issues](https://github.com/quantumblacklabs/kedro/blob/25fd242faafd1740f37e5094cd2e51f2120a0313/requirements.txt#L4) with coockicutter>1.7.0 . I don't know if it's still relevant.

**Comment by lorenabalan** [comment]
> Cookiecutter added the multiple templates per one repository feature since the 1.7.1 release. Unfortunately, it seems that kedro-airflow (and subsequently kedro) has an incompatibility issues with coockicutter>1.7.0 . I don't know if it's still relevant.

Thank you for bringing this to our attention! 
I'll create a ticket and discuss this with the team. :)

**Comment by limdauto** [comment]
@takikadiri Very happy to say now this is available in `kedro==0.17.0`. In fact, thanks for this suggestion. We have moved all of our starters into a [single repo](https://github.com/quantumblacklabs/kedro-starters) as well. A life-saver :)
