### ISSUE TITLE
Convert list on README.md into paragraph

### ISSUE THREAD

**Issue by yetudada** [quantumblacklabs/kedro#608]
## Description
The changes are related to our [README.md](https://github.com/quantumblacklabs/kedro/blob/master/README.md), I would like the list of names under [The humans behind Kedro](https://github.com/quantumblacklabs/kedro/blob/master/README.md#the-humans-behind-kedro) to be converted into a paragraph because this list takes up too much space.

**Comment by abdulelahsm** [comment]
hey could you assign this to me? I can manage to do it while running the other sprint as well

**Comment by yetudada** [comment]
Thank you @abdulelahsm! 🚀

**Comment by yetudada** [comment]
This is done and merged. Thank you @abdulelahsm 🎉
