### ISSUE TITLE
Documentation of `Running pipelines with IO` using KedroContext is missing

### ISSUE THREAD

**Issue by Minyus** [quantumblacklabs/kedro#61]
## Description
The document at
https://github.com/quantumblacklabs/kedro/blob/develop/docs/source/04_user_guide/05_nodes_and_pipelines.md#running-pipelines-with-io has not been updated to the upcoming version 0.15.0 and the documentation of `Running pipelines with IO` using KedroContext is missing.

## Context

KedroContext class was introduced by `[KED-826] Use KedroContext class in project template (#111)` (https://github.com/quantumblacklabs/kedro/commit/571bb8009b930e67c073115c23ae2d03942f6499) 2 days ago. 

Using this, I'm trying to give the input dataset in memory to the first node without saving a file and found the document has not been updated.

Related pull request: #60

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): Latest commit c9c49e0 in develop branch (version between 0.14.3 and 0.15.0)
* Python version used (`python -V`): 3.6.8
* Operating system and version: Ubuntu 18.04.2 LTS (Bionic Beaver)

**Comment by 921kiyo** [comment]
Hi @Minyus , thanks for opening the issue! This user guide section https://github.com/quantumblacklabs/kedro/blob/develop/docs/source/04_user_guide/05_nodes_and_pipelines.md#running-pipelines-with-io does not require KedroContext as it explains the concept of node and pipeline independent from KedroContext, but I would like to know which specific part of the documentation in `running-pipelines-with-io` section is causing your problem.

Also could you explain how https://github.com/quantumblacklabs/kedro/pull/60 is related to this issue?

**Comment by lorenabalan** [comment]
@Minyus did you find @921kiyo's answer helpful for your case? If not, could you please elaborate on the part that wasn't clear in documentation?

**Comment by 921kiyo** [comment]
I'm closing this, but please re-open it if this is still an issue.
