### ISSUE TITLE
Unable to install kedro 0.15.8 with Conda =4.9.0

### ISSUE THREAD

**Issue by JavierHernandezMontes** [quantumblacklabs/kedro#611]
## Description
When trying to install kedro from the docker image jupyter/scipy-notebook I get the following error: 

ERROR: Could not find a version that satisfies the requirement kedro==0.15.8 (from -r requirements.txt (line 60)) (from versions: 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.16.4, 0.16.5, 0.16.6)

The conda version used in that docker image is:  conda_version=4.9.0  and miniconda_version=4.8.3
## Context
How has this bug affected you? What were you trying to accomplish?
Install kedro

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

Trying to install the package in a docker image from jupyter/scipy-notebook 

* Kedro version used (`pip show kedro` or `kedro -V`):kedro==0.15.8 
* Python version used (`python -V`): 3.8.6
* Operating system and version: Ubuntu

**Comment by mzjp2** [comment]
What error do you get? What python version are you using? If you're using Python 3.8 and trying to install Kedro 0.15.8 then it won't work. Kedro only added Python 3.8 support in >=0.16

**Comment by JavierHernandezMontes** [comment]
Hello, you are correct, the version of python is 3.8.6. So installing it with 3.7 solved the issue
