### ISSUE TITLE
python3.8 is not supported for contributions to the spark related codebase

### ISSUE THREAD

**Issue by kislerdm** [quantumblacklabs/kedro#618]
## Description
The requirements file test_requirements.txt doesn't cover the case of py3.8+:

```python
pyspark~=2.2; python_version < '3.8'
```

## Context

If one would follow [the starter instructions](https://github.com/quantumblacklabs/kedro/blob/develop/CONTRIBUTING.md#first-time-one-off) to contribute to the spark related codebase using `python 3.8+` in the local env, the required dependency, `pyspark` won't be installed.

## Steps to Reproduce
1. Install [python 3.8+](https://www.python.org/downloads/) in your local virtual env, or spin up a docker container

```bash
docker run -v ${HOME}/.ssh:/root/.ssh -it python:3.8 /bin/bash
```

2. Clone [the kerdro repo](https://github.com/quantumblacklabs/kedro)

3. Follow [the "First time" instructions](https://github.com/quantumblacklabs/kedro/blob/develop/CONTRIBUTING.md#first-time-one-off)

4. Run the shell command in your local env, or inside a docker container

```bash
pip show pyspark | if [ $(wc -l) -eq 0 ]; then echo "FAIL"; else echo "OK"; fi
```

## Expected Result

After following the "Steps to Reproduce", "OK" shall appear on the screen/in stdout.

## Actual Result 

After following the "Steps to Reproduce", "FAIL" appeared on the screen/in stdout.

### Proposed Solutions

- Add `pyspark~=3.0; python_version >= '3.8'` to the `test_requirements.txt`. The drawback: possible problems with backwards compatibility of pyspark 3.* vs. pyspark 2.*.
- Adjust documentation for contributors to avoid using python3.8 as of yet.

## Your Environment

* Kedro version used (`pip show kedro` or `kedro -V`): null

* Python version used (`python -V`): 
```bash
Python 3.8.6
```

* Operating system and version: 
```yaml
-
 ProductName: "Mac OS X"
 ProductVersion: "10.15.7"
- 
 ProductName: "Debian GNU/Linux"
 ProductVersion: "10 (buster)"
```

**Comment by MerelTheisenQB** [comment]
Hi @kislerdm, thank you for bringing this to our attention! That sounds like a very reasonable request. You're more than welcome to make this contribution if you like, otherwise someone in the team will pick it up. 😊

**Comment by kislerdm** [comment]
Hi @MerelTheisenQB, thanks for reply. I'd go with the first proposed option and add `pyspark~=3.0` to the `test_requirements.txt`.
