### ISSUE TITLE
Add tagging to versioned datasets

### ISSUE THREAD

**Issue by louisdecharson** [quantumblacklabs/kedro#620]
## Description
Versioning of datasets is good but finding a specific version of the past is hard, because it's easier to remember plain words than timestamps.
I would like to be able to tag to datasets versions so that 
`kedro run --load-version="some_dataset:YYYY-MM-DDThh.mm.ss.sssZ"`
becomes
`kedro run --load-version="some_dataset:some_tag"`

## Context

I would use in order to tag specific versions of versioned datasets.

 Possibly, I could link the tag of the datasets to git tags so that I could data + code of a specific tag.

## Possible Implementation

Add a new CLI command `tag` that would work like that

1. Run `kedro tag <a_tag> --version="some_dataset:YYYY-MM-DDThh.mm.ss.sssZ"`
2. The command would : 
    1. Replace `YYYY-MM-DDThh.mm.ss.sssZ` by `a_tag` in all versioned catalog entries
    2. Create a new tag entry in yaml file (to be defined, a idea could be to use `tags.yml` in `conf/`) if a tag does not already exist.
Tag entry in this `tags.yml`file would look like
```yaml
a_tag: 
    timestamp: YYYY-MM-DDThh.mm.ss.sssZ
    created_at: a_timestamp
    last_modification: another_timestamp
    git_hash: aefedc # corresponding hash of git commit.
```

Things to pay attention to:
- Make sure that there is only one tag for one timestamp
- Issue warning if `kedro tag` is run but there is no versioned dataset in the `catalog`.

Nice to have:
- `--version="some_dataset:YYYY-MM-DDThh.mm.ss.sssZ"` would be optional and by default `kedro tag <a_tag>` would tag the latest version.
- `--git` would allow to also run `git tag <a_tag>` with the same tag name.

## Possible Alternatives

- Use shell variables KEDRO_MY_TAG="YYYY-MM-DDThh.mm.ss.sssZ" and use them in `kedro run -load-version="some_dataset:${KEDRO_MYTAG}"`
- Use `ProjectContext` `run()` method

**Comment by louisdecharson** [comment]
Easy implementation by superseding `ProjectContext._get_save_version()`

The idea is to retrieve the timestamp generated by the `_get_save_version()` method of `ProjectContext` and to have a dictionary saved in a `yaml` file mapping the generated timestamp and the tag. The dictionary is saved in a yaml file.
The `run()` method is then hijacked to insert the corresponding version timestamp if a tag is passed when `kedro run --load-version="models:a_tag"`  is ran. 

In this example, I am saving the version when I am running the `data_science` pipeline which is training my model.

In `run.py`  :

```python
from .kedro_tag_version import tag_version, retrieve_version_from_tag

class ProjectContext(KedroContext):
    tag_version = False

    def _get_save_version(self, *args, **kwargs):
        timestamp = super()._get_save_version(*args, **kwargs)
        if self.tag_version:
            tag = os.getenv("KEDRO_VERSION_TAG", None)
            new_tag = tag_version(timestamp, tag=tag, overwrite=True)
            logger.info(f"new tag {new_tag} for timestamp {timestamp}")
        return timestamp

    def run(self, *args, **kwargs):
        # Replace tag by timestamp
        load_versions = retrieve_version_from_tag(kwargs.get("load_versions", {}))
        kwargs['load_versions'] = load_versions
        # Trigger tag_version if pipeline is data_science
        if kwargs.get('pipeline_name', '') == "data_science":
            logger.info("Tag version activated")
            self.tag_version = True
        super().run(*args, **kwargs)      
```

`kedro_tag_version.py` file:

```python
from typing import Dict
from datetime import datetime
import os
from pathlib import Path
import yaml

VERSION_TAGS_FILE = Path("./version_tags.yml")

def tag_version(
        timestamp: datetime,
        tag : str = None,
        overwrite : bool = True) -> str:
    """map a tag with a version."""
    
    if VERSION_TAGS_FILE.is_file():
        with VERSION_TAGS_FILE.open() as f:
            tags = yaml.load(f, Loader=yaml.FullLoader)
    else:
        tags = {}
    if tag and tag in tags and not overwrite:
        logger.error(f"tag {tag} already exists and option overwrite set to False.")
        return None
    if not tag:
        if len(tags.keys()) > 0:
            latest_tag = sorted(tags.keys())[-1]
            tag = _increase_version(latest_tag)
        else:
            tag = "v0.0.1"
    tags[tag] = timestamp
    with open(VERSION_TAGS_FILE, mode="w") as f:
        f.write(yaml.dump(tags, sort_keys=False))
    return tag

def retrieve_version_from_tag(load_versions):
    if VERSION_TAGS_FILE.is_file():
        with VERSION_TAGS_FILE.open() as f:
            tags = yaml.load(f, Loader=yaml.FullLoader)
            for dataset, load_version in load_versions.items():
                if load_version in tags:
                    load_versions[dataset] = tags[load_version]
    return load_versions
        
    
def _increase_version(latest_tag):
    """Increase tag by one version."""
    latest_tag_parts = latest_tag.split('.')
    new_tag = ".".join(latest_tag_parts[0:-1]
                       + [str(int(latest_tag_parts[-1])+1)])
    return new_tag
```

**Comment by pedro-ricardo** [comment]
Hello there, I also use Kedro to build and deploy our models and I miss the possibility of controlling the version tag in versioned datasets .. like an specific string for example `v0.1.14`

I understand the default behavior of versioning this .. but I was hoping to use this as a version control for model deploy as well.

Was this incorporated somehow?

**Comment by pedro-ricardo** [comment]
Could this be reopen? Or should I create a new Issue and reference this one?

**Comment by lorenabalan** [comment]
Hi @pedro-ricardo , could you please open a new issue (& maybe just link it back to this one too)? We'd love to hear more about what your current workflow is, and we can move the conversation there. We are bringing experiment tracking to Kedro, so your insights might be very interesting for @MerelTheisenQB & @yetudada to hear. 😊
