### ISSUE TITLE
warning or exception when reading a pandas.ExcelDataSet with mixed type columns

### ISSUE THREAD

**Issue by clstaudt** [quantumblacklabs/kedro#621]
## Description
Raise a visible warning or optionally an exception when reading an ExcelDataSet with mixed type values in any column.

## Context
Mixed type columns are a typical data quality issue that cause pipelines to fail - however, often only further downstream, e.g. when performing transformations or exporting to a strictly typed format like Parquet.

## Possible Alternatives

`pandas_profiling` shows a warning for such columns ("Unsupported"), but this is a manual step that cannot easily be included in a pipeline. Kedro could support similar data sanity/quality checks.

**Comment by MerelTheisenQB** [comment]
Hi @clstaudt, thanks for bringing this up. Would you be able to elaborate a bit more on a possible implementation for this? Kedro itself helps you structure and build your ML pipeline, but I wouldn't expect it to do data profiling for you.

**Comment by clstaudt** [comment]
Profiling can be a lot of things, but why not check basic data type consistency and raise warnings?

I see that pandas has a warning that is raised from `pandas.read_csv`. Would that be visible in the Kedro log mesages when using the `pandas.CSVDataset`? 

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.errors.DtypeWarning.html

(I have not found a similar warning for `pandas.read_excel` though.)

**Comment by MerelTheisenQB** [comment]
The warning you've referenced above is actually raised when running a kedro pipeline. It won't stop the execution, but you'll see in the logs `DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.` when your dataset has mixed type columns. 

I don't think it's really Kedro's responsibility to check the data anymore than say pandas does.

**Comment by clstaudt** [comment]
Fair enough, since this is a common cause for failing pipelines I thought this might be in scope.

**Comment by yetudada** [comment]
Hi @clstaudt! We've actually thought about the issue of "bad data failing a pipeline" in a different way. Our recommended pattern is using another open-source project called [Great Expectations](https://greatexpectations.io/). You can validate your data using certain rules during a pipeline run. 

Issue #215 talks about how to integrates Great Expectations into your workflow. In our documentation [we recommend using Hooks to do this](https://kedro.readthedocs.io/en/stable/07_extend_kedro/04_hooks.html) and you can watch a video talking about this [here](https://www.youtube.com/watch?v=ntd6jnkC_o4&ab_channel=DataEngineerOne). 

I'm going to close this comment in the meanwhile and I hope this helps.

**Comment by clstaudt** [comment]
Thanks @yetudada, Great Expectations looks interesting, will check it it out.
