### ISSUE TITLE
Add Deltalake (delta.io) extra Dataset

### ISSUE THREAD

**Issue by xmehaut** [quantumblacklabs/kedro#622]
## Description
Adding a new extra dataset to handle Delta parquet format (delta.io)

## Context
When using Spark, we use more and more the Delta parquet format which is not only a parquet file but also gives ability to time travel or to change schema .

**Comment by MerelTheisenQB** [comment]
Hi @xmehaut, thanks for the suggestion. I've logged the request for it internally, however no timeline can be provided at this time. If this is something of high importance for you, please feel free to go ahead and [contribute this feature](https://github.com/quantumblacklabs/kedro/blob/master/CONTRIBUTING.md#contribute-a-new-feature) to Kedro 🙂

**Comment by andrii-ivaniuk** [comment]
Hi @xmehaut,

I'm wondering if you could use `SparkDataSet` for this purpose as follows:

```python
import pyspark
from kedro.extras.datasets.spark import SparkDataSet

# Start the Spark session first with the Delta Lake package
spark_sess = pyspark.sql.SparkSession.builder.appName("MyApp") \
    .config("spark.jars.packages", "io.delta:delta-core_2.12:0.7.0") \
    .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension") \
    .config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog") \
    .getOrCreate()

# Use `SparkDataSet` to save/load data to/from delta table
data = spark_sess.range(0, 5)

data_set = SparkDataSet(filepath="/tmp/delta-table", file_format="delta")
data_set.save(data)
reloaded = data_set.load()

data.show()
reloaded.show()
```

Is this what you need?

**Comment by xmehaut** [comment]
Thanks
Yes it could do the job
Best regards

Envoyé de mon iPhone

**Comment by andrii-ivaniuk** [comment]
Can I close the issue?

**Comment by xmehaut** [comment]
Yep
Thanks

Envoyé de mon iPhone
