### ISSUE TITLE
Getting 404 error on downloading spaceflights tutorial's data files

### ISSUE THREAD

**Issue by guludo** [quantumblacklabs/kedro#623]
## Description
Trying to [download data files](https://kedro.readthedocs.io/en/stable/03_tutorial/03_set_up_data.html#add-your-datasets-to-data) for the spaceflights tutorial fails with 404 errors.

## Context
I was doing the tutorial and got 404 errors when doing the data setup step.

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): `0.16.6`
* Python version used (`python -V`): `3.8.5`
* Operating system and version: `Arch Linux`

**Comment by guludo** [comment]
By the way, that happens when trying to download the files with the `curl` commands. The links displayed before the command work fine.

**Comment by lorenabalan** [comment]
Closing this as resolved through linked PR. Just for future reference, key words like "close" or "resolve" next to issue number will automatically close the related issue when PR is merged. :D

**Comment by guludo** [comment]
> Just for future reference, key words like "close" or "resolve" next to issue number will automatically close the related issue when PR is merged. :D

Cool tip. Thanks! :-)
