### ISSUE TITLE
[KED-2327] Validate if argument match existing dataset in catalog

### ISSUE THREAD

**Issue by noklam** [quantumblacklabs/kedro#627]
## Description
kedro run --load-version=unexist_dataset:123

## Context
If a dataset name does not match with the catalog, it will just ignore the argument and always getting the latest version of data. This could be hard to notice since the pipeline will still run successfully.

I experienced this as one of my teammates rename the dataset and forgot to change it in the run configuration yml.

## Expected Result
I expected any argument passed into kedro command or --config=xxx.yml should be validated, otherwise it should stop the run.

## Actual Result
pipeline runs with invalidate config successfully.

```
-- If you received an error, place it here.
```

```
-- Separate them if you have more than one.
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.16.6
* Python version used (`python -V`):
* Operating system and version:

**Comment by yetudada** [comment]
Thank you for flagging this @noklam! We'll look into this bug.
