### ISSUE TITLE
Tracking node/pipeline progress

### ISSUE THREAD

**Issue by guludo** [quantumblacklabs/kedro#628]
## Description
I'm brand new to Kedro and have not found yet in the documentation built-in support for tracking progress of nodes or pipelines. I was wondering if that is a feature Kedro already has or if it is on the project's roadmap.

## Context
My team currently have been working on an application for processing large text sequences and, after discovering this awesome project, I would like to migrate the code to use Kedro. One thing that is important for us is to be able to track the progress so that we can provide that info to the end user.  I think being able to track progress of nodes or pipelines would be a really nice feature for Kedro.

**Comment by yetudada** [comment]
Hi @guludo! We're so glad you've joined Kedro. Let me know if you have any feedback about it so far? 

And then, if I play back what you want to do, you want a way to track the progress of a Kedro run? What interfaces would your end user have access to while this run is happening?

**Comment by guludo** [comment]
Hi @yetudada!

Our application is a textual classification tool and is composed by three major components: (i) the classification service; (ii) the web server; and (iii) the front-end app. The end user interfaces with our application via the front end. The user selects a (possibly large) set of textual documents that have been previously uploaded and requests the classification of such documents. Upon the classification request, the web server makes an asynchronous call to the classification service to process the documents. While the classification service is processing the documents, it periodically sends back to the web server the progress information (i.e., how much of the whole process is done). That progress information is presented to the end user with a progress bar in the front-end app.

I hope that answers you question. Feel free to ask for more details :slightly_smiling_face:

### Implementation Idea

I would like to contribute by sharing an implementation idea.

I have started a very simple implementation of a workflow executor module that allows providing progress feedback. The idea is to use this implementation until we are able to replace it with Kedro. In such implementation, I solved the progress feedback problem by having each execution unit (which is analogous to Kedro nodes) having the following features:

1. A method to update the progress of the units execution, which receives as parameter a float between 0 and 1 representing the current execution progress of such unit. This method updates a private variable and calls a progress callback function if any is set for the unit;
2. An instance variable to represent the unit's "progress weight". Since not all units have the same CPU load, the developer might set different values for this variable so that units that take longer to execute have a higher progress weight than others that are lighter.

In the implementation there is a special kind of unit called `Workflow`, which is analogous to Kedro's pipelines. While user units can customize the progress weight and are responsible for calling the update method if the unit is supposed to provide the progress feedback, the workflow units:

1. Automatically update their progress weight to be the sum of the weights of its children units;
2. Automatically call the update method whenever a child unit updates it's progress info. In order to have a progress value between 0 and 1, the workflows progress value is defined by the following: `(w_1*p_1 + w_2*p_2 + ... + w_n*p_n) / (w_1 + w_2 + ... + w_n)`, where `n` is the number of child units, and `w_i` and `p_i` are the progress weight and progress value of the `i`-th child unit, respectively.

**Comment by yetudada** [comment]
Thanks for this explanation! Kedro only provides Python logging as a way to track the progress of a run. We look at other tools like [Prefect](https://kedro.readthedocs.io/en/stable/10_deployment/05_prefect.html), [Argo](https://kedro.readthedocs.io/en/stable/10_deployment/04_argo.html) or even [Grafana](https://kedro.readthedocs.io/en/stable/07_extend_kedro/02_hooks.html#hooks-examples) to provide run monitoring because they are great at doing this. I'm going to close this issue. Please feel free to re-open it if you have any other concerns and I hope you've had a great time using Kedro if you picked it up.
