### ISSUE TITLE
pyarrow 0.14.0 in Google Colab is not supported

### ISSUE THREAD

**Issue by Minyus** [quantumblacklabs/kedro#63]
## Description
Kedro requires pyarrow==0.12.0 and does not support pyarrow 0.14.0.

## Context
Google Colaboratory is a free cloud-based Jupyter-like environment but comes with pyarrow 0.14.0 which is not supported by Kedro.

![image](https://user-images.githubusercontent.com/33908456/61734994-9874fb80-adb5-11e9-8c3c-2ff4d04f9fec.png)

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): the latest build in develop branch (pre-0.15.0)
* Python version used (`python -V`): 3.6.8
* Operating system and version: Ubuntu 18.04.2 LTS in Google Colab

**Comment by yetudada** [comment]
Thanks for raising this @Minyus! I've placed this pinning problem on our backlog and will get back to you.

**Comment by LorenaBalanQB** [comment]
Hi @Minyus, thank you for spotting this! I will go ahead and close the issue, as it was fixed by this commit here: https://github.com/quantumblacklabs/kedro/commit/bceed9693add3668cce5043956bf2e688d0f9db0. It will be available in the next version of Kedro.
