### ISSUE TITLE
node input validation fails when using combination of args and varargs with partial

### ISSUE THREAD

**Issue by kretes** [quantumblacklabs/kedro#633]
## Description
Kedro fails when combining varargs method with partial on one of the static arguments

## Steps to Reproduce
The following code:
```
from functools import partial
from kedro.pipeline import Pipeline, node

def something_and_varargs(arg1, arg2, *args):
    print(arg1, arg2, *args)     
    
node(partial(something_and_varargs, arg1="arg1"),
     inputs=["arg2","vararg"],
     outputs=None
)
```

BTW - the same happens if i wrap partial with the method from http://louistiao.me/posts/adding-__name__-and-__doc__-attributes-to-functoolspartial-objects/

## Expected Result
This should call method `something_and_varargs` with positional arguments ["arg1", "arg2", "vararg"]

at minimum I should be able to specify 'skip validation' for this node parameters if this is impossible to validate

## Actual Result
Fails with
```
~/.conda/envs/kiakia-ai-env/lib/python3.8/site-packages/kedro/pipeline/node.py in node(func, inputs, outputs, name, tags, confirms, namespace)
    663         >>> ]
    664     """
--> 665     return Node(
    666         func,
    667         inputs,

~/.conda/envs/kiakia-ai-env/lib/python3.8/site-packages/kedro/pipeline/node.py in __init__(self, func, inputs, outputs, name, tags, decorators, confirms, namespace)
    120             )
    121 
--> 122         self._validate_inputs(func, inputs)
    123 
    124         self._func = func

~/.conda/envs/kiakia-ai-env/lib/python3.8/site-packages/kedro/pipeline/node.py in _validate_inputs(self, func, inputs)
    551                     func, follow_wrapped=False
    552                 ).parameters.keys()
--> 553                 raise TypeError(
    554                     "Inputs of function expected {}, but got {}".format(
    555                         str(list(func_args)), str(inputs)

TypeError: Inputs of function expected ['arg1', 'arg2'], but got ['arg2', 'vararg']
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`):
```
pip show kedro
Name: kedro
Version: 0.16.4
Summary: Kedro helps you build production-ready data and analytics pipelines
Home-page: https://github.com/quantumblacklabs/kedro
Author: QuantumBlack Labs
Author-email: None
License: Apache Software License (Apache 2.0)
Location: ###
Requires: anyconfig, jmespath, pip-tools, python-json-logger, cachetools, fsspec, setuptools, pluggy, toposort, click, cookiecutter, PyYAML, jupyter-client
Required-by: kedro-viz, kedro-pandera, kedro-mlflow, kedro-docker
```
* Python version used (`python -V`): Python 3.8.5
* Operating system and version:  Linux

**Comment by deepyaman** [comment]
@kretes You can't fill specific positional arguments with `partial` in Python. See https://stackoverflow.com/a/7811270/1093967 for a more complete explanation.

You can try this yourself without using Kedro:

```py
from functools import partial
from kedro.pipeline import Pipeline, node


def something_and_varargs(arg1, arg2, *args):
    print(arg1, arg2, *args) 

partial(something_and_varargs, arg1="arg1")(3,6)
```

You should get:

```py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: something_and_varargs() got multiple values for argument 'arg1'
```

**Comment by kretes** [comment]
Ok, you are right. I went into the solution of 'partial' as a workaround for missing 'literal': see https://github.com/quantumblacklabs/kedro/issues/526

I think my case is an argument for something that partial cannot do, but we could get with a 'kedro literal':

whatever the syntax but then it would look like:

```
node(
    something_and_varargs,
     inputs=[ lit:"arg1", "arg2", "vararg"],
     outputs=None
)
```

and the whole node call could go without relying on partial, right?

**Comment by lorenabalan** [comment]
I'll close this issue in favour of #526 . However, note that any future `literal` implementation would still very likely rely on Python `partial` behaviour so I'd expect the function signature would have to change to make it work even in the kedro native way.
