### ISSUE TITLE
[KED-923] Request for YAMLLocalDataset

### ISSUE THREAD

**Issue by Minyus** [quantumblacklabs/kedro#64]
## Description
YAML file format is apparently not supported by kedro.io.

## Context
It is common to load parameters from YAML file and Kedro supports this, but parameters are often modified/imputed during initialization, and it is useful to *save* the modified parameters as a part of reporting.

Unfortunately, YAML is apparently not supported by kedro.io according to the lists at https://kedro.readthedocs.io/en/latest/kedro.io.html#data-sets and https://kedro.readthedocs.io/en/latest/kedro.contrib.io.html

## Possible Implementation
Add a subclass of `kedro.io.AbstractDataSet` as `YAMLLocalDataset`.

**Comment by yetudada** [comment]
Hi @Minyus, thank you so much for submitting this issue. Could you tell me a bit more about your parameters workflow? 

Adding support for YAML file formats is something we could have as part of `kedro.contrib.io` and we will be more than happy to welcome contributions for the IO class. I will mark this with a `good first issue` label, so anyone can pick it up.

**Comment by Minyus** [comment]
Hi @yetudada,

My Python package handles lots of parameters.
If not specified, the default values are used.
One of parameters is which columns to use as the feature for the Machine Learning model, and if not specified, all the columns except specific ones are used.
Another possible parameter processing is clipping values to specific range.
It is convenient to save all the final parameters (including default values, specified by users, specified but clipped) in a yaml file so users can use it to report or manually modify it to use as the revised config file.

You can see how Kedro is used in my package here:
https://github.com/Minyus/causallift

You can try the demo here:
https://colab.research.google.com/github/Minyus/causallift/blob/v1.0/notebooks/demo/CausalLift_demo.ipynb

I implemented YAMLLocalDataSet in contrib and sent a pull request at:
https://github.com/quantumblacklabs/kedro/pull/66

**Comment by lorenabalan** [comment]
Closed by #69
