### ISSUE TITLE
Support TFRecord(Tensorflow) as a DataSet

### ISSUE THREAD

**Issue by RAbraham** [quantumblacklabs/kedro#640]
## Description

The TFRecord format in Tensorflow is a simple format for storing a sequence of binary records. A tutorial is [here](https://www.tensorflow.org/tutorials/load_data/tfrecord).

Can we support TFRecord in Kedro?

## Context
We deal with a lot of images. So Kedro supporting this format would be really useful(and make it easier to sell it our data scientists :) )

If there is an alternative, please let me know. Thanks

**Comment by yetudada** [comment]
Thanks for raising this @RAbraham! TFRecord looks like it would be a great addition to Kedro. We'd recommend creating a [custom dataset implementation](https://kedro.readthedocs.io/en/stable/07_extend_kedro/03_custom_datasets.html) and creating a PR for Kedro. 

At this point, we only support a [TensorflowDataset](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.tensorflow.TensorFlowModelDataset.html#kedro.extras.datasets.tensorflow.TensorFlowModelDataset) so this could make a lovely addition. I'll mark this ticket with the `Request: Help Wanted` tag to indicate that we're looking for contributions.
