### ISSUE TITLE
Missing run_params in after_catalog_created hook

### ISSUE THREAD

**Issue by maria-olivia-lihn** [quantumblacklabs/kedro#642]
Hi ! I had the same issue with `run_params` and `journals`. Is it possible to add them to Hook spec? I am looking to use `run_params` in `after_catalog_created`

_Originally posted by @maria-olivia-lihn in https://github.com/quantumblacklabs/kedro/issues/571#issuecomment-745539614_

**Comment by limdauto** [comment]
@maria-olivia-lihn Could you explain your use case a little more? Maybe there are other solutions to your problem. Coupling `run_params` and the catalog's lifecycle isn't ideal.

**Comment by maria-olivia-lihn** [comment]
Sure! We have a modular pipeline that is used for two cases: simulation and tracking. The issue is that we need to change a parameter so the node nows if it is running a simulation or tracking. As an example: we have a node that gives the output. For simulation the output must be the whole dataframe that was simulated, but for tracking we only need the last row. We tried using a parameter but it has been a pain because each time we want to change the pipeline that we are running, we must change the parameter y the parameter's file. So my approach was to change the parameter using the name of the pipeline that was run. 
I tried changing the parameter using the modular pipeline approach, but it still asks for another parameter instead of a value (would me much easier to say for example: `pipeline(simulation_pipeline, inputs={...}, outputs={...}, parameters={'key_parameter': True})` but that didn't work.

**Comment by limdauto** [comment]
@maria-olivia-lihn Is it possible for you to have 2 different pipelines and just supply the parameters at run time, something like

```
kedro run --pipeline=simulation --params "key_parameter:True"
kedro run --pipeline=tracking --params "key_parameter:False"
```

**Comment by lorenabalan** [comment]
@maria-olivia-lihn did @limdauto 's suggestion solve your use case? As mentioned before, we don't recommend tight links between `run_params` and the data catalog. I'm not sure I followed the example closely, but separate pipelines or separate environments are usually the typical solution here.

**Comment by maria-olivia-lihn** [comment]
Hi @lorenabalan! We went with @limdauto's suggestion and I understand avoiding the tight links, makes sense. The idea was not to have many different pipelines so adding the parameter and changing it when running made more sense. Thanks!

**Comment by lorenabalan** [comment]
Great, I'll close this as resolved then! 😊
