### ISSUE TITLE
spaceflight tutorial: broken links to data in readthedocs.io

### ISSUE THREAD

**Issue by mcbeem** [quantumblacklabs/kedro#645]
## Description

[Issue 624](https://github.com/quantumblacklabs/kedro/pull/624) identified broken data download links in the spaceflight tutorial. The issue was closed 19 days ago.

The links have been updated in the version of the tutorial that is hosted in [the github repo](https://github.com/quantumblacklabs/kedro/blob/master/docs/source/03_tutorial/03_set_up_data.md). However, the [version at readthedocs.io](https://kedro.readthedocs.io/en/stable/03_tutorial/03_set_up_data.html) still includes the broken download links.

**Comment by lorenabalan** [comment]
Hi @mcbeem that's because the change is only available on `latest` docs on Read The Docs: https://kedro.readthedocs.io/en/latest/03_tutorial/03_set_up_data.html 

The change will flow into `stable` once we've completed a release.

**Comment by lorenabalan** [comment]
Closing this as resolved. You should see the update on `stable` at some time today. Meanwhile feel free to use the `latest` links. :)
