### ISSUE TITLE
[KED-2357] `kedro new` shouldn't request Python package name if using `mini-kedro` starter

### ISSUE THREAD

**Issue by deepyaman** [quantumblacklabs/kedro#646]
## Description
The `mini-kedro` starter doesn't include a Python package, so it's confusing to ask for one.

Also, why does it include the Iris example? :(

## Context
Why is this change important to you? How would you use it? How can it benefit other users?

## Possible Implementation
(Optional) Suggest an idea for implementing the addition or change.

## Possible Alternatives
(Optional) Describe any alternative solutions or features you've considered.

**Comment by limdauto** [comment]
Hi @deepyaman, thank you for this great catch. Will fix the CLI experience for `mini-kedro` going forward.

Regarding the iris example, the original idea was for users to explore that dataset and maybe later on transition to `panda-iris`. Do you have any suggestion for a better approach?

**Comment by deepyaman** [comment]
> Regarding the iris example, the original idea was for users to explore that dataset and maybe later on transition to panda-iris. Do you have any suggestion for a better approach?

@limdauto I tried `mini-kedro` because I wanted to explore some data in notebooks, and I liked the idea of not generating the whole pipeline structure because I didn't intend to transition to it in this case. Knowing that, I think I should have an option to include the example or not, either via a y/N question or by differentiating `mini-kedro` and `mini-pandas-iris` starters (obviously, the latter means even more starter proliferation).

**Comment by andrii-ivaniuk** [comment]
`mini-kedro` starter was updated and know it doesn't ask `package name`.

**Comment by MerelTheisenQB** [comment]
Hi @deepyaman, this has now been changed and all starter can have custom prompts suitable for the starter. (See https://kedro.readthedocs.io/en/stable/07_extend_kedro/05_create_kedro_starters.html#configuration-variables for more details)
