### ISSUE TITLE
Support Compression in pickle.PickleDataSet

### ISSUE THREAD

**Issue by lou-k** [quantumblacklabs/kedro#655]
## Description
I often use `pickle.PickleDataSet` to save datasets between nodes when there isn't a clear container for the object type (a tuple of nd arrays, for example). This is convenient, but the files are often very large (hundreds of megabytes) and compressing them (with gzip, etc) would be advantageous. 

## Context
Such a change would allow users to have a trade off between disk space and cpu on load and save.

## Possible Implementation
Such a change could be introduced between the serialization backend and the filesystem handler.

## Possible Alternatives
I've considered packaging them into pandas frames which support compression, but it's not very elegant.

**Comment by andrii-ivaniuk** [comment]
Hi @lou-k,

You can try to use `pickle.PickleDataSet` with `joblib` backend which natively supports compression: https://joblib.readthedocs.io/en/latest/generated/joblib.dump.html

```python
from kedro.extras.datasets.pickle import PickleDataSet
data_set = PickleDataSet(filepath="test.pkl", backend="joblib", save_args={"compress": True})
```

**Comment by andrii-ivaniuk** [comment]
Also, we are going to add `compress_pickle` backend to `pickle.PickleDataSet`. The PR is in review: [534](https://github.com/quantumblacklabs/kedro/pull/534)

**Comment by lou-k** [comment]
oh awesome, thanks for the workaround and the heads up on the PR!
