### ISSUE TITLE
VersionNotFoundError when using versioned tensorflow model in azure blob storage

### ISSUE THREAD

**Issue by ethan-stone** [quantumblacklabs/kedro#661]
## Description
Creating a simple pipeline and I have been stuck on an issue using versioned tensorflow models stored in azure blob storage. Can't track down the cause and new to kedro.

Should note that I checked in blob storage to see if it does upload correctly and it does. 
## Context
How has this bug affected you? What were you trying to accomplish?
Create a simple pipeline. New to kedro just want to learn it for a project. 

## Steps to Reproduce
1. Add node to train tensorflow model and save it
2. Add node to load the model and evaluate it
3. Loading the model throws an error that version is not found

## Expected Result
The pipeline should run from data collection to formatting to training to evaluating successfully. 

## Actual Result
VersionNotFoundError thrown

```
kedro.io.core.VersionNotFoundError: Did not find any versions for TensorFlowModelDataset(filepath=models/elbow_model, load_args={}, protocol=abfs, save_args={'save_format': tf}, version=Version(load=None, save='2021-01-06T03.31.18.632Z'))

```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.17.0
* Python version used (`python -V`): 3.8.5
* Operating system and version: Windows 10 Home 19042.685

**Comment by yetudada** [comment]
Hi @ethan-stone! I hope that you're well. Are you still struggling with this issue?

**Comment by MerelTheisenQB** [comment]
Hi @ethan-stone I'm closing this issue, but feel free to re-open if you still need help with this.
