### ISSUE TITLE
Inconsistency in pipeline hook specification and journal documentation/implementation

### ISSUE THREAD

**Issue by mzjp2** [quantumblacklabs/kedro#685]
## Description
Looking at the documentation for the `run_params` in the [pipeline specification hook](https://kedro.readthedocs.io/en/stable/kedro.framework.hooks.specs.PipelineSpecs.html#kedro.framework.hooks.specs.PipelineSpecs.after_pipeline_run) the schema is specified as:

```python
{
  "run_id": str
  "project_path": str,
  "env": str,
  "kedro_version": str,
  "tags": Optional[List[str]],
  "from_nodes": Optional[List[str]],
  "to_nodes": Optional[List[str]],
  "node_names": Optional[List[str]],
  "from_inputs": Optional[List[str]],
  "load_versions": Optional[List[str]],
  "pipeline_name": str,
  "extra_params": Optional[Dict[str, Any]]
}
```

and says it "should be identical to the data logged by Journal". The [journal section of the documentation](https://kedro.readthedocs.io/en/stable/08_logging/02_journal.html#context-journal-record) however says:

```json
{
    "type": "ContextJournalRecord",
    "run_id": "2019-10-01T09.15.57.289Z",
    "project_path": "<path-to-project>/src/kedro-tutorial",
    "env": "local",
    "kedro_version": "0.17.0",
    "tags": [],
    "from_nodes": [],
    "to_nodes": [],
    "node_names": [],
    "from_inputs": [],
    "load_versions": {},
    "pipeline_name": null,
    "extra_params": {},
    "git_sha": "48dd0d3"
}
```

which seems to contradict the schema. Looking at the actual implementation, here is an example of `run_params` in a hook printed out:

```python
{
 'env': 'local',
 'extra_params': {},
 'from_inputs': [],
 'from_nodes': [],
 'kedro_version': '0.17.0',
 'load_versions': {},
 'node_names': (),
 'pipeline_name': None,
 'project_path': '/Users/zain_patel/code/kedro/yo',
 'run_id': '2021-02-06T14.51.09.986Z',
 'tags': (),
 'to_nodes': []
}
```

Should this the schema for `run_params` in the hook specification really be:

```python
{
  "run_id": str,
  "project_path": str,
  "env": str,
  "kedro_version": str,
  "tags": Tuple[str],
  "from_nodes": List[str],
  "to_nodes": List[str],
  "node_names": Tuple[str],
  "from_inputs": List[str],
  "load_versions": Dict[str, str],
  "pipeline_name": Optional[str],
  "extra_params": Dict[str, Any]
}
```

in particular, note that nothing is really optional, since things default to empty lists/tuples/dicts rather than `None` (if my understanding of `Optional` is correct), that some lists should in fact be tuples (e.g `tags`) or dictionaries (`load_versions`)?

Is my understanding here correct, or (very possible) have I confused myself? If correct, am happy to open a PR with the fixes.

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): Kedro 0.17.0
* Python version used (`python -V`): 3.7.9
* Operating system and version: MacOS 0.15.7

**Comment by limdauto** [comment]
Hey thanks for reporting this @mzjp2 You are right! They have definitely gone out of sync. I think we should just remove the mention in the doc that the hook spec params and the journal schema must be in sync. Generally, the hook spec params should be the source of truth, as we will remove the journal soon.
