### ISSUE TITLE
Possible bug with S3a credential set up

### ISSUE THREAD

**Issue by ppvastar** [quantumblacklabs/kedro#686]
## Description
If I use S3a credential for SparkDataSet in the format as the same as that for normal S3 connection:

```
dev_s3:
  client_kwargs:
    aws_access_key_id: XXX
    aws_secret_access_key: yyy
    
```
there will be error: 

**client() got an unexpected keyword argument 'client_kwargs'.**

After removing this level of key, this error has been removed but connection to S3a will actually fail with credential related error:
  
**com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden....**

Following the instruction here, 
https://kedro.readthedocs.io/en/stable/_modules/kedro/extras/datasets/spark/spark_dataset.html#SparkDataSet
changing keyword arguments to be "key" and "secret", again, there will be error: 

**client() got an unexpected keyword argument 'key'.**

Kedro version: 0.16.5

Question is:

How to correctly set up credential for S3a? Is there a bug in the current version?

**Comment by willashford** [comment]
For spark, I think you need to change to the following (you may need to make a different credentials configuration specifically for spark here). 
```
dev_s3:
    aws_access_key_id: XXX
    aws_secret_access_key: yyy
```

Note that a more secure solution is usually to store your access keys and secrets as environment variables and remove references to config-based credentials for your datasets.

**Comment by lorenabalan** [comment]
Closing this as answered, please feel free to raise a new issue if you encounter problems.
