### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by willashford** [quantumblacklabs/kedro#689]
## Description
Link to the release notes in the readthedocs is broken. 

## Steps to Reproduce
1. visit https://kedro.readthedocs.io/en/stable/12_faq/01_faq.html?highlight=0.17.0#how-do-i-upgrade-kedro
2. Try to click the release notes. 

## Expected Result
I should be taken to the release notes. 

## Actual Result
404.

**Comment by lorenabalan** [comment]
Hi @willashford , this was fixed on `master` (see https://kedro.readthedocs.io/en/latest/12_faq/01_faq.html?highlight=0.17.0#how-do-i-upgrade-kedro), and will be there in `stable` with the next release.

**Comment by willashford** [comment]
🎉
