### ISSUE TITLE
Unable to use Google Cloud Storage for datasets

### ISSUE THREAD

**Issue by ethan-stone** [quantumblacklabs/kedro#691]
## Description
Trying to setup kedro with google cloud storage. At first I felt that my credentials were simply incorrect since I am new to the cloud in general so I wasn't sure what an id token was. But I have tried a number of different things for credentials including just using the file path to the json and using the google cloud sdk to create an id token for my service account. The steps to reproduce is my most recent attempt.

## Steps to Reproduce
1. Create simple pipeline that uses google cloud somehow
2. Add credentials for google cloud. I created a service account for my storage and then used the google cloud sdk to produce an id token using the following commands. gcloud auth activate-service-account --key-file=key.json and gcloud auth print-identity-token
3. Run the pipeline. Get error where you do not have access to Google Cloud Storage object

## Expected Result
Pipeline should run completey

## Actual Result
Produces an error that I do not have access to Google Cloud Storage object

```
kedro.io.core.DataSetError: Failed while loading data from data set JSONDataSet(filepath=coachneuromlbucket/raw-json-data/basketball/front_legs.json, load_args={}, protocol=gcs, save_args={}).
Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.17.0
* Python version used (`python -V`):  3.8.7
* Operating system and version: Windows 10 Home 19042.746

**Comment by 96imranahmed** [comment]
Hey Ethan, were you able to solve your issues? 

I was able to set something up by simply setting-up the configs below. Only needed to run `gcloud auth activate-service-account --key-file=key.json` (no need to run `gcloud auth print-identity-token`). 

In `catalog.yml`: 
```
Dataset_Name:
      type: pandas.CSVDataSet
      filepath: gcs://my_gcp_bucket/file/path.csv
      credentials: gcp_file_store_creds
      fs_args:
          project: my_gcp_project
      load_args:
        sep: ','
```

  
In `credentials.yml`:
```
gcp_file_store_creds:
  token: /Link/To/my_service_account.json
```

Let me know if this works!

**Comment by lorenabalan** [comment]
@ethan-stone , any luck with following @96imranahmed 's suggestion? If so, please consider closing this issue. 🙂

**Comment by ethan-stone** [comment]
Yes sorry I was able to figure it out. Will close this
