### ISSUE TITLE
TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by khuyentran1401** [quantumblacklabs/kedro#694]
## Description
When using list as one of the inputs, I got this error

## Context
I tried to pass a string and a list to the function, but I cannot. This will prevent me from passing any list as an argument to my function.

## Steps to Reproduce
When I run this code
```python
a = 'string'
b = [1,2,3]

def dummy_func(a, b):
   return 'hello'

data_catalog = DataCatalog({'events': MemoryDataSet()})
dummy_func_node =  node(func=dummy_func, inputs=[a, b], outputs='events')
pipeline = Pipeline([dummy_func_node])
runner = SequentialRunner()
print(runner.run(pipeline, data_catalog))
```
I got
```bash
Traceback (most recent call last):
  File "src/get_events.py", line 66, in main
    dummy_func_node =  node(func=dummy_func, inputs=[a, b], outputs='events')
  File "/home/khuyentran/anaconda3/envs/scraping/lib/python3.8/site-packages/kedro/pipeline/node.py", line 665, in node
    return Node(
  File "/home/khuyentran/anaconda3/envs/scraping/lib/python3.8/site-packages/kedro/pipeline/node.py", line 133, in __init__
    self._validate_inputs_dif_than_outputs()
  File "/home/khuyentran/anaconda3/envs/scraping/lib/python3.8/site-packages/kedro/pipeline/node.py", line 570, in _validate_inputs_dif_than_outputs
    common_in_out = set(self.inputs).intersection(set(self.outputs))
TypeError: unhashable type: 'list'
```

I looked at the source code, and it seems like this error is due to the fact that there will be an error if you take a set of a list of list in `common_in_out = set(self.inputs).intersection(set(self.outputs))`. I wonder if kedro provides any option when one of the inputs is a list?

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used: 0.16.4
* Python version used: Python 3.8.3
* Operating system and version: Ubuntu 19.10

**Comment by mzjp2** [comment]
Are you trying to pass in a `literal` list `[1,2,3,4]` into your node? If so, this might be helpful: https://stackoverflow.com/questions/58875820/how-to-pass-a-literal-value-to-a-node

**Comment by limdauto** [comment]
@mzjp2 is correct. The mental model here is: the `node(...)` function receives a collection of dataset names as inputs and outputs, not the values themselves.

**Comment by khuyentran1401** [comment]
Got it! Got it to work. Thank you for the help!

**Comment by khuyentran1401** [comment]
Before I close this issue, is there any way to use a node with a class? For example, if the class is like this
```python
from kedro.pipeline import node, Pipeline

class MyClass:
   def __init__(self, some_var):
       self.some_var = some_var

   def do_something(self):
       return 'hello'
```

I want to insert a variable to `MyClass`, not `do_something`, so probably I cannot do this

```python
node(MyClass.do_something, input='some_var', ouput='some_output')
```

What is a way that I can approach this?

**Comment by mzjp2** [comment]
Indeed, the example you gave (as you correctly pointed out) doesn't really make sense, since `MyClass.do_something` is missing the class instance as its first argument (it's an _unbound_ method). You might need to expand on what you're really trying to achieve here, but as it stands:

1. If you're using a class because you want to save some state on the instance, this sounds like a bit of an antipattern but you'd be able to get away with it like so:

```python
my_class = MyClass()

node(my_class, input="some_var", output="some_output")
```

but this is a bad patter for many reasons (creating a class instance at `import` time for one!)

2. If you just want the class for the semantics/namespace (you should probably use a module, really) then you could make the method a `@staticmethod` and use it exactly like you did in your example, so that it's not expecting a class instance to be bound to.

```python
class MyClass:
  @staticmethod
  def do_something(some_input):
    # note: you have no access to self here, so if you wanted to save and use state on the instance
    # you can't do that with the state instance
    pass

node(MyClass.do_something, inputs="blah", outputs="blah")
```

I suspect you're angling for `1` and trying to _save_ state on the instance across different nodes, which I'd heavily recommend against, this breaks Kedro's philosophy of nodes not having side effects, to keep your mental model easy to reason with. Instead, pass data through your nodes by using transient `MemoryDataSet`'s, e.g:


```python
node(my_func, inputs="a", outputs="b") # a needs to exist in your catalog
node(my_func_2, inputs="b", outputs="c")

# b does not need to exist in your catalog, Kedro passes it along in memory
# even though it's not referencing something in your catalog. Though if you did
# reference it in your catalog, then it'd be `save`'d and `load`ed according to your dataset.
```

**Comment by khuyentran1401** [comment]
Thank you for your detailed feedback! Since you said Kedro's philosophy of nodes not having side effects, is that the case that Kedro discourages using class and the Pipeline is used instead?

**Comment by mzjp2** [comment]
Yes, typically you’d like your nodes to remain pure and pass information between them (using the catalog) rather than maintaining state yourself!

**Comment by khuyentran1401** [comment]
Got it! I think [this one](https://kedro.readthedocs.io/en/stable/06_nodes_and_pipelines/03_modular_pipelines.html) provides a good example of how to create modular pipelines. You might want to fix the broken image on this website. This should give me enough information to experiment more with Kedro. Thank you for the help!
