### ISSUE TITLE
[KED-2475] Version of .whl file generated with `kedro pipeline package`

### ISSUE THREAD

**Issue by mkretsch327** [quantumblacklabs/kedro#699]
## Description
When packaging a modular pipeline, I'd like the version of that packaged pipeline to be taken from the `__init__.py` present in the source code folder for that pipeline. From what I can tell/see the version for the packaged pipeline is either taken from the overall kedro project version or from a user-specified value through CLI.

This can be confusing if some pipelines are developed faster than others, requiring differing version numbers. A natural place to store this information would be in the pipeline's `__init__.py`.

## Context
I've developed a few modular pipelines, and would like to version them independently.

## Steps to Reproduce
1. Create a modular pipeline, `pipeline1`
2. run `kedro pipeline package pipeline1`
3. inspect generated .whl file.

## Expected Result
The .whl file's version matches what's in `__init__.py`.

## Actual Result
The .whl file version matches the overall kedro project version if present.

```
-- If you received an error, place it here.
```

```
-- Separate them if you have more than one.
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`):
* Python version used (`python -V`):
* Operating system and version:

**Comment by lorenabalan** [comment]
Hi @mkretsch327 , thank you for raising - this has been enabled in 0.17.4 https://github.com/quantumblacklabs/kedro/commit/41d1650bd259ed1116ef87d95a36ecb37f37c15c and made standard for 0.18.0 https://github.com/quantumblacklabs/kedro/commit/3c63f27fc31a1fc3814fba591194be2a41911dcf. Closing the issue as resolved. 🙂
