### ISSUE TITLE
[KED-944] Request for NetworkXDataSet

### ISSUE THREAD

**Issue by josephhaaga** [quantumblacklabs/kedro#70]
## Description
When building a pipeline to operate on graph data, users must create their own DataSet implementation for graphs. NetworkX is a popular library for doing graph analytics/manipulation in Python, and I believe built-in support for NetworkX graphs would benefit the community.

## Context
My colleagues and I focus on experimenting with different DL/ML techniques applied to graphs. We're looking for a testing harness to support this experimentation (along with a _path to production_), and I believe Kedro is the ideal candidate. I'm optimistic that out-of-the-box support for NetworkX would aid in Kedro's adoption by academics/researchers in the graph analytics space.

## Possible Implementation
I've got a NetworkXDataSet implementation living in the `src` folder of my projects; I'm currently working on adhering to the Kedro style guidelines, and writing unit tests.

Any/all feedback is welcome, especially pertaining to code standards and design decisions (e.g. what `load_args` and `save_args` are available to users etc.)

**Comment by lorenabalan** [comment]
Hi @josephhaaga, many thanks for raising this! That sounds like a great idea and we welcome contributions in this space! Feel free to raise a related PR for this and we'll be happy to review. :) I'll update the title with an internal ticket number so it's easier for us to track its progress, if you could reference the same ticket no. in the PR title that would be magnificent. :)

**Comment by lorenabalan** [comment]
Done! Please make sure you add this dataset as part of `contrib`.
