### ISSUE TITLE
Fully document project template

### ISSUE THREAD

**Issue by WaylonWalker** [quantumblacklabs/kedro#701]
## Description

When running `kedro new` the project template that comes out is not fully documented.

## Context

The kedro template should set a good example for those using it.  Many new python developers are using kedro's template as their way to get started and are building from it's example.   It should pass `interrogate` and/or `pydocstyle` out of the box.

### environment

I installed kedro@master to compare to the upcoming version.

### Interrogate

![image](https://user-images.githubusercontent.com/22648375/109388698-5899c280-78ce-11eb-9c7d-48f78abb986f.png)

### pydocstyle

![image](https://user-images.githubusercontent.com/22648375/109388906-85020e80-78cf-11eb-90f7-9799ff221957.png)

Personally my template uses these tools, this is one more hurdle for me to get through every time the template is significantly updated

## Possible Implementation

I'm happy to help, but fear that the process will be a slow back and fourth without discussion ahead of time.  Is this something the kedro team would like to take PR for?  Is it best done in one PR, or module by module.

**Comment by lorenabalan** [comment]
Hey @WaylonWalker, `pylint` already warns about `missing-module-docstring` or `missing-function-docstring`, so I'm tempted to leave that as the only one responsible for this sort of thing so we don't have a cacophony of third-party linting tools. Having said that, if there are places where you believe there should be more docstrings, feel free to raise a PR (either here or on starters repo), and we'll be happy to approve! ✅
