### ISSUE TITLE
[KED-2484] kedro@master new is not suggesting a repo or package name correctly

### ISSUE THREAD

**Issue by WaylonWalker** [quantumblacklabs/kedro#703]
## Description

Kedro typically lowercases and fills the suggested repo with '-' and the package name with '_'.  I tried running `kedro new` from kedro@master and it did not make these suggestions.

## Your Environment

* Kedro version used (`pip show kedro` or `kedro -V`): pip install git+https://github.com/quantumblacklabs/kedro
* Python version used (`python -V`): Python3.8.8
* Operating system and version: Ubuntu

**Comment by lorenabalan** [comment]
Hi @WaylonWalker thank you for raising, this is a known issue that's on our radar.

**Comment by WaylonWalker** [comment]
Thanks for the feedback @lorenabalan
