### ISSUE TITLE
How to configure kedro on AWS EMR to use files store in s3

### ISSUE THREAD

**Issue by MayankGupta3012** [quantumblacklabs/kedro#705]
When I am not having seperate s3 credentials. I am assigning roles to EMR to access s3. I am not sure how to use it. Its urgent issues. Quick help is very much appreciated.

**Comment by datajoely** [comment]
Hi @MayankGupta3012 
[Do the docs here help](https://kedro.readthedocs.io/en/stable/05_data/01_data_catalog.html#feeding-in-credentials)?

Additionally parts of our [AWS Sagemaker tutorial](https://kedro.readthedocs.io/en/latest/10_deployment/09_aws_sagemaker.html) may be applicable

**Comment by MayankGupta3012** [comment]
Hi @datajoely ,

Thanks for your help. Actually I gone through these docs yesterday and got some glimpse. Can you help me in advising how spark context needs to be configured so that it can use full EMR cluster. Currently what I observed whole jobs keep running on the master node only. I think we need to configure the spark context correctly. Sorry, I do not have much knowledge so any idea of great help here.

**Comment by datajoely** [comment]
Hi @MayankGupta3012 - I can do my best! 

So our [Spark docs are here](https://kedro.readthedocs.io/en/latest/11_tools_integration/01_pyspark.html). The most important points for optimisation are:

- [spark.yml](https://kedro.readthedocs.io/en/latest/11_tools_integration/01_pyspark.html#centralise-spark-configuration-in-conf-base-spark-yml) which passes the Spark configuration at the point the Spark session is created.
- Utilising the [ThreadRunner](https://kedro.readthedocs.io/en/latest/11_tools_integration/01_pyspark.html#tips-for-maximising-concurrency-using-threadrunner) which optimises for parallelism when running Spark jobs.

The last thing that may be helpful is to run `kedro new --starter=pyspark-iris` as this will generate a toy project configured to run Spark (locally).

**Comment by MayankGupta3012** [comment]
I am trying to run the command 
from kedro.framework import context
proj = context.load_context("path dir")

from jupyter pyspark kernel (from sagemaker, integrated with EMR for cluster). but getting following error:

An error was encountered:
[Errno 13] Permission denied: '/root/Elixir-codes/patient/.kedro.yml'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/kedro/framework/context/context.py", line 949, in load_context
    static_data = get_static_project_data(project_path)
  File "/usr/local/lib/python3.7/site-packages/kedro/framework/context/context.py", line 816, in get_static_project_data
    for conf_file in KEDRO_CONFIGS
  File "/usr/local/lib/python3.7/site-packages/kedro/framework/context/context.py", line 817, in <listcomp>
    if (project_path / conf_file).is_file()
  File "/usr/lib64/python3.7/pathlib.py", line 1387, in is_file
    return S_ISREG(self.stat().st_mode)
  File "/usr/lib64/python3.7/pathlib.py", line 1183, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/root/Elixir-codes/patient/.kedro.yml

I have given chmod 777 -R * to whole directory and parent directory too.. then also getting same error. Could you please help ASAP.

**Comment by MayankGupta3012** [comment]
Hi @datajoely can you help pleaseeeee with above issue

**Comment by datajoely** [comment]
Hi @MayankGupta3012  - we have several thoughts, but it's a little difficult to diagnose.

- We think there is a discrepancy between the user that runs the job and the one setting permissions
- First recommendation is to move the project out of the `/root/` directory and into something directly within userspace and run as a non-root user too
- `.kedro.yml` is a hidden file and may not be picked up by the `chmod` command you ran. This has been replaced by a `pyproject.toml` in newer versions of Kedro and isn't susceptible to this issue
- Our hidden file theory chan be provided by running `ls -al` in the project directory and `whoami` can tell us if a different user is used

**Comment by MayankGupta3012** [comment]
Thanks @datajoely , it was access issue in root. 

Could you please also let me know how to configure which pyspark it should use. as currently I have pyspark installed in /usr/bin/pyspark but still getting error:

 from pyspark.conf import SparkConf
ModuleNotFoundError: No module named 'pyspark'

while if I directly run pyspark shell it is running fine.

Please help. I am very beginner in kedro

**Comment by datajoely** [comment]
@MayankGupta3012  This just means that the environment which is running the pipeline is running doesn't have the correct dependencies installed. 

Steps to install requirements can be found here:
https://kedro.readthedocs.io/en/stable/04_kedro_project_setup/01_dependencies.html

**Comment by MayankGupta3012** [comment]
Thanks @datajoely , I really appreciate your prompt response and it is always helping me to figure out the solution and move with the setup. I am really very very sorry to bother you this much.
Can you help with my probably last question.

I want to give jupyter notebook as interface for my datascientist. This jupyter is running inside the container on cluster. So, the job submitting through the jupyter is getting submitting as Client side spark job. Meaning spark driver is running in form of container in one of the worker node so, we don't know in which worker node it will launch the driver container.

For this, we are loading our complete kedro project in hdfs or placing it in s3 bucket.

and using following code to run the code:

from kedro.framework.context import load_context
context = load_context("<Project directory>")
context.run()

In place of project directory, we tried to give the hdfs location as; hdfs:///<dir path> or hdfs:///<dir path>
and for s3, I tried to give s3://<dir path>

but getting same error like file not found etc.. previously when I was giving local directory path then that error makes sense as actually container is launched in worker node and file was present in master node so the error was making sense. 

But now after looking into detail, either load_context do not support hdfs filesystem path or s3 filesystem path or I am doing it something wrong.

it would be really great if you can help with this. or any other recommendation for such scenario where we are not knowing on which core node this driver container will be launched.

Really accpet our heartfelt thanks for your help!

**Comment by datajoely** [comment]
Can you post a screenshot? Where are you trying to provide the location?

**Comment by MayankGupta3012** [comment]
![KedroContext](https://user-images.githubusercontent.com/51915579/110350272-df8d2e80-8076-11eb-836e-4e2f1d677dae.jpg)

Thank @datajoely for your quick reponse. PFA screenshot

**Comment by datajoely** [comment]
So it's not possible to reference the project directory remotely like this. I think there is a bit of a disconnect here so I'll try and clear it up. 

The context is responsible for the managing the Nodes, Pipelines (Python) and Config (YAML) ahead of a 'run'. This run can be executed remotely by configuring your spark context via the `spark.yml` file. So each Data Scientist should have copies of these files locally and execution should happen remotely. 

The Catalog found within config should also allow the users to load/save data stored on S3 or HDFS like seen here:
https://kedro.readthedocs.io/en/stable/05_data/01_data_catalog.html

Lastly, you can get a nicer Jupyter experience here:
https://kedro.readthedocs.io/en/latest/11_tools_integration/02_ipython.html

**Comment by MayankGupta3012** [comment]
Hi @datajoely ,

Thanks for your quick response again.

Here I am saying, my jupyterhub is runing in docker container on the EMR Master. Now when Jupyter hub is trying to create the context but actually this whole context in JVM container which is launching on EMR core node (worker node). Due to this if we are giving path of server on which jupyterhub is running is actually showing that .kedro.yml file not found as once spark context is launched and from inside spark context (application) it is trying to locate the file which is availbale in master node while the spark application is launched in jvm container in one of the core node. This is the reason it is not able to access the .kedro.yml file.

I hope it will give you some more context

**Comment by lorenabalan** [comment]
Closing this as answered.
