### ISSUE TITLE
KedroContextError in jupyter notebook when using unreleased 0.18 from develop branch

### ISSUE THREAD

**Issue by pascalwhoop** [quantumblacklabs/kedro#707]
## Description

I am building a hook that uses `after_dataset_loaded` so I ran `pip install ../kedro`,  pointing at a locally checked out version of kedro develop branch. After running `kedro new --starter pandas-iris` I cannot access the `context` object of kedro jupyter lab. 

Note: The `kedro new ...` command also didn't trigger the usual interactive questions. The packages was called `default`. Is using `pip install <path_to_git_repo>` potentially not working properly? If so, how would one use the latest develop branch version of kedro in a project? 

## Expected Result
`context` is available in a notebook

## Actual Result

Looking at `startup_error` I receive

```
kedro.framework.context.context.KedroContextError('Expected an instance of `ConfigLoader`, got `NoneType` instead.')
```

## Your Environment

Running 
```
$ kedro --version
kedro, version 0.17.0
```

But that makes sense since the develop branch's `__init__.py` still states .17.0 on the current develop branch
https://github.com/quantumblacklabs/kedro/blob/develop/kedro/__init__.py

python37
MacOS BigSur

**Comment by MerelTheisenQB** [comment]
Hi @pascalwhoop, 

Thanks for reaching out. We've made some changes to the interaction flow when creating a new project, but the starters haven't been released with these new changes yet. Whenever we make a change that affect the starters, we need to release Kedro first and then the starters to make it work. 

This means that when you're using an unreleased version of Kedro e.g. from `master` or `develop`, you'll need to specify a commit to check out on the starter side. For this case specifically you could use `kedro new --starter=pandas-iris --checkout 310f2ff15adfb95fb458738bcd56c8b022069912`

**Comment by pascalwhoop** [comment]
cool thanks Merel for that note. Closing then
