### ISSUE TITLE
'kwargs' is not defined in `kedro_cli.py` generated by `kedro new` command

### ISSUE THREAD

**Issue by Minyus** [quantumblacklabs/kedro#71]
## Description
'kwargs' is not defined in `kedro_cli.py` generated by `kedro new` command

![image](https://user-images.githubusercontent.com/33908456/62770143-f5b6bf80-bacc-11e9-88e5-6cf4b6568091.png)

## Context
The code generated by `kedro new` is apparently not tested.

## Steps to Reproduce
1. Run `kedro new` to create a kedro project with iris dataset.
2. Run `kedro jupyter convert --all`

## Expected Result
No error.

## Actual Result
`NameError: name 'kwargs' is not defined`

![image](https://user-images.githubusercontent.com/33908456/62769268-2b5aa900-bacb-11e9-8737-77fbe6df20e9.png)

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): the latest develop build (commit 39ca35e
)
* Python version used (`python -V`): Python 3.6.8
* Operating system and version: Ubuntu 18.04.3 LTS (Bionic Beaver)

**Comment by 921kiyo** [comment]
@Minyus Thanks for reporting this. I actually fixed it yesterday and will let you know when my PR is merged :)

**Comment by 921kiyo** [comment]
It is fixed in https://github.com/quantumblacklabs/kedro/commit/d311df454254b145a834625c844eaff367e761a5
