### ISSUE TITLE
Present Kedro at the Argo Workflows community meeting

### ISSUE THREAD

**Issue by alexec** [quantumblacklabs/kedro#718]
I think our community would love to learn more about Kedro. Would someone like to come and present?

**Comment by WaylonWalker** [comment]
Kedro also has a [kedro.community](https://discourse.kedro.community)

I have cross posted your question there for reach.

https://discourse.kedro.community/t/present-kedro-at-the-argo-workflows-community-meeting/391

**Comment by alexec** [comment]
You can email me at alex_collins@intuit.com

**Comment by yetudada** [comment]
Thank you!

**Comment by AntonyMilneQB** [comment]
Very excited about this! We'll be reaching out to you via email, so I'll close this issue in the meanwhile 🙂

**Comment by lorenabalan** [comment]
Sent you an email @alexec ✅  @nraw and I are happy to help. 😊 🚀
