### ISSUE TITLE
No prompt for user input when creating new project by `kedro new --starter`

### ISSUE THREAD

**Issue by jw-cpnet** [quantumblacklabs/kedro#721]
## Description
With pre 0.17.1, `kedro new --starter starter-path` will prompt and ask the user for essential information about the new package. But with latest 0.17.1, there is no prompt and will just create a new project `new-kedro-project`. 

## Context
This happens when creating new kedro project with starters. No problem when creating with just `kedro new` (without the --starter argument)

## Steps to Reproduce
`kedro new --starter some-starter`

## Expected Result
The user can enter the metadata interactively when invoking this command

## Actual Result
There is no prompt for input.

## Your Environment

* Kedro version used (`pip show kedro` or `kedro -V`): 0.17.1
* Python version used (`python -V`): 3.8.6
* Operating system and version: Arch Linux

**Comment by yetudada** [comment]
Hi @jw-cpnet! Thank you for flagging this. I'll register this to the backlog to investigate. We have a new release coming out next week that should fix this.

**Comment by limdauto** [comment]
Hi @jw-cpnet are you experiencing the issue with a custom starter? For starters, we now use a `prompts.yaml` to provide the questions. Here is the related documentation: https://kedro.readthedocs.io/en/latest/07_extend_kedro/05_create_kedro_starters.html?highlight=prompts.yml#configuration-variables

You can also see the `prompts.yml` used for `kedro new` here: https://github.com/quantumblacklabs/kedro/blob/master/kedro/templates/project/prompts.yml

I'm going to close this issue but if you think it doesn't resolve your problem, please feel free to re-open it.

**Comment by jw-cpnet** [comment]
Thanks for looking into this. I was using the pandas-iris starter from the official kedro starter repo (@v0.17.1) and I think the prompts.yml is present. I'll try checkout the master branch and see if it still happens.
