### ISSUE TITLE
Hook to apply decorators

### ISSUE THREAD

**Issue by Minyus** [quantumblacklabs/kedro#723]
## Description
Hook to apply decorators

## Context
Decorators are useful to modify behaviors of multiple node functions.
Kedro 0.18.0 will deprecate applying decorators by [`decorate`](https://kedro.readthedocs.io/en/stable/kedro.pipeline.Pipeline.html#kedro.pipeline.Pipeline.decorate) method of `kedro.pipeline.Pipeline` and it is encouraged to use hooks to apply decorators, but there are no official hooks to apply decorators.

## Possible Implementation
Provide hooks to apply decorators

## Possible Alternatives
Continue to support decorators by `kedro.pipeline.Pipeline` even in Kedro 0.18.0 and later.

**Comment by mzjp2** [comment]
My understanding was that the "official" hook to apply decorators was the `before_node_run` hook, as described [here](https://kedro.readthedocs.io/en/stable/07_extend_kedro/02_hooks.html#use-hooks-to-extend-a-node-s-behaviour). Is there something lacking with that approach?

**Comment by Minyus** [comment]
A major benefit of decorators is getting info needed after the function ends before the function starts.
For example, log_time decorator gets timestamp before the function starts, keeps it locally (in memory), and uses it after the function ends to measure the execution time for the function.

(`before_pipeline_run` and `after_pipeline_run` cannot be used for this purpose.)

Users would not like to break down every decorator to `before_node_run`, variables to keep, and `after_node_run` because it needs additional efforts and adds maintenance costs for the 2 implementations (Kedro hooks for Kedro projects and decorators for non-Kedro projects)

**Comment by mzjp2** [comment]
You can still use function decorators and decorate `node.func` inside the hook, no? (there’s an example in the docs)

**Comment by AntonyMilneQB** [comment]
Hello @Minyus. If I understand correctly, it should still be possible to apply decorators using `before_node_run`. Something like this:

```
# <your_project>/src/<your_project>/hooks.py

from kedro.framework.hooks import hook_impl
from kedro.pipeline.decorators import log_time
from kedro.pipeline.node import Node


class ProjectHooks:
    @hook_impl
    def before_node_run(self, node: Node):
        node.func = log_time(node.func)
```

**Comment by Minyus** [comment]
Thanks @AntonyMilneQB .
Yes, using decorators as functions like `node.func = log_time(node.func)` seems to work fine. 
To use multiple decorators, however, the decorators need to be nested like `node.func = deco1(deco2(deco3(node.func)))`, and it doesn't look like Kedro's style though.
Anyway, thanks for a workable suggestion!

**Comment by AntonyMilneQB** [comment]
If you prefer chaining decorators together like in the existing `Node.decorate` notation, then you should be able to write a small helper function to do this. Something like:
```
def decorate(function: Callable, *decorators: Callable) -> Callable:
    for decorator in reversed(decorators):
        function = decorator(function)
    return function

class ProjectHooks:
    @hook_impl
    def before_node_run(self, node: Node):
        node.func =decorate(node.func, deco1, deco2, deco3)
```
This should achieve `node.func = deco1(deco2(deco3(node.func)))` without needing to explicitly do the nesting.

**Comment by Minyus** [comment]
Ok, thanks you!
