### ISSUE TITLE
Hook to apply transformers

### ISSUE THREAD

**Issue by Minyus** [quantumblacklabs/kedro#724]
## Description
Hooks to apply transformers

## Context
Transformers are useful to measure the duration time for loading/saving data which could be a bottleneck of the pipeline.
Kedro 0.18.0 will deprecate the current way to apply transformers and it is encouraged to use hooks to apply transformers but there are no official hooks to apply transformers.

## Possible Implementation
Provide hooks to apply transformers

## Possible Alternatives
Continue to support the current way to apply transformers even in Kedro 0.18.0 and later.

**Comment by AntonyMilneQB** [comment]
Hello @Minyus, similar to the comment in #723 I believe that this is actually still possible. See [this example](https://kedro.readthedocs.io/en/stable/07_extend_kedro/02_hooks.html#hook-implementation)

```
# <your_project>/src/<your_project>/hooks.py
from kedro.extras.transformers.time_profiler import ProfileTimeTransformer
from kedro.framework.hooks import hook_impl
from kedro.io import DataCatalog


class TransformerHooks:
    @hook_impl
    def after_catalog_created(self, catalog: DataCatalog) -> None:
        catalog.add_transformer(ProfileTimeTransformer())
```

Please let me know if that does what you're looking for or if I didn't understand the requirement correctly 🙂

**Comment by Minyus** [comment]
Thanks @AntonyMilneQB . Looking forward to a better solution!

**Comment by AntonyMilneQB** [comment]
So I think the pattern will now look like this:

```
class TransformerHooks:
    def __init__(self):
        self._start_times = {}

    @property
    def _logger(self):
        return logging.getLogger(self.__class__.__name__)

    @hook_impl
    def before_dataset_loaded(self, dataset_name: str) -> None:
        self._start_times[dataset_name] = time.time()

    @hook_impl
    def after_dataset_loaded(self, dataset_name: str) -> None:
        self._logger.info(
            "Loading %s took %0.3f seconds",
            dataset_name,
            time.time() - self._start_times[dataset_name],
        )
```

The documentation isn't very clear on this so I'll update it.

**Comment by Minyus** [comment]
Yes, this makes sense (assuming `before_dataset_saved` and `after_dataset_saved` can be used likewise.)
A concern is that this may not work with `ParallelRunner` or `ThreadRunner`. Testing code will be needed.

**Comment by AntonyMilneQB** [comment]
Yes, that is definitely a valid concern. I actually just tried this out using `async` to concurrently load datasets and found that it didn't work correctly - have filed it as a bug to be fixed.
