### ISSUE TITLE
Running `pip install "kedro[pandas.SQLQueryDataSet]"` not resolving a dependency error

### ISSUE THREAD

**Issue by jackcbaker** [quantumblacklabs/kedro#743]
Hello

Thanks a lot for this very useful library.

I've run into a small bug I wanted to report. I was getting the error:

```
Object `SQLQueryDataSet` cannot be loaded from `kedro.extras.datasets.pandas`. Please see the documentation on how to install relevant dependencies for kedro.extras.datasets.pandas.SQLQueryDataSet:
https://kedro.readthedocs.io/en/stable/04_kedro_project_setup/01_dependencies.html
```

So I ran
`pip install "kedro[pandas.SQLQueryDataSet]"`
as per the documentation. Which ran successfully. But my error was not resolved by this.

Thanks a lot.

**Comment by MerelTheisenQB** [comment]
Hi @jackcbaker , thanks for reporting this. Would you be able to provide steps to reproduce this issue?

**Comment by MerelTheisenQB** [comment]
Hi @jackcbaker, do you still need help resolving this issue?

**Comment by MerelTheisenQB** [comment]
I'm closing this issue for now, but of course feel free to re-open if you still need help with this.
