### ISSUE TITLE
Error in iris dataset tutorial

### ISSUE THREAD

**Issue by elcronos** [quantumblacklabs/kedro#747]
## Description

I get the error below while running command `kedro install'.
ERROR: Cannot uninstall 'ptyprocess'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

## Context
I created a virtual environment with kedro as suggested in the tutorials and tried to run the commands for the iris dataset example example project but keep getting the error and cannot continue.

## Steps to Reproduce
I run the commands as follow:
1. kedro new --starter=pandas-iris
2. kedro install
3. kedro run

## Expected Result
I should see the following message: 

'''
2019-02-13 16:59:26,293 - kedro.runner.sequential_runner - INFO - Completed 4 out of 4 tasks
2019-02-13 16:59:26,293 - kedro.runner.sequential_runner - INFO - Pipeline execution completed successfully.
'''

## Actual Result

```
ERROR: Cannot uninstall 'ptyprocess'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.17.2
* Python version used (`python -V`): Python 3.7.10
* Operating system and version: MacOS Big Sur

**Comment by limdauto** [comment]
Hi @elcronos thanks for filing this. It sounds like there might be a problem with your environment. The error means you have `ptyprocess` installed with your OS package manager, so kedro, which uses pip, can't clean it up when installing its dependencies. Did you install it with homebrew by any chance?

**Comment by elcronos** [comment]
HI @limdauto. I run the command you suggested and it worked.
