### ISSUE TITLE
Simple worfklow won't parallelize

### ISSUE THREAD

**Issue by 6Hhcy** [quantumblacklabs/kedro#75]
## Description
I take daily (gzipped) CSV files, process them and return HDF5 files. When I try to do 2 or more days using the Parallel Runner it doesn't work (see error)

## Context
The processing function just renames some variables, calls another (non-lambda) function to do some date processing, then uses the LambdaDataset trick to save it as an HDF5 file.  I'm using a factory for the LambdaDataSet:

```
def lambda_data_set_factory(output_dir_file, frame_name="dat") -> LambdaDataSet:
    """ df -> HDF
    """
    def save_df_to_hdf(value):
        with pd.HDFStore(
            path=output_dir_file, mode="w", complib="blosc:blosclz"
        ) as store:
            store.append(
                key=frame_name, value=value, append=False, data_columns=["ts"]
            )

    def load_hdf():
        with pd.HDFStore(output_dir_file, mode="r") as store:
            nrows = store.get_storer("dat").nrows
            df = store.select(frame_name, start=0, stop=nrows)

        # Replace TS index with integers
        # df.reset_index(inplace=True, drop=False)

        return df

    return LambdaDataSet(save=save_df_to_hdf, load=load_hdf)
```

## Steps to Reproduce
1. [First Step]
2. [Second Step]
3. [and so on...]

## Expected Result
Work

## Actual Result
Doesn't Work

```
AttributeError: The following data_sets cannot be serialized: [Mon, Tue]
In order to utilize multiprocessing you need to make sure all data sets are serializable, i.e. data sets should not make use of lambda functions, nested functions, closures etc.
If you are using custom decorators ensure they are correctly using functools.wraps().
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.14.3
* Python version used (`python -V`): 3.6.6
* Operating system and version: Win10

**Comment by tolomea** [comment]
The functions inside your factory are lexical closures. Lexical closures can't be pickled and so can't be used with the multiprocessing module which is what the parallel runner uses internally.
I think you should be able to get around this by converting your factory to a class, it's a bit more faff, but should work.

Presumably your factory is something like this:
```
def factory(num):
    def fn():
        print(num)

    return fn


fn = factory(6)
fn = pickle.loads(pickle.dumps(fn))
fn()
```
which fails with `AttributeError: Can't pickle local object 'factory.<locals>.fn'`
Instead you could do something like this
```
class Factory:
    def __init__(self, num):
        self.num = num

    def fn(self):
        print(self.num)

    def get(self):
        return self.fn


fn = Factory(6).get()
fn = pickle.loads(pickle.dumps(fn))
fn()
```
Another approach would be to write your own dataset, then you could pass your parameters to its constructor.

**Comment by 6Hhcy** [comment]
oh, I removed the datafactory from this post thinking it wasnt relevant. I'ved put it back. Is there a chance that it is complaining about the Gzipped file?

**Comment by tolomea** [comment]
No, it's the function inside a function construct. The inner function is a lexical closure and can't be pickled.
Pickle doesn't serialize functions and classes it just records their public name, but because these functions are hidden inside another function they don't have public names.

you could do the lambda dataset thing with a class like this
``` 
class LambdaDataSetFactory:
    def __init__(self, output_dir_file, frame_name="dat"):
        """ df -> HDF
        """
        self.output_dir_file = output_dir_file
        self.frame_name = frame_name

    def save_df_to_hdf(self, value):
        with pd.HDFStore(
            path=self.output_dir_file, mode="w", complib="blosc:blosclz"
        ) as store:
            store.append(
                key=self.frame_name, value=value, append=False, data_columns=["ts"]
            )

    def load_hdf(self):
        with pd.HDFStore(self.output_dir_file, mode="r") as store:
            nrows = store.get_storer("dat").nrows
            df = store.select(self.frame_name, start=0, stop=nrows)

        # Replace TS index with integers
        # df.reset_index(inplace=True, drop=False)

        return df

    def data_set(self):
        LambdaDataSet(save=self.save_df_to_hdf, load=self.load_hdf)
```
but you are probably better off just making your own dataset like this
```
class MyDataSet(AbstractDataSet):
    def __init__(self, output_dir_file, frame_name="dat"):
        self.output_dir_file = output_dir_file
        self.frame_name = frame_name

    def _load(self) -> Any:
        with pd.HDFStore(output_dir_file, mode="r") as store:
            nrows = store.get_storer("dat").nrows
            df = store.select(frame_name, start=0, stop=nrows)
        return df

    def _save(self, value: Any) -> None:
        with pd.HDFStore(
            path=output_dir_file, mode="w", complib="blosc:blosclz"
        ) as store:
            store.append(
                key=frame_name, value=value, append=False, data_columns=["ts"]
            )

    def _describe(self) -> Dict[str, Any]:
        return {
            "output_dir_file": output_dir_file,
            "frame_name": frame_name,
        }
```

**Comment by 6Hhcy** [comment]
Many thanks. It works, and now I understand Python a little better. It seems Dill doesn't suffer from this problem. Was there a reason for using Pickle instead of Dill in Kedro? Or is this an edge case not worth bothering with?

**Comment by tolomea** [comment]
I'm glad you got it working.
We in general prefer standard library thing, we like to try and keep our requirements as light as possible.
In this particular case we are using the standard library multiprocessing module and it is using pickle internally.

**Comment by 6Hhcy** [comment]
It's a great tool you've developed. Thanks again.
