### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by Jarthurn0** [quantumblacklabs/kedro#755]
I have been trying to run this command:
from kedro.pipeline import Pipeline, node

from .nodes import create_master_table, preprocess_companies, preprocess_shuttles

def create_pipeline(**kwargs):
    return Pipeline(
        [
            node(
                func=preprocess_companies,
                inputs="companies",
                outputs="preprocessed_companies",
                name="preprocess_companies_node",
            ),
            node(
                func=preprocess_shuttles,
                inputs="shuttles",
                outputs="preprocessed_shuttles",
                name="preprocess_shuttles_node",
            ),
            node(
                func=create_master_table,
                inputs=["preprocessed_shuttles", "preprocessed_companies", "reviews"],
                outputs="master_table",
                name="create_master_table_node",
            ),
        ]
    )

But this error appears:
ImportError                               Traceback (most recent call last)
<ipython-input-1-36c74848cafb> in <module>
      1 from kedro.pipeline import Pipeline, node
      2
----> 3 from .nodes import create_master_table, preprocess_companies, preprocess_shuttles
      4
      5

ImportError: attempted relative import with no known parent package.

I'm new to programming and really could use some help.

**Comment by FranciscoReveriano** [comment]
This issue has not been fixed. On your Spaceflight tutorial. The : 
"from .nodes import create_master_table, preprocess_companies, preprocess_shuttles"

results in an error where create_master table is not found in the package.
