### ISSUE TITLE
Neo4j dataset

### ISSUE THREAD

**Issue by juan-carlos-calvo** [quantumblacklabs/kedro#756]
## Description

I would like to have a dataset to run queries on Neo4j

## Context

I'm building a personal project with a neo4j database and would like to use kedro datasets to interact with it. Other users interested in working with neo4j databases might benefit from it.

**Comment by datajoely** [comment]
Hi @juan-carlos-calvo  you would in theory be able to talk to Neo4j using the [`SparkJdbcDataSet`](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.spark.SparkJDBCDataSet.html) but I agree  this is something that would be useful.  

How would you want to persist graphs in this world? We do have a [`NetworkXDataSet`](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.networkx.NetworkXDataSet.html) that has parallels this in terms of it being a graph, but can be loaded and saved the way you would use as Pickle or CSV. 

In the Neo4j world there are two options available to us a OGM like [Py2Neo](https://py2neo.org/2021.0/) which provides abstractions similar to SQL Alechmy. Alternatively you can execute Cypher statements via the [neo4j-driver](https://neo4j.com/docs/api/python-driver/current/) or [JDBC connection](https://neo4j-contrib.github.io/neo4j-jdbc/). 

This is actually the same problem we have with SQL in general - we don't have a great mechanism for executing a 'Transaction' where execution is remote as we are built around performing operations within the Kedro Node.  I'm very keen to build a `SQLTransactionDataSet` of sorts which would be an ephemeral node that simply applies a query string, but doesn't pass objects around in the same way as a regular Kedro DataSet. I'm not exactly sure on what the API for this looks like - but if we were to build it in theory you could execute Cypher via JDBC or easily extend it to work with the official driver.

**Comment by juan-carlos-calvo** [comment]
For now I'm thinking of just a simple api where `load` and `save` correspond to a `read_transaction` and `write_transaction` respectively (using the neo4j-driver).
Certaintly it would be great later to have a dataaset that would parse a `networkx.Graph` object into a transaction for saving and back.

**Comment by deepyaman** [comment]
I've created draft PR #758 with a Neo4j Cypher dataset (modeled on `SQLQueryDataSet`) that @JodySchechter developed during an internal asset development initiative (she doesn't have access to the asset repo for some reason, so I'm sharing with her permission). It would be great to more fully enable using Neo4j within Kedro pipelines!
