### ISSUE TITLE
Support Network File Sharing Protocol (SMB Protocol)

### ISSUE THREAD

**Issue by lucasjamar** [quantumblacklabs/kedro#765]
## Description
I often work with data located on a network drive. If I am working locally, I can easily load such data by specifying the displayed path, e.g.:
```
companies:
  type: pandas.CSVDataSet
  filepath: O:/department_name/team_name/companies.csv
```

However, if I want to move my work to the cloud, I need to use the [SMB protocol](https://github.com/jborean93/smbprotocol). It is already supported by [fsspec](https://filesystem-spec.readthedocs.io/en/latest/_modules/fsspec/implementations/smb.html). Using normal pandas read/ write csv, I do something like this:
```
df = pd.read_csv("smb://myuser:mypassword@myserver.com:445/department_name/team_name/companies.csv")
```

However, when I plug something similar into my data catalog, I get the following error message:
```
companies:
  type: pandas.CSVDataSet
  filepath: smb://myuser:mypassword@myserver.com:445/department_name/team_name/companies.csv
```

```
File "C:\Users\JAMAR_L\Anaconda3\envs\kedro-alpiq\lib\site-packages\kedro\extras\datasets\pandas\csv_dataset.py", line 121, in __init__
    self._fs = fsspec.filesystem(self._protocol, **_credentials, **_fs_args)
  File "C:\Users\JAMAR_L\Anaconda3\envs\kedro-alpiq\lib\site-packages\fsspec\registry.py", line 244, in filesystem
    return cls(**storage_options)
  File "C:\Users\JAMAR_L\Anaconda3\envs\kedro-alpiq\lib\site-packages\fsspec\spec.py", line 69, in __call__
    obj = super().__call__(*args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'host'
```

When I look at the code of [kedro.io.core](https://kedro.readthedocs.io/en/stable/_modules/kedro/io/core.html), I notice that smb protocol is not listed.
```
HTTP_PROTOCOLS = ("http", "https")
PROTOCOL_DELIMITER = "://"
CLOUD_PROTOCOLS = ("s3", "gcs", "gs", "adl", "abfs")
```

## Possible Implementation
Has anyone come across this issue before and perhaps have a workaround? If not, I will implement this by adding smb to the list of protocols.

Thanks :)

**Comment by MerelTheisenQB** [comment]
Hi @lucasjamar, this sounds like a good addition. We'd be happy to accept a PR for this 🙂

**Comment by lorenabalan** [comment]
Closing this as per https://github.com/quantumblacklabs/kedro/pull/782#issuecomment-858971526 and related discussion on the PR.
