### ISSUE TITLE
NO RUN.PY file in kedro starter 

### ISSUE THREAD

**Issue by agarwalsourabh55** [quantumblacklabs/kedro#766]
## Description
whenever I run kedro new no run.py file created although it was written in documentaiton that run.py file will be create
## Context
I wanted to do some changes inKedroContext func

```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.17
* Python version used (`python -V`):3.9
* Operating system and version:ubuntu 20

**Comment by agarwalsourabh55** [comment]
To be more specific  whenever I do **kedro new**  it is not creating src/package_name/run.py file . Any help on this ?

**Comment by datajoely** [comment]
Hi @agarwalsourabh55  - the functionality of `run.py` has moved to `__main__.py` - this is the [file generated by the starter](https://github.com/quantumblacklabs/kedro-starters/blob/master/pandas-iris/%7B%7B%20cookiecutter.repo_name%20%7D%7D/src/%7B%7B%20cookiecutter.python_package%20%7D%7D/__main__.py).

Please shout if anything doesn't make sense.

**Comment by agarwalsourabh55** [comment]
Thank you for the answer.
But please update kedro architecture overview because it is confusing for a beginner to understand because run.py was given instead of  __main__.py 

![](https://kedro.readthedocs.io/en/stable/_images/kedro_architecture.png)

**Comment by datajoely** [comment]
Great point @agarwalsourabh55 - A ticket to update this has been created!

**Comment by lorenabalan** [comment]
FYI this has now been updated in https://github.com/quantumblacklabs/kedro/commit/416b2d4dd9f7085cabda21d42ffc64f4d754943e
