### ISSUE TITLE
[KED-861] Implement dataset versioning on SparkDataSet

### ISSUE THREAD

**Issue by 921kiyo** [quantumblacklabs/kedro#77]
## Description
`SparkDataSet` class in `kedro.contrib.io.pyspark.SparkDataSet` does not have versioning implemented and it would be great if we could also enable it in this dataset. 

## Context
N/A

## Possible Implementation

- The documentation for how to enable versioning can be found in [here](https://kedro.readthedocs.io/en/latest/04_user_guide/07_advanced_io.html?#versioning) 
- You could also find actual examples of versioning implementations in the datasets in  `kedro.io`

**Comment by i25959341** [comment]
#85   I tried to create a PR, this is my first PR, so it is not very good

**Comment by DmitriiDeriabinQB** [comment]
Resolved in af11862
