### ISSUE TITLE
after_catalog_created fires on tab complete

### ISSUE THREAD

**Issue by WaylonWalker** [quantumblacklabs/kedro#775]
## Description

Is this expected behavior?  It's not something that I expected or was intuitive to me.

## Context

Looking for discussion around this, does it make sense to fix, document, or is it working as expected?

## Steps to Reproduce
1. apply an after_catalog_created hook to a pipeline
2. open ipython and create a context object (`kedro ipython`)
3. context.cata<TAB>

## Expected Result

`after_catalog_created` hook should fire after the catalog is created, not during tab complete

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.17.1 and 0.17.3
* Python version used (`python -V`): 3.8.10
* ipython version used: 7.21.0
* Operating system and version: Ubuntu

**Comment by AntonyMilneQB** [comment]
I am getting this too and it's definitely weird. Just doing `cata<TAB>` does the expected rather than the weird behaviour for me, as does `kedro jupyter`. No idea why this would happen 🤔

**Comment by mzjp2** [comment]
Is this possible related: https://github.com/ipython/ipython/issues/9094?

**Comment by WaylonWalker** [comment]
In the same vein of me trying to understand design decisions around the catalog and `after_catalog_created` hook.  Should `after_catalog_created` fire every single time I do a context.catalog?  When first designing the hook this was related to I tried to get the catalog through a session and quickly learned that causes infinite recursion.  It seems that reaching into the session.context for a catalog gives me a new catalog, which feels counter intuitive to the name "session".

**Comment by AntonyMilneQB** [comment]
This is a good question. My guess is that it's not really been considered (that `context.catalog` reruns `_get_catalog` and hence `after_catalog_created`) since, like you suggest, we weren't envisaging the catalog changing within one session. @limdauto might know more here. This also relates to the question of where the catalog belongs and whether it should be importable in the same way that pipelines are now.

**Comment by limdauto** [comment]
The decision to recreate the catalog every time users access `context.catalog` predates me. I guess it's to cater to this notebook workflow, i.e. users can play with dataset in a notebook and update `catalog.yaml`. Then when users go back to the notebook, we expect that catalog to be updated.

As @WaylonWalker mentioned, I think it's wrong to have catalog changing within the same session. We meant to create an interactive session for notebook to do autoreload of library components better but never got round to.
