### ISSUE TITLE
Ability to simply split the data catalog file into several small data catalog files

### ISSUE THREAD

**Issue by RafaelCartenet** [quantumblacklabs/kedro#781]
Hi there, completely in love with Kedro. I'd like to propose a feature that could might be helpful for everyone.
It might already exists, I have searched quite a lot but have not found it yet. Sorry in advance if it already does ...

## Description
When writing the data catalog, I often come to the point where I have so many datasets that the file itself becomes a little bit messy, I have to split it with comment character lines in order to split it into different parts so that it stays readable.

## Context
Organising a set of datasets in a single file is not really handy in my opinion. I think the ability to have an hierarchy/structure to organise them would help a lot, as you did in the default templates for the data folders,.

## Possible Implementation
Maybe the data catalog could be a folder of files rather than a single file (not as a default behaviour but something that could be configered)

## Possible Alternatives
Multi levels yaml file

**Comment by mzjp2** [comment]
Apologies if I've misread your issue, but I believe this is already how it works, see [this section in the documentation](https://kedro.readthedocs.io/en/stable/04_kedro_project_setup/02_configuration.html#loading) so you can either have:

```
conf/<env>/
  catalog_uk.yml
  catalog_usa.yml
```

or

```
conf/<env>/
  catalog/
    uk.yml
    usa.yml
    mauritius.yml
```

for example.

**Comment by datajoely** [comment]
Hi @RafaelCartenet  - we have some documentation on [how this works here](https://kedro.readthedocs.io/en/0.17.3/04_kedro_project_setup/02_configuration.html#local-and-base-configuration), essentially to achieve the results @mzjp2 mentioned faster than I could respond!

We match the following `glob` patterns: 

1.  '`catalog*`' - matches any file in `conf` which start with the prefix "`catalog`"
2.  '`catalog*/**`' - matches all `yaml` files one or more levels below below a folder called "`catalog`" 
 
Some other points:
- You can actually provide your own patterns at the point the `ConfigLoader` is registered.
- You can't use the same dataset name across split catalog files, you will get an error
- In memory Kedro treats them all as one big catalog, but it's much easier for humans to manage their work this way. I personally have used this pattern:
![image](https://user-images.githubusercontent.com/35801847/120551326-cda8f680-c3ed-11eb-8318-119ec0e2ae2e.png)

**Comment by RafaelCartenet** [comment]
Thanks both @mzjp2 @datajoely for your helpful replies. My apologies, I didn't encounter that part in the doc.
That's pretty smart, let the user the ability to organise its files as he wants.

Thanks for your fast replies :)
