### ISSUE TITLE
KedroContext inside the test enviroment doesn't found the context from the project

### ISSUE THREAD

**Issue by Khalil09** [quantumblacklabs/kedro#785]
## Description
Using the CLI command `kedro test`, with the default `test_run.py`, the class `KedroContext` doesn't find the pipelines nor the `params` from the kedro project.

## Context
This creates an impediment to start writing test for the pipelines.

## Steps to Reproduce
1. Create a `kedro` project and follow [this](https://kedro.readthedocs.io/en/stable/03_tutorial/04_create_pipelines.html) tutorial until you have the first pipeline.
2. Go to the test folder and change it to look like this:
 ```python
from pathlib import Path

import pytest
from kedro.framework.context import KedroContext


@pytest.fixture
def project_context():
    return KedroContext(package_name="MyProjectName", project_path=Path.cwd())


# The tests below are here for the demonstration purpose
# and should be replaced with the ones testing the project
# functionality
class TestProjectContext:
    def test_package_name(self, project_context):
        print(project_context.pipelines) # <- print the pipelines from the context
        assert 1 == 2 # <- This line is just to make the pytest print the above line
        assert project_context.package_name == "MyProjectName"
```
3. Run `kedro test` and search for the pipelines printed. In my case the output is:
```sh
self = <tests.test_run.TestProjectContext object at 0x7f08b5ea8ca0>
project_context = <kedro.framework.context.context.KedroContext object at 0x7f08b5ea8eb0>

    def test_package_name(self, project_context):
        print(project_context.pipelines)
>       assert 1 == 2
E       assert 1 == 2

src/tests/test_run.py:56: AssertionError
-------------------------------------------------- Captured stdout call ---------------------------------------------------
{} <- An empty dictionary

```

## Expected Result
A dictionary with all pipelines from the project.

## Actual Result
Receving an empty dictionary. Probably because the kedro context is not finding the pipelines.

## Your Environment

* Kedro version used (`pip show kedro` or `kedro -V`): 0.17.3
* Python version used (`python -V`): 3.8.10
* Operating system and version: Ubuntu bionic 18.04

**Comment by AntonyMilneQB** [comment]
Hello @Khalil09, thanks very much for the bug report. You're absolutely right. The reason that `project_context.pipelines` isn't being loaded is because our `configure_project` isn't being called here to register the pipelines. In fact, the whole scheme of accessing `package_name` and `pipelines` through a KedroContext is being deprecated for 0.18. The new way of doing this would be:

```python
from pathlib import Path

import pytest
from kedro.framework.startup import bootstrap_project
from kedro.framework.project import pipelines

@pytest.fixture
def metadata():
    return bootstrap_project(Path.cwd())  # this will call configure_project and register pipelines

# The tests below are here for the demonstration purpose
# and should be replaced with the ones testing the project
# functionality
class TestProjectContext:
    def test_package_name(self, metadata):
        print(pipelines)
        assert False
        assert metadata.package_name == "spaceflights"
```

Note (a) use of `metadata` rather than kedro context and (b) you can now import `pipelines` directly rather than accessing as a property.

I'll check this with the team and update our templates to match 🙂

**Comment by Khalil09** [comment]
@AntonyMilneQB, Thank for your response. I will test this solution and return with a feedback.

**Comment by Khalil09** [comment]
Works!!! Thank you @AntonyMilneQB.

**Comment by lasiadhi** [comment]
Hello, As a follow-up question, how to load the parameters using the metadata inside the above test_package_name()? Thanks!
