### ISSUE TITLE
Kedro default logging seems to remove other handlers?

### ISSUE THREAD

**Issue by noklam** [quantumblacklabs/kedro#792]
## Description
Kedro default logging will remove other handlers.

## Context
I am using `clearml` which is a tool for experiment tracking. It would normally log my program STDOUT included print message or logging.info() stuff. I found that when I am using Kedro with it, the log is sent to `clearml` properly.

ClearML: https://github.com/allegroai/clearml

## Steps to Reproduce
The standard logging config provided by `Kedro` is [this](https://github.com/quantumblacklabs/kedro-starters/blob/master/pandas-iris/%7B%7B%20cookiecutter.repo_name%20%7D%7D/conf/base/logging.yml)

This is a minimal snippet to reproduce the issue. To see the log properly, uncomment the line ` # "incremental": True,`. I have written a short summary ofthis issue [here](https://noklam.github.io/blog/python/2021/06/20/logging_config_dict_problem_in_kedro.html). In short, the default is `incremental: False` which seems to remove the existing handler.

to run this, you need to install two package
`pip install kedro clearml`

```
import logging
from clearml import Task
conf_logging = {
    # "incremental": True,
    "disable_existing_loggers": False,
    "version":1,
     "formatters":{
         "simple":{
             "format":"%(asctime)s - %(name)s - %(levelname)s - %(message)s"}
             }
             }

t = Task.init(project_name="test")
logging.config.dictConfig(conf_logging)
logging.warning("WARN!")
print("PRINT!")

```

## Expected Result
Log should show up in the ClearML App

## Actual Result
Log is missing

```
-- If you received an error, place it here.
```

```
-- Separate them if you have more than one.
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): kedro 0.16.6
* Python version used (`python -V`): 3.7
* Operating system and version: Window 10

**Comment by AntonyMilneQB** [comment]
Hi @noklam, thanks for the very clear bug report and proposed fix - much appreciated. Adding `incremental: True` to our logging.yml sounds like an easy fix, but I'm wondering whether it will cause other issues? From the same page you linked to:

> Thus, when the incremental key of a configuration dict is present and is True, the system will completely ignore any formatters and filters entries, and process only the level settings in the handlers entries, and the level and propagate settings in the loggers and root entries.

Would be good if you could confirm whether `incremental: True` loses some of the desired behaviour from logging.yml that most users do want (e.g. using `formatter: simple` in handlers and `handlers` option under `loggers`). If this is the case then it seems like there is not a good way to fix logging.yml that works nicely in all scenarios. Probably the current settings that don't work with `clearml` are more generally applicable/useful than options that work with `clearml` but detract from the logging experience in all other scenarios.

If this is the case and there's no solution that works nicely with both `clearml` and no-`clearml` projects, probably we should add a note to the documentation pointing out the fix in this special case.

Let me know what you think!

**Comment by noklam** [comment]
@AntonyMilneQB 

Hi, you are right about the `incremental: True` flag, it would make other handlers does not work as expected. I don't have a perfect solution here. It may be best to just keep a note here without changing Kedro's default.

Having said that, the situation may be more generic to just any logging handlers, not specific to `clearml`. Maybe there are better choices than using `dictConfig`?  Ideally, I would expect Kedro set up its owns handlers while not affecting the existing one unless specified.

**Comment by AntonyMilneQB** [comment]
@noklam You are right, this is a more general issue, and it would be nice if it were possible for kedro to set its own handlers without affecting existing ones. Unfortunately I don't think there is any better option than using `dictConfig` here - as I understand it, this is just a general problem with Python logging handlers.

I think the best solution will be to leave the default logging.yaml as it is and add a note to the documentation about this.

**Comment by noklam** [comment]
I agree.
