### ISSUE TITLE
Addition to migration guide regarding moving from CSVLocalDataset to pandas.CSVDataSet from kedro 0.15.* to upcoming release

### ISSUE THREAD

**Issue by ShaunDeRoza** [quantumblacklabs/kedro#797]
## Description

When converting from CSVLocalDataset to pandas.CSVDataSet code that works in kedro 0.15.* can have encoding errors in kedro 0.16.* even if the correct encoding is specified in save_args or load_args. This can be fixed by instead placing the encoding argument in fs_args under open_args_load or open_args_save. The proposal is to add some information mentioning this in the section on migration of datasets in the migration guide for kedro 0.15.*

**Comment by datajoely** [comment]
@ShaunDeRoza we documented this in the upgrade from 0.15.x to 0.16.x release notes:
https://github.com/quantumblacklabs/kedro/blob/master/RELEASE.md#migration-guide-from-kedro-015-to-016
