### ISSUE TITLE
[KED-929] Libcloud Support

### ISSUE THREAD

**Issue by EricSchles** [quantumblacklabs/kedro#8]
## Description
At present I make use of libcloud for consistency of interface.  It would be great if this tool made use of libcloud so that we can guarantee consistency of interface across all clouds.

## Possible Implementation
Make use of libcloud for all cloud automation.

## Possible Alternatives
Keep current implementation

## Checklist
Include labels so that we can categorise your issue:

- [Interface standardization ] Add a "Component" label to the issue
- [ Low ] Add a "Priority" label to the issue

**Comment by yetudada** [comment]
Hi @EricSchles, thank you for sending through this feature request. We think that `libcloud` support could be added as part of `kedro.contrib.io`. I will mark this as good first issue label, so anyone interested in doing can pick it up.

More information about how to do this is available here: https://github.com/quantumblacklabs/kedro/blob/develop/CONTRIBUTING.md

**Comment by shril** [comment]
@yetudada, Can I pick this up?

**Comment by DmitriiDeriabinQB** [comment]
Hi @shril, please feel free to tackle this if it's of interest for you :) The contribution guide can be found [here](https://github.com/quantumblacklabs/kedro/blob/develop/CONTRIBUTING.md#contribute-a-new-feature).

**Comment by lorenabalan** [comment]
I've updated the PR title with our internal ticket number to keep track of this more easily. :)
@shril do you need any help from our side on this issue?

**Comment by bahij-youssef** [comment]
@yetudada I can pick this up.

**Comment by yetudada** [comment]
Thank you @bahij-youssef! You could check this guide out for more help: https://kedro.readthedocs.io/en/stable/04_user_guide/14_create_a_new_dataset.html

I'll assign this task to you.

**Comment by yetudada** [comment]
Hi @EricSchles, we're cleaning up our GitHub issues and want to close this. We think that our use of fsspec will have solved the need to connect to many cloud storage options.
