### ISSUE TITLE
Cannot open the notebook after installing Jupyter Extension

### ISSUE THREAD

**Issue by khuyentran1401** [quantumblacklabs/kedro#802]
## Description
After [installing Jupyter Extension](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/install.html), I can no longer open the notebook using `kedro notebook` anymore. However, I can still open the notebook using `jupyter notebook`. Does Kedro allow users to add Jupyter Extension to the notebook?

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used: 0.17.4
* Python version used: 3.8.10
* Operating system and version: macOS Big Sur Version 11.4

**Comment by MerelTheisenQB** [comment]
Hi @khuyentran1401, thanks for flagging this. 

Can you provide some more details about this issue so I can try and replicate it: did you install the extensions using pip or conda? What's the error you're seeing?

**Comment by khuyentran1401** [comment]
Hi Merel, I'm not sure why but when I attempted to install jupyter extension again with another project, the notebook works well. So I think the problem might not be because of the jupyter extension. Sorry for this confusion.

**Comment by MerelTheisenQB** [comment]
No worries @khuyentran1401 , I'm glad the issue was resolved 🙂
