### ISSUE TITLE
Limit the number of parallel nodes

### ISSUE THREAD

**Issue by acnazarejr** [quantumblacklabs/kedro#809]
## Description
I would like to be able to limit the number of nodes running in parallel when I use `kedro run --parallel`

## Context
This feature is important to avoid memory error problems due to memory size limitations. 
For instance, I have a pipeline composed of many independent nodes with big dataset inputs (more than 1 GB each). So, when I run kedro specifying the `--parallel` option, all these node starts simultaneously and load all inputs, reaching the memory limit. 

If we could specify the number of concurrent nodes, we will be able to control de memory usage.

**Comment by deepyaman** [comment]
Would customizing it using the `max_workers` argument to `ParallelRunner` work for you? See the documentation [here](https://kedro.readthedocs.io/en/stable/kedro.runner.ParallelRunner.html).

I understand that it's not as straightforward as passing it on the command line (which technically could be done, more than happy to make a PR if the core team feels this would be desirable), but there's probably a level of balancing how much you expose through the CLI. Personally feel this is a very reasonable option to expose.

**Comment by acnazarejr** [comment]
Thanks @deepyaman, the max_workers arg works for me!

I could add an extra option on CLI to expose this feature in my application using the below code:

```
if runner in ["ParallelRunner", "ThreadRunner"]:
        runner_instance=runner_class(is_async=is_async, max_workers=max_workers)
    else:
        runner_instance=runner_class(is_async=is_async)
```

Also, I feel this is a very reasonable option to expose. :D

**Comment by lorenabalan** [comment]
Hi @acnazarejr , @deepyaman! I understand where you're coming from, however we want to limit the surface of the API to dimensions that are as reasonable as possible. 

Adding a `--max-workers` option wouldn't be relevant for every runner - e.g. `SequentialRunner`, or a `DryRunner` suggested in our docs. Therefore this option would be dependent on another option being present with a certain value (`--runner`), which doesn't make for a nice experience. 

Given it's very easy to extend the `kedro run` CLI by the user adding the option to the project's own `cli.py` - which is designed/encouraged to be tinkered with anyway! - , I believe this is enough for the purposes of this task. Hope this makes sense, and thank you for your contribution! 🙏

**Comment by chillerb** [comment]
Sorry for commenting on this issue closed a long time ago, but I think having some command line control over the number of workers integrated into kedro is a reasonable feature. Being able to limiting the number of workers is definitely necessary to avoid running out of RAM / vRAM. I think the simplicity of having this `--max-workers` option in the command line would compensate for it being co-dependent on the chosen runner - the way less "nice experience" for the user is having to customize the whole CLI just to achieve this. If having co-dependent CLI options is that big of an issue, there are simple solutions to this: instead of having a `--max-workers` argument, just integrate a general `--runner-params` option, which would allow configuring all runners from the command line, enabling something like `--runner-params` max_workers=4.

Finally, if for some reason a CLI option is to be avoided at all costs, you could introduce a environment variable `KEDRO_MAX_WORKERS`, which would allow configuration, or a setting in the `settings.py`.

Therefore, please reconsider adding this feature!

**Comment by deepyaman** [comment]
> I think the simplicity of having this `--max-workers` option in the command line would compensate for it being co-dependent on the chosen runner - the way less "nice experience" for the user is having to customize the whole CLI just to achieve this. If having co-dependent CLI options is that big of an issue, there are simple solutions to this: instead of having a `--max-workers` argument, just integrate a general `--runner-params` option, which would allow configuring all runners from the command line, enabling something like `--runner-params` max_workers=4.

I'm open to either of these solutions. The benefit of `--runner-params` is that it is flexible enough to support any custom runners with additional params; the benefit of `--max-workers` is that it's more straightforward. Given you don't have to think about which runner supports what with `--runner-params`, that would get my vote.

@merelcht @rashidakanchwala any thoughts/objections?

**Comment by deepyaman** [comment]
@chillerb I'm not hearing any objections, and this sounds reasonable to me. Would you be open to raising a PR? :)

**Comment by Adeikalam** [comment]
@deepyaman I've tried to implement it as my first contribution to Kedro, but it feels awkward having both `is_async` and `runner_params` as possible arguments. What should happen if someones passes `max_workers=4,is_async=True`?

Should the `is_async` parameter be deprecated in favor of `runner_params`?

**Comment by merelcht** [comment]
Hi @Adeikalam & @deepyaman , sorry for the late response, I didn't see the tag because the issue was closed before. I'll add this to our backlog grooming to discuss with the team!

**Comment by chillerb** [comment]
Hi @deepyaman @Adeikalam @merelcht 
Thank you for your replies! Sorry, @deepyaman , I wasn't aware you were awaiting a reply from me. I don't have any objections to implementing `--runner-params`, I think this would solve the problem neatly. @Adeikalam seems to be already close to opening a Pull Request? I agree with having both `is_async` (I think it is just called `--async` in the CLI), and `--runner-params` is somewhat awkward. However, to keep compatibility, I would keep `--async` for now? Then merge it into the other `--runner-params`, and maybe raise an Exception, if `--async` and `--runner-params` are conflicting.

**Comment by deepyaman** [comment]
> [@deepyaman](https://github.com/deepyaman) I've tried to implement it as my first contribution to Kedro, but it feels awkward having both `is_async` and `runner_params` as possible arguments. What should happen if someones passes `max_workers=4,is_async=True`?
> 
> Should the `is_async` parameter be deprecated in favor of `runner_params`?

As @chillerb also pointed out, we need to maintain support for the `--async` flag for compatibility. I think the approach he laid out is perfect, though; consolidate as needed in the logic, and raise a `KedroCLIError` if somebody provides an incompatible configuration.

**Comment by merelcht** [comment]
For whoever wants to work on this, we agreed with the team on the approach of adding `--runner-params` to allow passing max workers. The `--async` flag will then be deprecated and removed in the next breaking release. An exception should be raised if `--async` and `--runner-params` are conflicting.
