### ISSUE TITLE
Any plans on bumping the Python version to 3.9?

### ISSUE THREAD

**Issue by Nieju** [quantumblacklabs/kedro#810]
I'd like to use the improved Python typing features of 3.9 but as Kedro is <3.9 I cannot.

Any plans on bumping it?

**Comment by MerelTheisenQB** [comment]
Hi @Nieju! Yes, support for Python 3.9 will be released in our next major version 0.18.0.

**Comment by Nieju** [comment]
Great, when will that be?

**Comment by datajoely** [comment]
We can't commit to an exact date, it's the team's current focus and we currently do think there will be another minor point release beforehand.

**Comment by lorenabalan** [comment]
I was just about to answer the same. I acknowledge this is not what you'd like to hear, but we need to finish re-working out some framework internals before we are ready. I'll close this as answered and in favour of https://github.com/quantumblacklabs/kedro/discussions/739, where you can keep track of the discussion if we have any updates.
