### ISSUE TITLE
Spaceflight tutorial adding kedro[pandas.CSVDataSet,pandas.ExcelDataSet]==0.17.4

### ISSUE THREAD

**Issue by andrewMcK1** [quantumblacklabs/kedro#811]
## Description
When going through the tutorial, I followed the instructions on this page: https://kedro.readthedocs.io/en/stable/03_tutorial/02_tutorial_template.html. However, what ended up happening is that adding the above line to `requiremenst.txt` did not work as when I ran `kedro build-reqs` it looked in `requirements.in` and rebuilt `requirements.txt` to what it was before I made the update. Should `requirements.in` be updated here instead?

## Context
Trying to get up to speed with kedro

## Steps to Reproduce
1. Replacve the line that has `kedro==0.17.4` in `requirements.txt` in `/src` of whatever directory you choose for the spaceflight tutorial with `kedro[pandas.CSVDataSet,pandas.ExcelDataSet]==0.17.4`
2. Run `kedro build-reqs`
3. See that the update you made to `requirements.txt` is no longer present

## Expected Result
Update made to `requirements.txt` should not be removed.

## Actual Result
Update to `requirements.txt` is not removed

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

`kedro, version 0.17.4`
`Python 3.8.2`

**Comment by datajoely** [comment]
Thanks @andrewMcK1  this is a bug in our docs - you should make the change to `requirements.in` instead.

**Comment by andrewMcK1** [comment]
> Thanks @andrewMcK1 this is a bug in our docs - you should make the change to `requirements.in` instead.

Happy to do that :) Will submit a PR

**Comment by AntonyMilneQB** [comment]
I actually think the documentation here is correct. Following the tutorial exactly, you will not have a `requirements.in` file to begin with - just a `requirements.txt` file. The line *should* be added to that initial `requirements.txt`; running `kedro build-docs` will then generate the `requirements.in` file (by copying and pasting the `requirements.txt` file to it). Only once `requirements.in` exists should that be where you change dependencies. This is explained fully [here](https://kedro.readthedocs.io/en/stable/04_kedro_project_setup/01_dependencies.html).

We know this is a very confusing flow for users and are hoping to improve it 🙂  But I think if you follow the tutorial precisely, it will all work as it should.

**Comment by andrewMcK1** [comment]
> I actually think the documentation here is correct. Following the tutorial exactly, you will not have a `requirements.in` file to begin with - just a `requirements.txt` file. The line _should_ be added to that initial `requirements.txt`; running `kedro build-docs` will then generate the `requirements.in` file (by copying and pasting the `requirements.txt` file to it). Only once `requirements.in` exists should that be where you change dependencies. This is explained fully [here](https://kedro.readthedocs.io/en/stable/04_kedro_project_setup/01_dependencies.html).
> 
> We know this is a very confusing flow for users and are hoping to improve it 🙂 But I think if you follow the tutorial precisely, it will all work as it should.

Ah yes you're right - I must have run `kedro build-reqs` previously and hence the presence of `requirements.in`. Thanks for the clarification

**Comment by lorenabalan** [comment]
Hi all, thank you for contributing! Looks like this has been resolved, so I'm gonna go ahead and close this issue. 🙂
