### ISSUE TITLE
pandas.XMLDataSet

### ISSUE THREAD

**Issue by lucasjamar** [quantumblacklabs/kedro#818]
## Description
Add a pandas.XMLDataSet to the list of dataset implementations. Newly available in pandas 1.3.0
https://pandas.pydata.org/docs/reference/api/pandas.read_xml.html?highlight=read_xml
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_xml.html?highlight=xml

## Context
Such a feature would allow users to read data from a url or file straight into a pandas df without needing to create a node to parse the xml.

I'd be happy to have a crack at this one starting next week :) .

**Comment by datajoely** [comment]
@lucasjamar we'd love a PR doing this, in theory you can copy and paste `pandas.CSVDataSet` and simply change the `pandas` call.

**Comment by AntonyMilneQB** [comment]
Sounds like a great idea! But I'd just check with @lorenabalan or @ignacioparicio first since I know we've recently changed the pandas requirement from 1.0 to 1.2 in develop (master is still `>=0.24`). There might be a good reason we can't yet support 1.3?

**Comment by lorenabalan** [comment]
Closing as resolved in #822 , will be available in 0.18.0.
