### ISSUE TITLE
Kedro Starter for popular CI tools

### ISSUE THREAD

**Issue by sagrawal128** [quantumblacklabs/kedro#826]
## Description
I would like to add Kedro Starter projects with scripts for CIrcle CI, Github Actions. This would be two starter templates. This starter template would help non-devops engineer developer to easily set up a CI/CD process and ensure quality code.

## Context
This will help anyone in easily setting up their CI/CD environment and ensure quality code from the beginning. Most of the services offered by Circle CI and Github Actions are free for developers. However, writing a good script could be a daunting task. This template would do this for the user and will contain elaborate steps on how to set up the keys and access too.

## Possible Implementation
- Add a starter project in `kedro-starters` each for Circle CI and Github Actions.
- Enrich the kedro_cli.yml file with commands to run/check for `docstring styles`, `integrations tests`, `unit tests`

**Comment by lucasjamar** [comment]
Hi,

This isnt exactly what you are asking for but you might find it to be of interest: https://github.com/marketplace/actions/kedro-action

**Comment by deepyaman** [comment]
This is something I've been thinking about for a while and would love! It's also an issue/opportunity that's come up in our data engineering leadership calls.

To add on an alternative implementation, is it possible to have CI be something you optionally initialize? e.g. `kedro new --starter pandas-iris --ci circle`? Kedro is opinionated around a lot of tooling/best practices, and I don't see why optionally adding a base CI script would be out of it's realm.

**Comment by sagrawal128** [comment]
Thank @lucasjamar . It is definitely of interest!
@deepyaman modifying the `kedro new` sounds like a great idea! This way we can use ci scripts for any new starter project in the future. I would prefer to add a starter template for now, let it stabilise and meanwhile work on modifying the `kedro new` command. The former looks like a low effort high impact thing at the moment. Let me know if you think otherwise, happy to pivot!

**Comment by WaylonWalker** [comment]
I just submitted a starter this morning and elected to remove ci from it.  I felt that by the time you combine all the ci platforms and deployment options possible, the chances of my starter including what someone wants was not high.

Some good options I can think of to include ci in starters are.

Have ci as a separate component, where users can copy the script into their repo or do a second cookie cutter render into the project.

Have a series of questions built into the starter about ci runner and production environment.

**Comment by sagrawal128** [comment]
> I just submitted a starter this morning and elected to remove ci from it. I felt that by the time you combine all the ci platforms and deployment options possible, the chances of my starter including what someone wants was not high.
> 
> Some good options I can think of to include ci in starters are.
> 
> Have ci as a separate component, where users can copy the script into their repo or do a second cookie cutter render into the project.
> 
> Have a series of questions built into the starter about ci runner and production environment.

@WaylonWalker I agree. I guess that's what @deepyaman's suggestion sounds like, to have a `kedro new --starter <> --ci <>` Wdyt?
