### ISSUE TITLE
networkx extended datasets

### ISSUE THREAD

**Issue by sbrugman** [quantumblacklabs/kedro#828]
## Description
Kedro currently support networkx's json representation. Being able to select from other formats can be beneficial, for instance gml or graph xml (graphml, interoperability with other graph tools) - both are supported by networkx.

Creating a PR with these additional datasets is straight-forward, however there is a design decision I'd like to raise.

Currently the networkx dataset structure is inconsistent with that of pandas:
- pandas.CSVDataSet
- pandas.ExcelDataSet
- json.JsonDataSet
- networkx.NetworkxDataSet

The addition of additional dataset formats would be an ideal time to refactor, however this introduces backwards incompatibility. 

## Context
These additional dataset formats have their use depending on the use case. Having complete support in kedro is low-effort.

## Possible Implementation
Proposed:
- pandas.CSVDataSet
- pandas.ExcelDataSet
- json.JsonDataSet
- networkx.JSONDataSet
- networkx.GMLDataSet
- networkx.GraphMLDataSet

## Possible Alternatives
Alternatively, only extend the current datasets:

- pandas.CSVDataSet
- pandas.ExcelDataSet
- json.JsonDataSet
- networkx.NetworkxDataSet
- networkx.GMLDataSet
- networkx.GraphMLDataSet

**Comment by datajoely** [comment]
Hi @sbrugman this is a sensible request. The original NetworkX implementation was submitted via the community, would you be interested in submitting a PR?
