### ISSUE TITLE
json.decoder.JSONDecodeError when loading log file with versioning enabled

### ISSUE THREAD

**Issue by selalamiTF** [quantumblacklabs/kedro#841]
## Description
I am trying to use the versioning capabilities with a pandas parquet dataset. Everything works fine, but when I try to open log file using `json.load()`. I am using a hook that loads my log files to  S3 after a pipeline run. In order to do that, I need to open and transform the log files

## Context
I cannot handle the log files. I don't know if storing `ContextJournalRecord` and `DatasetJournalRecord` in same file.
## Steps to Reproduce
1. [First Step]
2. [Second Step]
3. [And so on...]

## Expected Result
Nothing in particular. I only need to know if it is intentional.

## Actual Result
The logging file looks like this: 
```
{"type": "ContextJournalRecord", "run_id": "2021-07-20T12.59.14.049Z", "project_path": "", "env": "local", "kedro_version": "0.16.6", "tags": [], "from_nodes": [], "to_nodes": [], "node_names": [], "from_inputs": [], "load_versions": {}, "pipeline_name": "restaurant_metadata", "extra_params": {"bucket": "xxxx"}, "git_sha": "4e19b5c"}
{"type": "DatasetJournalRecord", "run_id": "2021-07-20T12.59.14.049Z", "name": "xxxx", "operation": "save", "version": "2021-07-20T12.59.14.049Z"}
```

```
-- If you received an error, place it here.
```

```
-- Separate them if you have more than one.
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.16.6
* Python version used (`python -V`): 3.7
* Operating system and version: MacOS

**Comment by ignacioparicio** [comment]
Hi @selalamiTF, what specific log file are you tring to open? What would be your expected result?
