### ISSUE TITLE
Pytorch data connector

### ISSUE THREAD

**Issue by marcelned** [quantumblacklabs/kedro#846]
Perusing the [data connectors available](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.html#data-sets), I can't seem to find a Pytorch Model Dataset connector like the current  `TensorFlowModelDataset`

Is there an implementation available somewhere?`

**Comment by datajoely** [comment]
Hi @marcelned  in most cases PyTorch is compatible with the standard `pickle.PickleDataSet` and the various backends provided by default (pickle, joblib etc).

https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.pickle.PickleDataSet.html

We are aware of some (rare) edge cases where some PyTorch models don't save nicely - we have plans to support custom Pickle backends at some point.

I'm going to close the issue - but please reopen if you have any issues.
