### ISSUE TITLE
Configurable Default DataSet wtih catalog create

### ISSUE THREAD

**Issue by WaylonWalker** [quantumblacklabs/kedro#849]
## Description

It would be nice if `kedro catalog create` had a configurable default.  I can see in [catalog.py#L196)](https://github.com/quantumblacklabs/kedro/blob/master/kedro/framework/cli/catalog.py#L196) that it is hardcoded.  It seems like it would be easy to pull a default DataSet type from settings, but I have no idea how you would configure per dataset options such as filepath.  Would it be possible to point to a formatting function?

## Possible Implementation

``` python
# settings.py

# default
DEFAULT_DATASET  = {"type": "MemoryDataSet"}

# simple example of parquet
DEFAULT_DATASET  = {"type": "  type: pandas.ParquetDataSet", "filepath": lambda ds: f'data/{ds.lower()}.parquet'}

# parquet
DEFAULT_DATASET  = {"type": "  type: pandas.ParquetDataSet", "filepath": create_parquet_filepath}

def create_parquet_filepath(dataset_name: str) -> str:
   """
   This is my company default data file structure where I can add specific keywords that I want to become directories.
   """
   if "raw" in dataset_name:
      return f'data/raw/{dataset_name}'
   if "int" in dataset_name:
      return f'data/int/{dataset_name}'
   ....

```

## Let's add some typing.

using typing.get_type_hints, we can see what the user is intending to return from the node.  Could pipeline developers add specific defaults for each return type, with a fallback to memorydataset or pickledataset?  From the framework side it seems like it would be an easy dictionary lookup from the nodes creating the dataset.  If there happens to be multiple nodes that create the same dataset check that they would intend to return the same dataset type, if not fall back on the default.

![image](https://user-images.githubusercontent.com/22648375/127659962-f2e41008-c6a6-4639-b8a2-0b582b0e067f.png)

## Context

This would save me from writing yaml catalog entries, possibly making mistakes, and save users hours of frustration caused by misconfigured catalogs.

**Comment by cupdike** [comment]
This would be useful for distributed environments (e.g. Kubeflow) where MemoryDataSet cannot be used.
