### ISSUE TITLE
[KED-1054] Add option to kedro build-docs which also opens the documentation

### ISSUE THREAD

**Issue by datajoely** [quantumblacklabs/kedro#86]
## Description
I find myself writing '`kedro build-docs ; open docs/build/html/index.html`', adding a simple 
`--open` argument would be appreciated. I do plan to PR this myself, I'm just not sure when I have time.

## Context
- Saves time
- Is almost always the next action after running the command

## Possible Implementation
- Add CLI argument

## Possible Alternatives
N/A

**Comment by Flid** [comment]
Correct me if I'm wrong, but that's MacOS-specific, and `xdg-open` should be used on Linux.
That might be a cross-platform solution: https://docs.python.org/3.7/library/webbrowser.html

**Comment by Pet3ris** [comment]
@datajoely - as a temporary fix, I'd recommend looking at the `entr` CLI [tool](http://eradman.com/entrproject/).

You can use it like so:

```bash
ls *.py | entr kedro build-docs && open docs/build/html/index.html
```

Effectively it would allow you to create a live reload server that watches for changes in Python source files and automatically serves the up-to-date documentation.

**Comment by mzjp2** [comment]
I thought this'd be a useful feature too! I built it for myself in my fork here: https://github.com/mzjp2/kedro/commit/468f328b5e774130fc367dea763ee6d3f3f79205

Happy to PR it (it's ready), if you want @datajoely, but equally also happy to let you if you want. :)

**Comment by mzjp2** [comment]
I've opened a PR, but feel free to close it in favour of Joel's if he makes one. :)
