### ISSUE TITLE
Partitioned Dataset should wipe directory before writing into it

### ISSUE THREAD

**Issue by jan-kaufmann** [quantumblacklabs/kedro#868]
## Description
Partitioned dataset allows to split a data set into multiple files during write.
This will create new files or overwrite existing files if they already exist but it will not delete any existing files!

Let's say my pipeline outputs 3 objects and I use PartitionedDataset to write them to JSON objects. It will generate 1.JSON, 2.JSON and 3.JSON. If my input data is updated and one object (2.JSON) is deleted, it will update all existing objects but ignore the deletion: 1.JSON*, 2.JSON, 3.JSON*

My directory is now in a state where old and new data are mixed - this is really hard to detect and can cause a lot of problems for subsequential pipelines that use this data as input.

## Possible Implementation
Always wipe the directory before writing partitioned data sets (maybe match a regex expression on the filename_suffix)

**Comment by jan-kaufmann** [comment]
this is potentially a bug report and not a feature request

**Comment by datajoely** [comment]
I @jan-kaufmann - as a rule we avoid wiping any data to prevent people losing their work accidentally. I would suggest if this is important to your use case, I would recommend subclassing `PartitionedDataSet` and modifying it to behave so you suggest.

**Comment by deepyaman** [comment]
> I @jan-kaufmann - as a rule we avoid wiping any data to prevent people losing their work accidentally. I would suggest if this is important to your use case, I would recommend subclassing `PartitionedDataSet` and modifying it to behave so you suggest.

@datajoely I'm inclined to agree with @jan-kaufmann here; this seems like it could be a legit "bug" in some people's eyes, though, because they may read back different data than they wrote due to leftovers from a previous run.

It's also not trivially possible to write partitions from different parts of the run, which means that use case where you want to build up a `PartitionedDataSet` isn't common (i.e. write 3 partitions from one node, another 2 from another note, etc.). `IncrementalDataSet` could represent a use case where things are built up over runs, so maybe that case is worth giving special attention to (I feel like I'm least familiar with this/never used it in my years of working with Kedro).

Maybe it's possible to add an `overwrite` option to `PartitionedDataSet`, which can initially default to `False` and maybe transition to `True` if that's what people generally want?

**Comment by jan-kaufmann** [comment]
In my specific use case I am preprocessing and cleaning data for an external system that expects one json file per data entry. So multiple thousands of files that might get changed/deleted between runs.

I can implement a workaround / custom implementation for this but it might be valuable for other people as @deepyaman pointed out. A flag that is `False` by default would be good solution - I understand your reservations against deleting data.

A hint to point out this behavior in the documentation would be good, though.

**Comment by datajoely** [comment]
Thanks I'll make a documentation ticket now for sure.

**Comment by Galileo-Galilei** [comment]
Just for the record, this is also true for ``MatplotlibWriter``. A situation which arises quite often is the following: 
- I have a node which returns a dict of images, saved by ``MatplotlibWriter`` in the catalog. (exemple: some per-variables informations for my machine learning model)
- This ``Dict[Figure]`` contains a dynamic number of images which varies between runs (the number of variables changes while I am experimenting). 

I am often hit by the following issue: 

1. Run 1: I save ``{image1.png: fig1, image2.png: fig2, image3.png: fig4}``. My data/08_reproting folder contains 3 files: image1.png, image2.png, image3.png
1. Run 2: I save ``{image1.png: fig1bis, image4.png: fig4}``. My data/08_reporting folder contains 4 files (!!): image1.png (from run 2), image2.png (**from run 1!!**), image3.png (**from run 1!!**), image4.png (from run 2). This is very confusing and error prone. 

I totally agree with creating an optional ``overwrite`` argument and setting it to ``False`` by default, this would be really convenient.

**Comment by datajoely** [comment]
This is on our backlog, but we'd be happy to accept a PR if you get there before us :)

**Comment by AntonyMilneQB** [comment]
This is done in #970 (thanks Deepyaman) both for `PartitionedDataSet` and `MatplotlibWriter` as suggested above. 🙂
