### ISSUE TITLE
Unable to load excel file

### ISSUE THREAD

**Issue by off99555** [quantumblacklabs/kedro#908]
## Description
When I was following this tutorial: 
https://kedro.readthedocs.io/en/stable/03_tutorial/03_set_up_data.html

And running this command:
```py
shuttles = catalog.load("shuttles")
```

I got this error:
```
DataSetError: Failed while loading data from data set ExcelDataSet(filepath=C:/Users/off99/Documents/Code/tutorials/kedro/kedro-tutorial/data/01_raw/shuttles.xlsx, load_args={'engine': xlrd}, protocol=file, save_args={'index': False}, writer_args={'engine': xlsxwriter}).
Your version of xlrd is 2.0.1. In xlrd >= 2.0, only the xls format is supported. Install openpyxl instead.
```

I also tried to install openpyxl like it asks, but it said that I already have openpyxl installed.
```
>pip install openpyxl -U
Requirement already satisfied: openpyxl in c:\users\off99\anaconda3\envs\kedro\lib\site-packages (3.0.9)
Requirement already satisfied: et-xmlfile in c:\users\off99\anaconda3\envs\kedro\lib\site-packages (from openpyxl) (1.1.0)
```

## Context
I am unable to load the dataset while following the tutorial.

## Steps to Reproduce
Create the project using `kedro new` then download excel dataset in the tutorial into your data folder.
```bash
conda create -n kedro python=3.8.11
conda activate kedro
kedro build-reqs
pip install -r src/requirements.txt
curl -o data\01_raw\shuttles.xlsx https://quantumblacklabs.github.io/kedro/shuttles.xlsx
kedro ipython
shuttles = catalog.load("shuttles")
```

## Expected Result
I can load dataset.

## Actual Result
Cannot load dataset.

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.17.5
* Python version used (`python -V`): 3.8.11
* Operating system and version: Windows 10 Build 19043.1237

**Comment by sbrugman** [comment]
Are you sure you've installed in the right environment? In a notebook you can try:

> import sys
> !{sys.executable} -m pip install -U [package]

This ensures you install the package in the same environment. Note that you probably need to restart your kernel.

**Comment by off99555** [comment]
Thanks. It's the problem of me installing conda with the option of putting conda binaries on `PATH` environment variable. And that makes new environent try to access the base environment whenever it doesn't have a certain library.
