### ISSUE TITLE
Add Kedro to stackshare

### ISSUE THREAD

**Issue by lucasjamar** [quantumblacklabs/kedro#915]
## Description
Stackshare is a website that allows people to share their experience on the technologies they used to implement their project and to ask for advice wrt to how to implement new projects.
It would seem only natural to add kedro: https://stackshare.io/submit.
It would be cool to add it to the list of data science tools. https://stackshare.io/data-science-tools
I didn't want to add it myself as I am not a core member of the Kedro team and maybe you guys don't want to see it there :)

**Comment by datajoely** [comment]
Posting for reference - there are two ways to submit, the link posted by @lucasjamar above, but also the Vendor route:
https://stackshare.io/vendors

**Comment by datajoely** [comment]
It's up! https://stackshare.io/kedro#description
