### ISSUE TITLE
Add kedro-airflow-k8s plugin to list of Community Developed Plugins

### ISSUE THREAD

**Issue by yetudada** [quantumblacklabs/kedro#917]
## Description

We need to update our list of community developed plugins, as our ecosystem grows, this task focuses on adding the `kedro-airflow-k8s` plugin to our [Community Developed Plugins page](https://github.com/quantumblacklabs/kedro/blob/master/docs/source/07_extend_kedro/04_plugins.md#community-developed-plugins).

## Possible Implementation
Follow the process in our [Contribution Guide](https://github.com/quantumblacklabs/kedro/blob/master/CONTRIBUTING.md), and [add a new bullet at the end of this list](https://github.com/quantumblacklabs/kedro/blob/master/docs/source/07_extend_kedro/04_plugins.md#community-developed-plugins) with the following: 
```
- [kedro-airflow-k8s](https://github.com/getindata/kedro-airflow-k8s), [GetInData](https://github.com/getindata), a plugin that enable running a Kedro pipeline with Airflow on Kubernetes Cluster
```

**Comment by pedrogengo** [comment]
Hey, can I get it?
