### ISSUE TITLE
Update README.md image

### ISSUE THREAD

**Issue by yetudada** [quantumblacklabs/kedro#918]
## Description
We need to update the image showcasing [Kedro-Viz](https://github.com/quantumblacklabs/kedro-viz) on the [Kedro README.md](https://github.com/quantumblacklabs/kedro#readme). 

## Possible Implementation
We need to do a few things in this PR: 

- Delete the current image on the [Kedro README.md](https://github.com/quantumblacklabs/kedro#readme)
- And link to the new one that's on the [Kedro-Viz README.md](https://github.com/quantumblacklabs/kedro-viz#readme)

To accomplish this, do the following: 
- Follow the process in our [Contribution Guide](https://github.com/quantumblacklabs/kedro/blob/master/CONTRIBUTING.md)
- Delete [this image](https://github.com/quantumblacklabs/kedro/blob/master/static/img/pipeline_visualisation.png)
- Go the [Kedro README.md](https://github.com/quantumblacklabs/kedro#what-are-the-main-features-of-kedro)
  - Remove this line `![Kedro-Viz Pipeline Visualisation](https://raw.githubusercontent.com/quantumblacklabs/kedro/develop/static/img/pipeline_visualisation.png)`
  - And substitute that removed line with the following `![Kedro-Viz Pipeline Visualisation](https://github.com/quantumblacklabs/kedro-viz/blob/main/.github/img/banner.png)`

**Comment by ManishS6** [comment]
@yetudada I would like to work on this
Please assign this task to me.

**Comment by rutuja1121** [comment]
I would like to work on this

**Comment by yetudada** [comment]
> @yetudada I would like to work on this Please assign this task to me.

Sure, I've got @ManishS6 down for this first.

**Comment by ManishS6** [comment]
@yetudada I have completed the task and have created a PR #925 for the same.

**Comment by MerelTheisenQB** [comment]
This has now been done! Thanks to @ManishS6 🚀
