### ISSUE TITLE
Add example YAML definitions to common dataset Python docstrings

### ISSUE THREAD

**Issue by datajoely** [quantumblacklabs/kedro#920]
## Description
Users often ask for an easy way to look up the relevant YAML dataset configuration for use in the DataCatalog would look like. We include a series of examples in this [section of the documentation](https://kedro.readthedocs.io/en/stable/05_data/01_data_catalog.html#using-the-data-catalog-with-the-yaml-api), but it's not especially easy to (1) link to as these aren't under headings (2) find via search engine for the same reason.

This would be useful for all datasets - but the highest priority are those which drive most traffic to our documentation website:

- `kedro.extras.datasets.pandas.CSVDataSet`
- `kedro.extras.datasets.spark.SparkDataSet`
- `kedro.io.PartitionedDataSet`
- `kedro.extras.datasets.pandas.ParquetDataSet`
- `kedro.extras.datasets.pickle.PickleDataSet`
- `kedro.extras.datasets.pandas.ExcelDataSet`
- `kedro.extras.datasets.pandas.SQLQueryDataSet`
- `kedro.extras.datasets.pandas.GBQTableDataSet`
- `kedro.extras.datasets.spark.SparkHiveDataSet`

## Possible Implementation

```python
def __init__(
        self,
        filepath: str,
        backend: str = "pickle",
        load_args: Dict[str, Any] = None,
        save_args: Dict[str, Any] = None,
        version: Version = None,
        credentials: Dict[str, Any] = None,
        fs_args: Dict[str, Any] = None,
    ) -> None:
        """Creates a new instance of ``PickleDataSet`` pointing to a concrete Pickle
        file on a specific filesystem. ``PickleDataSet`` supports four backends to
        serialize/deserialize objects: `pickle`, `joblib`, `dill`, and `compress_pickle`.

        Example YAML data catalog entry:
        >>> airplanes:
        >>>     type: pickle.PickleDataSet
        >>>     filepath: data/06_models/airplanes.pkl
        >>>     backend: pickle

        Args:
            filepath: Filepath in POSIX format to a Pickle file prefixed with a protocol like
                `s3://`. If prefix is not provided, `file` protocol (local filesystem) will be used.
                The prefix should be any protocol supported by ``fsspec``.
                Note: `http(s)` doesn't support versioning.
            backend: Backend to use, must be one of ['pickle', 'joblib', 'dill', 'compress_pickle'].
                Defaults to 'pickle'.
        """
```

## To accomplish this, do the following: 
- Follow the process in our [Contribution Guide](https://github.com/quantumblacklabs/kedro/blob/master/CONTRIBUTING.md)

**Comment by avan-sh** [comment]
Hey @datajoely, I'd love to add these yaml examples. Please assign this to me.

**Comment by avan-sh** [comment]
Took a stab at this for CSV dataset, taking some inspiration from the [old discussion](https://github.com/quantumblacklabs/kedro/issues/579). 
The new docs would look as below, [hyperlinked to](https://kedro.readthedocs.io/en/stable/05_data/01_data_catalog.html#using-the-data-catalog-with-the-yaml-api). 

![image](https://user-images.githubusercontent.com/11796986/136081763-e5815c98-216c-4cb1-b17e-7c4f39cf43eb.png)

Would love to hear any suggestions for changes before I add it to other datasets.

**Comment by datajoely** [comment]
@avan-sh this is an excellent start! Any idea how to get the code block to highlight as YAML not Python?

**Comment by datajoely** [comment]
I'd also look to steal examples from [this page](https://kedro.readthedocs.io/en/stable/05_data/01_data_catalog.html#using-the-data-catalog-with-the-yaml-api), and opt for those that look complex with `load_args` etc.
