### ISSUE TITLE
Global credentials file for multiple pipelines

### ISSUE THREAD

**Issue by nicpayne713** [quantumblacklabs/kedro#930]
## Description
I'm always frustrated when credentials for a pipeline changes, or I need to help a teammate with a specific pipeline but I don't have the right credentials handy, or the credentials rotate without me knowing, and then we spend minutes/hours getting it sorted out before I can even jump in to help...

## Context
Our team builds many kedro pipelines that get deployed via Docker, but one issue we have is that each pipeline has its own credentials file... so each user maintains a project specific `credentials.yml` in a `local` directory ignored by `gitignore`, then when we build in AZDO we have to upload the right file and give permissions to the build pipeline for that file - when credentials rotate we then have to remember which pipelines used the now-expired credentials. For our group, it would be awesome to have a central place to store credentials where users can clone a repo securely, decrypt, and have all pipelines on their machines reference the one-safe-source credentials, and then our builds can all reference the same credentials file so updates roll out automagically.

## Possible Implementation

I think it'd be great if a kedro project could just read `GLOBAL_KEDRO_CREDENTIALS` or something from an env variable, or be configured in a way to go outside the project context to get a file with the right credentials/keys in it.

## Possible Alternatives
I'm a noob in the space in the first place so I don't have an alternative idea here

**Comment by datajoely** [comment]
Hi @nicpayne713 this is absolutely something we want to improve out of the box. You can read our (now very long) issue #891 regarding how we want to improve the configuration experience more holistically. 

If you want to introduce environment variables to your credentials workflow today, this is how you can do it yourself by editing `hooks.py`. 

![image](https://user-images.githubusercontent.com/35801847/135987442-366aabbd-e62d-4aae-a2a0-bbc39300e163.png)

I'm pretty sure this should work as you describe.
