### ISSUE TITLE
Implement `delete_existing_files_on_save` method for `ParititionedDataSet` and `MatplotlibWriter` 

### ISSUE THREAD

**Issue by datajoely** [quantumblacklabs/kedro#936]
## Description
Several users have discussed the fact that `PartitionedDataSet` and `MatplotlibWriter` datasets do not clear the contents of the directories they write to when saving. A discussion can be found on this issue https://github.com/quantumblacklabs/kedro/issues/868 

We should keep the current behaviour as default, but provide an extra argument that the user can explicitly ask Kedro to wipe the contents of a directory at save time.

## Possible Implementation
(Optional) Suggest an idea for implementing the addition or change.

`fsspec` library provides a `delete()` method which can be used for this purposes.

## Possible Alternatives
(Optional) Describe any alternative solutions or features you've considered.

We could simply update the documentation to highlight that current default behaviour does not delete old data.

**Comment by deepyaman** [comment]
I can take a stab at this. Can we call it `overwrite` instead of `delete_existing_files_on_save`? 😂
