### ISSUE TITLE
[KED-1057] Modify the test_run.py file to be directly executable

### ISSUE THREAD

**Issue by AlexandreOuellet** [quantumblacklabs/kedro#96]
## Description
One way of developing is to create unit tests, and then make them work.  An easy way to do that is to have your unit tests runnable directly with a main entry point

## Context
While using vs code, I often set my launch to a single unit test to debug whatever piece of code I am currently working on.  This way, I ensure that I can work on separate concerns, and that those concerns are tested properly.

## Possible Implementation
Modify the cookiecutter template project to also include :

```
if __name__ == "__main__":
    import sys
    pytest.main(sys.argv + ["--no-cov"])
```
at the end of test_run.py

**Comment by Flid** [comment]
I'm not against the change, but just curious: is it actually easier to type `python src/tests/test_run.py tests/test_my_module.py` than `pytest tests/test_my_module.py`? Any added benefits? Is it a common way of doing things (I've never seen it done like that, but maybe it's just me)?
In other words, I'd like to know more about the motivation.

**Comment by AlexandreOuellet** [comment]
This enables me to have multiple run configuration (in vs code) to launch my test.  I can simply set my run configuration to point to the unit tests of the thing I am working on, press F5, and I am debugging my code through unit tests.

There is currently no way to do that with a single keypress in vscode.  According to https://code.visualstudio.com/docs/python/testing#_debug-tests, you can customize how the tests are run, but not to debug a specific file.

Essentially : I am lazy, and wants to press F5 to debug a single test file (and my code) in vscode.  I have not found a way to do this yet in vscode with launch.json, except if I do the previous snippet of code.  I can essentially have this launch.json file :
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        },
        {
            "name": "Python: Test Feature X",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/src/tests/test_feature_x.py",
            "console": "integratedTerminal"
        },
        {
            "name": "Python: Test Feature Y",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/src/tests/test_feature_y.py",
            "console": "integratedTerminal"
        }
    ]
}
```

**Comment by yetudada** [comment]
Hi @AlexandreOuellet, thank you for creating the #98 PR for this. I'm going to put a JIRA number assignment to this so that we can track it.

**Comment by DmitriiDeriabinQB** [comment]
Hi @AlexandreOuellet, thanks again for your suggestion! 

So after having an internal discussion we decided not to add this into the project template. Here are our concerns regarding this:
1. Since the template also serves the purpose of the tutorial to some extent, this may give the false impression of a suggested way of running project tests for less experienced Python users
2. In your example coverage behaviour is going to be different depending on how the test file is being run, we'd rather recommend explicit test run configurations
3. We'd like to avoid putting extra non-essential logic in the tests and not tempt users to do so

**Comment by AlexandreOuellet** [comment]
I don't quite agree with point 2 I'd argue that this is a different use case than for code coverage : it is to make Test Driven Development a bit easier on the developer's end, hence `the --no-cov` argument was added to not add to the confusion.  This code does not affect how `kedro run` or `pytest .` works in any way, just in the case where you ask python to execute that file directly (which is kind of the point of this change)

Nevertheless, I definitely agree with point 1 and 3.

Thanks for the feedback!
