### ISSUE TITLE
Redis.PickleDataset

### ISSUE THREAD

**Issue by lucasjamar** [quantumblacklabs/kedro#966]
## Description
A dataset for reading and writing data to a Redis cache. 

## Context
Redis is a super fast key value store. This would allow users to retrieve data shared between users in a super fast way.

## Possible Implementation
Currently, I use redis with pickle dumps and pickle loads as mentioned here: https://stackoverflow.com/a/20400288/12403925. I currently have my own custom redis.PickleDataSet that I could contribute.

## Possible Alternatives
Other possibilities include saving a JSON to Redis but pickle would allow saving any python object. Pickle is also much faster.
Furthermore, the pyarrow serialization/ deserialization methods have been deprecated so we cannot use it anymore.
https://stackoverflow.com/questions/57949871/how-to-set-get-pandas-dataframes-into-redis-using-pyarrow

**Comment by datajoely** [comment]
I think this is a neat idea - it would be great to see a pseudo-code YAML catalog entry for how this could look?

**Comment by datajoely** [comment]
I think it's reasonable for datasets to not work with the `ParallelRunner` - in fact this has lots of parallels with the `SparkDataSet` which cannot for similar reasons. We recommend people use the `ThreadRunner` in this situation, presumably that would help here too. 

https://kedro.readthedocs.io/en/0.17.5/11_tools_integration/01_pyspark.html#tips-for-maximising-concurrency-using-threadrunner

As long as it's documented somewhere I think that's fine :)

**Comment by juan-carlos-calvo** [comment]
I would also find this dataset useful

**Comment by datajoely** [comment]
We'd love to see this contributed :)
