### ISSUE TITLE
[KED-2900] Remove Rope 0.19.0 dependency subject to GPL license

### ISSUE THREAD

**Issue by theauheral** [quantumblacklabs/kedro#967]
## Description
Remove or bump Rope dependency version subject to GPL license (Next versions: LGPLv3)

## Context
Kedro version 0.17.5 gets blocked by corporate Nexus as depends on Rope which has an GPL license.

## Steps to Reproduce
Have corporate nexus not allowing LGPv3 license usage.

## Expected Result
Being able to use Kedro in a corporate setting.

## Your Environment
Kedro 0.17.5

**Comment by datajoely** [comment]
@idanov FYI

**Comment by AntonyMilneQB** [comment]
Thanks very much for raising this and figuring out the fix @theauheral. We've bumped to rope 0.21.0 in e9b288972dc6b7c440a9330e24b00ea18e1ccd1d - this will be released in kedro 0.17.6.
