### ISSUE TITLE
Add support for Stata datasets

### ISSUE THREAD

**Issue by vavalomi** [quantumblacklabs/kedro#971]
## Description
Add support for Stata datasets. 

## Context
Stata (www.stata.com) is a popular statistical analysis software used in wide range of fields - economics, biostatistics, education, medicine, and many more.

## Possible Implementation
Pandas already includes read_stata() and to_stata() functions so the implementation could be straightforward based on already implemented pandas data formats.

**Comment by AntonyMilneQB** [comment]
This should now be possible in 0.17.6 (to be released soon) thanks to @datajoely's new [`pandas.GenericDataSet']`(https://kedro.readthedocs.io/en/latest/kedro.extras.datasets.pandas.GenericDataSet.html#kedro.extras.datasets.pandas.GenericDataSet)! Just specify `file_format: stata`. I'm going to close this issue, but do let us know if this doesn't work for some reason 🙂
