### ISSUE TITLE
Dataset for saving a sklearn pipeline with a tensorflow estimator

### ISSUE THREAD

**Issue by juan-carlos-calvo** [quantumblacklabs/kedro#982]
## Description

A scikit learn pipeline where the last step is an instance of KerasRegressor [cannot be saved directly as a pickle dataset](https://stackoverflow.com/questions/37984304/how-to-save-a-scikit-learn-pipline-with-keras-regressor-inside-to-disk). To save it using the current datasets would require two datasets: one for the scikit learn pipeline without the tensorflow model, and another for the tensorflow model. However, managing this model in this way would be cumbersome because to make an inference say, I would need to load both the scikit learn pipeline, and the tf model, put them together, and predict.

## Context

When working with tensorflow models, users might want to add them to a scikit-learn pipeline.

## Possible Implementation
(Optional) Suggest an idea for implementing the addition or change.

## Possible Alternatives
(Optional) Describe any alternative solutions or features you've considered.

**Comment by AntonyMilneQB** [comment]
Hi @juan-carlos-calvo, just wondering if you had any updates on this? Do you think we still need the PR for a new dataset?

**Comment by juan-carlos-calvo** [comment]
I ran a test with the simple example in the docstring of the dataset implementation (using the latest tensorflow) and it throws the same error `TypeError: cannot pickle 'weakref' object`

**Comment by AntonyMilneQB** [comment]
Hmm, that's weird - I just tried this out  and it works perfectly for me. Take a look at [my environment](https://gitpod.io#snapshot/aababbb2-1005-4798-929d-a908258b596d) and the example project in the `blah` directory. `kedro run` seems to work ok, as does loading up the datasets in `kedro ipython`. What am I doing differently here? 🤔

**Comment by juan-carlos-calvo** [comment]
seems you are absolutely right!
not sure if it was because I tried the version just before 2.7 but anyways, it works! thank you very much for taking the time to verify this
