### ISSUE TITLE
[KED-1058] Several issues with Spaceflights tutorial documentation

### ISSUE THREAD

**Issue by IonutBarbuMcK** [quantumblacklabs/kedro#99]
## Description
1. Short description of the problem here.
Command at page https://kedro.readthedocs.io/en/latest/03_tutorial/03_set_up_data.html says `mkdir -p src/kedro_tutorial/io && touch src/kedro_tutorial/io/__init__.py`
which does not execute under Windows. Because they are Unix commands

Please be specific about this
the same holds true for the (linux) commands suggested to download files

2. the format of the .csv files under heading "Adding your datasets to data" is actually .txt

**Comment by yetudada** [comment]
Hi @IonutBarbuMcK! Thank you so much for raising this issue. I'm adding the need for these corrections to the backlog. You mentioned several issues, are they related to the individual links for the each of the download files? 

And I should just check, did you manage to download the files in the end?

**Comment by IonutBarbuMcK** [comment]
I managed in the end to download the files. They were incorrectly in the .txt format (the contents of the file was comma separated) and just changed the extension

**Comment by Flid** [comment]
Hi @IonutBarbuMcK 
I'm trying to understand what's going on regarding the second issue, the CSV<->TXT

I'm on MacOS+Chrome, open the documentation, click the link with reviews.csv (the link is https://raw.githubusercontent.com/quantumblacklabs/kedro/develop/docs/source/03_tutorial/data/reviews.csv), and Chrome shows its content as a text indeed. If I try to "Save link as..." on the link, it suggests saving it as text. 
Is that the issue you are facing?

Using the commands provided (with `curl`) seems to work on *nix, but not on Windows indeed, that needs to be addressed.

**Comment by lorenabalan** [comment]
Hi @IonutBarbuMcK , the Windows commands have been addressed in these commits: https://github.com/quantumblacklabs/kedro/commit/2a9bd0116a0c2586c4009617d34fc79a1634aa85 & https://github.com/quantumblacklabs/kedro/commit/cd26ab14193490d4de144fb3d915adc2e70b4ba6 
We have also updated the links for the 3 files to download in this commit: https://github.com/quantumblacklabs/kedro/commit/9f27314e0dbf1490328a521b536da9bc5c12b3ab
I'll go ahead and close this issue as resolved.
